### PR TITLE
MH-13028: Clean up mockup

### PR DESCRIPTION
**Pull request by jaysuz**
This will update the mockup in the following ways:

- Reducing the event data to the most relevant (see 3474586a5c184ecd1f1f7b15432d1be2209b2c74)
- Addition of two tiny binary files to correctly showcase video editor

### CODE REVIEW

**Comment by gregorydlogan** [comment]
Things which are WIP ought to have the onhold tag.  Makes life easier to sort out what's actually ready for review :)

**Comment by lkiesow** [comment]
In general, even better would be to prepare the patch first and only then create the pull requests. That way, they do not get mixed up with things ready to be reviewed. Feel free to keep this though. That's no hard requirement. Thanks for working on this at all :D

**Comment by staubesv** [comment]
@lkiesow The patch is now ready for review. To best test this: Run grunt serve without this patch and play around a little. Then merge (while grunt serve is still running) this PR und hit the refresh page on your browser. Things should "feel" better now. In particular the video editor ;-)

**Comment by lkiesow** [comment]
@jaysuz, would you mind me quashing the commits when I do the merge?

**Comment by jaysuz** [comment]
@lkiesow not at all, please go ahead 👍

**Comment by lkiesow** [comment]
The mockup is still far from being perfect, but it is much better than it was before. Thanks for the patch → merged

**Pull request merged**
