### PR TITLE
SchedulerService updates Elasticsearch indices directly (last one!)

### PR DESCRIPTION
**Pull request by KatrinIhler**
With this PR, the SchedulerService now directly updates the Elasticsearch indices for the Admin UI and the External API instead of sending messages for that. It still sends these messages for updating the life events, however. I tried ripping that out as well, but it was more complicated than I expected...

This is based on #2742 because without it, funky things happen when deleting scheduled events, probably because of timing issues.

This is the last of the services populating the Elasticsearch indices I had to change, so with this one done, every update of them will now happen directly. This means that it will be finally safe to rebuild the index all at once, because one service will be guaranteed to be done before the next one starts. That makes updates with an index rebuild much less of a headache, because we no longer need to babysit this. Yay! :tada:

### CODE REVIEW

**Comment by mliradelc** [comment]
Hi Katrin, I'm reviewing this PR, from what are you saying, is needed to try with #2742 ? It could not be better to merge the two pr into one? If that is, I tried to merge this pr into #2742, and I found some merge conflicts.

**Comment by mliradelc** [comment]
is normal to get those warnings when building?:

```bash
[INFO] --- maven-bundle-plugin:3.5.0:bundle (default-bundle) @ opencast-elasticsearch-impl ---
[WARNING] Bundle org.opencastproject:opencast-elasticsearch-impl:bundle:11-SNAPSHOT : Export org.opencastproject.elasticsearch.impl,  has 1,  private references [org.apache.lucene.search],
[WARNING] Bundle org.opencastproject:opencast-elasticsearch-impl:bundle:11-SNAPSHOT : Export org.elasticsearch,  has 1,  private references [org.apache.lucene.util],
[WARNING] Bundle org.opencastproject:opencast-elasticsearch-impl:bundle:11-SNAPSHOT : Export org.elasticsearch.action,  has 1,  private references [org.apache.lucene.util],
[WARNING] Bundle org.opencastproject:opencast-elasticsearch-impl:bundle:11-SNAPSHOT : Export org.elasticsearch.action.admin.cluster.stats,  has 1,  private references [com.carrotsearch.hppc],
[WARNING] Bundle org.opencastproject:opencast-elasticsearch-impl:bundle:11-SNAPSHOT : Export org.elasticsearch.action.bulk,  has 1,  private references [org.apache.lucene.util],
[WARNING] Bundle org.opencastproject:opencast-elasticsearch-impl:bundle:11-SNAPSHOT : Export org.elasticsearch.action.explain,  has 1,  private references [org.apache.lucene.search],
[WARNING] Bundle org.opencastproject:opencast-elasticsearch-impl:bundle:11-SNAPSHOT : Export org.elasticsearch.action.search,  has 2,  private references [com.carrotsearch.hppc, org.apache.lucene.search],
[WARNING] Bundle org.opencastproject:opencast-elasticsearch-impl:bundle:11-SNAPSHOT : Export org.elasticsearch.action.termvectors,  has 1,  private references [org.apache.lucene.index],
[WARNING] Bundle org.opencastproject:opencast-elasticsearch-impl:bundle:11-SNAPSHOT : Export org.elasticsearch.client,  has 1,  private references [org.apache.http.impl.nio.client],
[WARNING] Bundle org.opencastproject:opencast-elasticsearch-impl:bundle:11-SNAPSHOT : Export org.elasticsearch.client.eql,  has 1,  private references [org.apache.lucene.search],
[WARNING] Bundle org.opencastproject:opencast-elasticsearch-impl:bundle:11-SNAPSHOT : Export org.elasticsearch.cluster,  has 1,  private references [com.carrotsearch.hppc],
[WARNING] Bundle org.opencastproject:opencast-elasticsearch-impl:bundle:11-SNAPSHOT : Export org.elasticsearch.cluster.routing,  has 1,  private references [com.carrotsearch.hppc],
[WARNING] Bundle org.opencastproject:opencast-elasticsearch-impl:bundle:11-SNAPSHOT : Export org.elasticsearch.common,  has 3,  private references [com.carrotsearch.hppc, com.carrotsearch.hppc.cursors, org.apache.lucene.util],
[WARNING] Bundle org.opencastproject:opencast-elasticsearch-impl:bundle:11-SNAPSHOT : Export org.elasticsearch.common.bytes,  has 1,  private references [org.apache.lucene.util],
[WARNING] Bundle org.opencastproject:opencast-elasticsearch-impl:bundle:11-SNAPSHOT : Export org.elasticsearch.common.collect,  has 4,  private references [com.carrotsearch.hppc, com.carrotsearch.hppc.cursors, com.carrotsearch.hppc.predicates, com.carrotsearch.hppc.procedures],
[WARNING] Bundle org.opencastproject:opencast-elasticsearch-impl:bundle:11-SNAPSHOT : Export org.elasticsearch.common.geo,  has 3,  private references [org.apache.lucene.document, org.apache.lucene.geo, org.apache.lucene.index],
[WARNING] Bundle org.opencastproject:opencast-elasticsearch-impl:bundle:11-SNAPSHOT : Export org.elasticsearch.common.io.stream,  has 1,  private references [org.apache.lucene.util],
[WARNING] Bundle org.opencastproject:opencast-elasticsearch-impl:bundle:11-SNAPSHOT : Export org.elasticsearch.common.joda,  has 1,  private references [org.joda.time.format],
[WARNING] Bundle org.opencastproject:opencast-elasticsearch-impl:bundle:11-SNAPSHOT : Export org.elasticsearch.common.lucene,  has 5,  private references [org.apache.lucene.document, org.apache.lucene.index, org.apache.lucene.search, org.apache.lucene.store, org.apache.lucene.util],
[WARNING] Bundle org.opencastproject:opencast-elasticsearch-impl:bundle:11-SNAPSHOT : Export org.elasticsearch.common.lucene.index,  has 4,  private references [org.apache.lucene.codecs, org.apache.lucene.index, org.apache.lucene.search, org.apache.lucene.util],
[WARNING] Bundle org.opencastproject:opencast-elasticsearch-impl:bundle:11-SNAPSHOT : Export org.elasticsearch.common.lucene.search,  has 7,  private references [org.apache.lucene.analysis, org.apache.lucene.index, org.apache.lucene.search, org.apache.lucene.search.similarities, org.apache.lucene.search.spans, org.apache.lucene.util, org.apache.lucene.util.automaton],
[WARNING] Bundle org.opencastproject:opencast-elasticsearch-impl:bundle:11-SNAPSHOT : Export org.elasticsearch.common.lucene.search.function,  has 2,  private references [org.apache.lucene.index, org.apache.lucene.search],
[WARNING] Bundle org.opencastproject:opencast-elasticsearch-impl:bundle:11-SNAPSHOT : Export org.elasticsearch.common.lucene.store,  has 1,  private references [org.apache.lucene.store],
[WARNING] Bundle org.opencastproject:opencast-elasticsearch-impl:bundle:11-SNAPSHOT : Export org.elasticsearch.common.lucene.uid,  has 1,  private references [org.apache.lucene.index],
[WARNING] Bundle org.opencastproject:opencast-elasticsearch-impl:bundle:11-SNAPSHOT : Export org.elasticsearch.common.regex,  has 1,  private references [org.apache.lucene.util.automaton],
[WARNING] Bundle org.opencastproject:opencast-elasticsearch-impl:bundle:11-SNAPSHOT : Export org.elasticsearch.common.settings,  has 1,  private references [org.apache.lucene.util],
[WARNING] Bundle org.opencastproject:opencast-elasticsearch-impl:bundle:11-SNAPSHOT : Export org.elasticsearch.common.util,  has 3,  private references [com.carrotsearch.hppc, org.apache.lucene.store, org.apache.lucene.util],
[WARNING] Bundle org.opencastproject:opencast-elasticsearch-impl:bundle:11-SNAPSHOT : Export org.elasticsearch.common.xcontent,  has 1,  private references [org.joda.time.format],
[WARNING] Bundle org.opencastproject:opencast-elasticsearch-impl:bundle:11-SNAPSHOT : Export org.elasticsearch.discovery.zen,  has 1,  private references [com.carrotsearch.hppc],
[WARNING] Bundle org.opencastproject:opencast-elasticsearch-impl:bundle:11-SNAPSHOT : Export org.elasticsearch.gateway,  has 1,  private references [org.apache.lucene.store],
[WARNING] Bundle org.opencastproject:opencast-elasticsearch-impl:bundle:11-SNAPSHOT : Export org.elasticsearch.index,  has 3,  private references [org.apache.lucene.index, org.apache.lucene.search, org.apache.lucene.search.similarities],
[WARNING] Bundle org.opencastproject:opencast-elasticsearch-impl:bundle:11-SNAPSHOT : Export org.elasticsearch.index.analysis,  has 3,  private references [org.apache.lucene.analysis, org.apache.lucene.analysis.standard, org.apache.lucene.util],
[WARNING] Bundle org.opencastproject:opencast-elasticsearch-impl:bundle:11-SNAPSHOT : Export org.elasticsearch.index.cache.bitset,  has 4,  private references [org.apache.lucene.index, org.apache.lucene.search, org.apache.lucene.search.join, org.apache.lucene.util],
[WARNING] Bundle org.opencastproject:opencast-elasticsearch-impl:bundle:11-SNAPSHOT : Export org.elasticsearch.index.cache.query,  has 1,  private references [org.apache.lucene.search],
[WARNING] Bundle org.opencastproject:opencast-elasticsearch-impl:bundle:11-SNAPSHOT : Export org.elasticsearch.index.cache.request,  has 1,  private references [org.apache.lucene.util],
[WARNING] Bundle org.opencastproject:opencast-elasticsearch-impl:bundle:11-SNAPSHOT : Export org.elasticsearch.index.codec,  has 2,  private references [org.apache.lucene.codecs, org.apache.lucene.codecs.lucene87],
[WARNING] Bundle org.opencastproject:opencast-elasticsearch-impl:bundle:11-SNAPSHOT : Export org.elasticsearch.index.engine,  has 7,  private references [org.apache.lucene.analysis, org.apache.lucene.codecs, org.apache.lucene.index, org.apache.lucene.search, org.apache.lucene.search.similarities, org.apache.lucene.store, org.apache.lucene.util],
[WARNING] Bundle org.opencastproject:opencast-elasticsearch-impl:bundle:11-SNAPSHOT : Export org.elasticsearch.index.fielddata,  has 4,  private references [org.apache.lucene.index, org.apache.lucene.search, org.apache.lucene.search.join, org.apache.lucene.util],
[WARNING] Bundle org.opencastproject:opencast-elasticsearch-impl:bundle:11-SNAPSHOT : Export org.elasticsearch.index.fielddata.fieldcomparator,  has 2,  private references [org.apache.lucene.index, org.apache.lucene.search],
[WARNING] Bundle org.opencastproject:opencast-elasticsearch-impl:bundle:11-SNAPSHOT : Export org.elasticsearch.index.fielddata.ordinals,  has 4,  private references [org.apache.lucene.index, org.apache.lucene.search, org.apache.lucene.util, org.apache.lucene.util.packed],
[WARNING] Bundle org.opencastproject:opencast-elasticsearch-impl:bundle:11-SNAPSHOT : Export org.elasticsearch.index.fielddata.plain,  has 4,  private references [org.apache.lucene.index, org.apache.lucene.search, org.apach
e.lucene.util, org.apache.lucene.util.packed],
[WARNING] Bundle org.opencastproject:opencast-elasticsearch-impl:bundle:11-SNAPSHOT : Export org.elasticsearch.index.fieldvisitor,  has 2,  private references [org.apache.lucene.index, org.apache.lucene.util],
[WARNING] Bundle org.opencastproject:opencast-elasticsearch-impl:bundle:11-SNAPSHOT : Export org.elasticsearch.index.mapper,  has 8,  private references [org.apache.lucene.analysis, org.apache.lucene.codecs, org.apache.lucene.document, org.apache.lucene.index, org.apache.lucene.queries, org.apache.lucene.search, org.apache.lucene.search.spans, org.apache.lucene.util],
[WARNING] Bundle org.opencastproject:opencast-elasticsearch-impl:bundle:11-SNAPSHOT : Export org.elasticsearch.index.merge,  has 1,  private references [org.apache.lucene.index],
[WARNING] Bundle org.opencastproject:opencast-elasticsearch-impl:bundle:11-SNAPSHOT : Export org.elasticsearch.index.query,  has 7,  private references [org.apache.lucene.analysis, org.apache.lucene.index, org.apache.lucene.queryparser.classic, org.apache.lucene.search, org.apache.lucene.search.join, org.apache.lucene.search.similarities, org.apache.lucene.search.spans],
[WARNING] Bundle org.opencastproject:opencast-elasticsearch-impl:bundle:11-SNAPSHOT : Export org.elasticsearch.index.query.functionscore,  has 2,  private references [org.apache.lucene.index, org.apache.lucene.search],
[WARNING] Bundle org.opencastproject:opencast-elasticsearch-impl:bundle:11-SNAPSHOT : Export org.elasticsearch.index.query.support,  has 1,  private references [org.apache.lucene.search],
[WARNING] Bundle org.opencastproject:opencast-elasticsearch-impl:bundle:11-SNAPSHOT : Export org.elasticsearch.index.search,  has 7,  private references [org.apache.lucene.analysis, org.apache.lucene.index, org.apache.lucene.queryparser.classic, org.apache.lucene.queryparser.simple, org.apache.lucene.search, org.apache.lucene.search.join, org.apache.lucene.search.spans],
[WARNING] Bundle org.opencastproject:opencast-elasticsearch-impl:bundle:11-SNAPSHOT : Export org.elasticsearch.index.seqno,  has 1,  private references [com.carrotsearch.hppc],
[WARNING] Bundle org.opencastproject:opencast-elasticsearch-impl:bundle:11-SNAPSHOT : Export org.elasticsearch.index.shard,  has 5,  private references [com.carrotsearch.hppc, org.apache.lucene.index, org.apache.lucene.search, org.apache.lucene.store, org.apache.lucene.util],
[WARNING] Bundle org.opencastproject:opencast-elasticsearch-impl:bundle:11-SNAPSHOT : Export org.elasticsearch.index.similarity,  has 3,  private references [org.apache.lucene.index, org.apache.lucene.search, org.apache.lucene.search.similarities],
[WARNING] Bundle org.opencastproject:opencast-elasticsearch-impl:bundle:11-SNAPSHOT : Export org.elasticsearch.index.snapshots.blobstore,  has 1,  private references [org.apache.lucene.store],
[WARNING] Bundle org.opencastproject:opencast-elasticsearch-impl:bundle:11-SNAPSHOT : Export org.elasticsearch.index.store,  has 3,  private references [org.apache.lucene.index, org.apache.lucene.store, org.apache.lucene.util],
[WARNING] Bundle org.opencastproject:opencast-elasticsearch-impl:bundle:11-SNAPSHOT : Export org.elasticsearch.index.termvectors,  has 1,  private references [org.apache.lucene.index],
[WARNING] Bundle org.opencastproject:opencast-elasticsearch-impl:bundle:11-SNAPSHOT : Export org.elasticsearch.index.translog,  has 2,  private references [org.apache.lucene.index, org.apache.lucene.store],
[WARNING] Bundle org.opencastproject:opencast-elasticsearch-impl:bundle:11-SNAPSHOT : Export org.elasticsearch.indices,  has 1,  private references [org.apache.lucene.search],
[WARNING] Bundle org.opencastproject:opencast-elasticsearch-impl:bundle:11-SNAPSHOT : Export org.elasticsearch.indices.analysis,  has 1,  private references [org.apache.lucene.analysis],
[WARNING] Bundle org.opencastproject:opencast-elasticsearch-impl:bundle:11-SNAPSHOT : Export org.elasticsearch.indices.fielddata.cache,  has 2,  private references [org.apache.lucene.index, org.apache.lucene.util],
[WARNING] Bundle org.opencastproject:opencast-elasticsearch-impl:bundle:11-SNAPSHOT : Export org.elasticsearch.indices.recovery,  has 1,  private references [org.apache.lucene.store],
[WARNING] Bundle org.opencastproject:opencast-elasticsearch-impl:bundle:11-SNAPSHOT : Export org.elasticsearch.plugins,  has 2,  private references [org.apache.lucene.analysis, org.apache.lucene.store],
[WARNING] Bundle org.opencastproject:opencast-elasticsearch-impl:bundle:11-SNAPSHOT : Export org.elasticsearch.repositories,  has 1,  private references [org.apache.lucene.index],
[WARNING] Bundle org.opencastproject:opencast-elasticsearch-impl:bundle:11-SNAPSHOT : Export org.elasticsearch.repositories.blobstore,  has 1,  private references [org.apache.lucene.index],
[WARNING] Bundle org.opencastproject:opencast-elasticsearch-impl:bundle:11-SNAPSHOT : Export org.elasticsearch.script,  has 2,  private references [org.apache.lucene.index, org.apache.lucene.search],
[WARNING] Bundle org.opencastproject:opencast-elasticsearch-impl:bundle:11-SNAPSHOT : Export org.elasticsearch.search,  has 3,  private references [org.apache.lucene.index, org.apache.lucene.search, org.apache.lucene.util],

[WARNING] Bundle org.opencastproject:opencast-elasticsearch-impl:bundle:11-SNAPSHOT : Export org.elasticsearch.search.aggregations,  has 2,  private references [org.apache.lucene.index, org.apache.lucene.search],
[WARNING] Bundle org.opencastproject:opencast-elasticsearch-impl:bundle:11-SNAPSHOT : Export org.elasticsearch.search.aggregations.bucket,  has 3,  private references [org.apache.lucene.index, org.apache.lucene.search, org.apache.lucene.util.packed],
[WARNING] Bundle org.opencastproject:opencast-elasticsearch-impl:bundle:11-SNAPSHOT : Export org.elasticsearch.search.aggregations.bucket.adjacency,  has 2,  private references [org.apache.lucene.index, org.apache.lucene.search],
[WARNING] Bundle org.opencastproject:opencast-elasticsearch-impl:bundle:11-SNAPSHOT : Export org.elasticsearch.search.aggregations.bucket.composite,  has 1,  private references [org.apache.lucene.index],
[WARNING] Bundle org.opencastproject:opencast-elasticsearch-impl:bundle:11-SNAPSHOT : Export org.elasticsearch.search.aggregations.bucket.filter,  has 2,  private references [org.apache.lucene.index, org.apache.lucene.search],
[WARNING] Bundle org.opencastproject:opencast-elasticsearch-impl:bundle:11-SNAPSHOT : Export org.elasticsearch.search.aggregations.bucket.geogrid,  has 2,  private references [org.apache.lucene.index, org.apache.lucene.search],
[WARNING] Bundle org.opencastproject:opencast-elasticsearch-impl:bundle:11-SNAPSHOT : Export org.elasticsearch.search.aggregations.bucket.global,  has 1,  private references [org.apache.lucene.index],
[WARNING] Bundle org.opencastproject:opencast-elasticsearch-impl:bundle:11-SNAPSHOT : Export org.elasticsearch.search.aggregations.bucket.histogram,  has 2,  private references [org.apache.lucene.index, org.apache.lucene.search],
[WARNING] Bundle org.opencastproject:opencast-elasticsearch-impl:bundle:11-SNAPSHOT : Export org.elasticsearch.search.aggregations.bucket.missing,  has 1,  private references [org.apache.lucene.index],
[WARNING] Bundle org.opencastproject:opencast-elasticsearch-impl:bundle:11-SNAPSHOT : Export org.elasticsearch.search.aggregations.bucket.nested,  has 1,  private references [org.apache.lucene.index],
[WARNING] Bundle org.opencastproject:opencast-elasticsearch-impl:bundle:11-SNAPSHOT : Export org.elasticsearch.search.aggregations.bucket.range,  has 3,  private references [org.apache.lucene.index, org.apache.lucene.search, org.apache.lucene.util],
[WARNING] Bundle org.opencastproject:opencast-elasticsearch-impl:bundle:11-SNAPSHOT : Export org.elasticsearch.search.aggregations.bucket.sampler,  has 2,  private references [org.apache.lucene.index, org.apache.lucene.search],
[WARNING] Bundle org.opencastproject:opencast-elasticsearch-impl:bundle:11-SNAPSHOT : Export org.elasticsearch.search.aggregations.bucket.terms,  has 4,  private references [org.apache.lucene.index, org.apache.lucene.search
, org.apache.lucene.util, org.apache.lucene.util.automaton],
[WARNING] Bundle org.opencastproject:opencast-elasticsearch-impl:bundle:11-SNAPSHOT : Export org.elasticsearch.search.aggregations.metrics,  has 2,  private references [org.apache.lucene.index, org.apache.lucene.search],
[WARNING] Bundle org.opencastproject:opencast-elasticsearch-impl:bundle:11-SNAPSHOT : Export org.elasticsearch.search.aggregations.support,  has 3,  private references [org.apache.lucene.index, org.apache.lucene.search, org.apache.lucene.util],
[WARNING] Bundle org.opencastproject:opencast-elasticsearch-impl:bundle:11-SNAPSHOT : Export org.elasticsearch.search.aggregations.support.values,  has 1,  private references [org.apache.lucene.search],
[WARNING] Bundle org.opencastproject:opencast-elasticsearch-impl:bundle:11-SNAPSHOT : Export org.elasticsearch.search.collapse,  has 2,  private references [org.apache.lucene.search, org.apache.lucene.search.grouping],
[WARNING] Bundle org.opencastproject:opencast-elasticsearch-impl:bundle:11-SNAPSHOT : Export org.elasticsearch.search.dfs,  has 3,  private references [com.carrotsearch.hppc, org.apache.lucene.index, org.apache.lucene.searc
h],
[WARNING] Bundle org.opencastproject:opencast-elasticsearch-impl:bundle:11-SNAPSHOT : Export org.elasticsearch.search.fetch,  has 3,  private references [com.carrotsearch.hppc, org.apache.lucene.index, org.apache.lucene.search],
[WARNING] Bundle org.opencastproject:opencast-elasticsearch-impl:bundle:11-SNAPSHOT : Export org.elasticsearch.search.fetch.subphase,  has 2,  private references [org.apache.lucene.index, org.apache.lucene.search],
[WARNING] Bundle org.opencastproject:opencast-elasticsearch-impl:bundle:11-SNAPSHOT : Export org.elasticsearch.search.fetch.subphase.highlight,  has 6,  private references [org.apache.lucene.analysis, org.apache.lucene.document, org.apache.lucene.index, org.apache.lucene.search, org.apache.lucene.search.uhighlight, org.apache.lucene.search.vectorhighlight],
[WARNING] Bundle org.opencastproject:opencast-elasticsearch-impl:bundle:11-SNAPSHOT : Export org.elasticsearch.search.internal,  has 3,  private references [org.apache.lucene.index, org.apache.lucene.search, org.apache.lucene.search.similarities],
[WARNING] Bundle org.opencastproject:opencast-elasticsearch-impl:bundle:11-SNAPSHOT : Export org.elasticsearch.search.lookup,  has 1,  private references [org.apache.lucene.index],
[WARNING] Bundle org.opencastproject:opencast-elasticsearch-impl:bundle:11-SNAPSHOT : Export org.elasticsearch.search.profile.aggregation,  has 2,  private references [org.apache.lucene.index, org.apache.lucene.search],
[WARNING] Bundle org.opencastproject:opencast-elasticsearch-impl:bundle:11-SNAPSHOT : Export org.elasticsearch.search.profile.query,  has 2,  private references [org.apache.lucene.index, org.apache.lucene.search],
[WARNING] Bundle org.opencastproject:opencast-elasticsearch-impl:bundle:11-SNAPSHOT : Export org.elasticsearch.search.query,  has 2,  private references [org.apache.lucene.index, org.apache.lucene.search],
[WARNING] Bundle org.opencastproject:opencast-elasticsearch-impl:bundle:11-SNAPSHOT : Export org.elasticsearch.search.rescore,  has 1,  private references [org.apache.lucene.search],
[WARNING] Bundle org.opencastproject:opencast-elasticsearch-impl:bundle:11-SNAPSHOT : Export org.elasticsearch.search.searchafter,  has 1,  private references [org.apache.lucene.search],
[WARNING] Bundle org.opencastproject:opencast-elasticsearch-impl:bundle:11-SNAPSHOT : Export org.elasticsearch.search.slice,  has 1,  private references [org.apache.lucene.search],
[WARNING] Bundle org.opencastproject:opencast-elasticsearch-impl:bundle:11-SNAPSHOT : Export org.elasticsearch.search.sort,  has 2,  private references [org.apache.lucene.index, org.apache.lucene.search],
[WARNING] Bundle org.opencastproject:opencast-elasticsearch-impl:bundle:11-SNAPSHOT : Export org.elasticsearch.search.suggest,  has 3,  private references [org.apache.lucene.analysis, org.apache.lucene.search, org.apache.lu
cene.util],
[WARNING] Bundle org.opencastproject:opencast-elasticsearch-impl:bundle:11-SNAPSHOT : Export org.elasticsearch.search.suggest.completion,  has 2,  private references [org.apache.lucene.search, org.apache.lucene.util],
[WARNING] Bundle org.opencastproject:opencast-elasticsearch-impl:bundle:11-SNAPSHOT : Export org.elasticsearch.search.suggest.phrase,  has 6,  private references [org.apache.lucene.analysis, org.apache.lucene.analysis.tokenattributes, org.apache.lucene.codecs, org.apache.lucene.index, org.apache.lucene.search, org.apache.lucene.util],
[WARNING] Bundle org.opencastproject:opencast-elasticsearch-impl:bundle:11-SNAPSHOT : Export org.elasticsearch.search.suggest.term,  has 2,  private references [org.apache.lucene.search, org.apache.lucene.util],
[WARNING] Bundle org.opencastproject:opencast-elasticsearch-impl:bundle:11-SNAPSHOT : Classes found in the wrong directory: {META-INF/versions/11/org/elasticsearch/monitor/jvm/JvmPid.class=org.elasticsearch.monitor.jvm.JvmPid}
[WARNING] Bundle org.opencastproject:opencast-elasticsearch-impl:bundle:11-SNAPSHOT : Classes found in the wrong directory: {META-INF/versions/11/org/elasticsearch/core/internal/io/Streams.class=org.elasticsearch.core.internal.io.Streams, META-INF/versions/11/org/elasticsearch/common/collect/Set.class=org.elasticsearch.common.collect.Set, META-INF/versions/11/org/elasticsearch/common/collect/List.class=org.elasticsearch.common.collect.List, META-INF/versions/11/org/elasticsearch/common/collect/Map.class=org.elasticsearch.common.collect.Map}
[WARNING] Bundle org.opencastproject:opencast-elasticsearch-impl:bundle:11-SNAPSHOT : Classes found in the wrong directory: {META-INF/versions/9/org/apache/lucene/search/PointRangeQuery$1.class=org.apache.lucene.search.PointRangeQuery$1, META-INF/versions/9/org/apache/lucene/util/StringHelper.class=org.apache.lucene.util.StringHelper, META-INF/versions/9/org/apache/lucene/store/DataInput.class=org.apache.lucene.store.DataInput, META-INF/versions/9/org/apache/lucene/util/bkd/BKDRadixSelector$2$1.class=org.apache.lucene.util.bkd.BKDRadixSelector$2$1, META-INF/versions/9/org/apache/lucene/util/BytesRef.class=org.apache.lucene.util.BytesRef, META-INF/versions/9/org/apache/lucene/document/BinaryPoint$2.class=org.apache.lucene.document.BinaryPoint$2, META-INF/versions/9/org/apache/lucene/index/CodecReader.class=org.apache.lucene.index.CodecReader, META-INF/versions/9/org/apache/lucene/codecs/blocktree/SegmentTermsEnumFrame.class=org.apache.lucene.codecs.blocktree.SegmentTermsEnumFrame, META-INF/versions/9/org/apache/lucene/util/automaton/Automaton.class=org.apache.lucene.util.automaton.Automaton, META-INF/versions/9/org/apache/lucene/util/bkd/MutablePointsReaderUtils$2.class=org.apache.lucene.util.bkd.MutablePointsReaderUtils$2, META-INF/versions/9/org/apache/lucene/document/LongRange.class=org.apache.lucene.document.LongRange, META-INF/versions/9/org/apache/lucene/codecs/blocktree/BlockTreeTermsWriter$TermsWriter.class=org.apache.lucene.codecs.blocktree.BlockTreeTermsWriter$TermsWriter, META-INF/versions/9/org/apache/lucene/document/LatLonPointDistanceQuery$1.class=org.apache.lucene.document.LatLonPointDistanceQuery$1, META-INF/versions/9/org/apache/lucene/document/RangeFieldQuery$QueryType$2.class=org.apache.lucene.document.RangeFieldQuery$QueryType$2, META-INF/versions/9/org/apache/lucene/codecs/compressing/FieldsIndexReader.class=org.apache.lucene.codecs.compressing.FieldsIndexReader, META-INF/versions/9/org/apache/lucene/util/bkd/MutablePointsReaderUtils$3$1.class=org.apache.lucene.util.bkd.MutablePointsReaderUtils$3$1, META-INF/versions/9/org/apache/lucene/util/bkd/HeapPointWriter.class=org.apache.lucene.util.bkd.HeapPointWriter, META-INF/versions/9/org/apache/lucene/util/bkd/MutablePointsReaderUtils$1$1.class=org.apache.lucene.util.bkd.MutablePointsReaderUtils$1$1, META-INF/versions/9/org/apache/lucene/document/IntRange.class=org.apache.lucene.document.IntRange, META-INF/versions/9/org/apache/lucene/index/CheckIndex$VerifyPointsVisitor.class=org.apache.lucene.index.CheckIndex$VerifyPointsVisitor, META-INF/versions/9/org/apache/lucene/document/LatLonPointDistanceFeatureQuery$DistanceScorer$2.class=org.apache.lucene.document.LatLonPointDistanceFeatureQuery$DistanceScorer$2, META-INF/versions/9/org/apache/lucene/util/bkd/BKDWriter$BKDMergeQueue.class=org.apache.lucene.util.bkd.BKDWriter$BKDMergeQueue, META-INF/versions/9/org/apache/lucene/util/compr
ess/LZ4.class=org.apache.lucene.util.compress.LZ4, META-INF/versions/9/org/apache/lucene/util/IntsRef.class=org.apache.lucene.util.IntsRef, META-INF/versions/9/org/apache/lucene/index/PointValues.class=org.apache.lucene.index.PointValues, META-INF/versions/9/org/apache/lucene/util/bkd/BKDWriter$OneDimensionBKDWriter.class=org.apache.lucene.util.bkd.BKDWriter$OneDimensionBKDWriter, META-INF/versions/9/org/apache/lucene/util/LongsRef.class=org.apache.lucene.util.LongsRef, META-INF/versions/9/org/apache/lucene/util/automaton/Automaton$Builder.class=org.apache.lucene.util.automaton.Automaton$Builder, META-INF/versions/9/org/apache/lucene/util/bkd/BKDRadixSelector$1$1.class=org.apache.lucene.util.bkd.BKDRadixSelector$1$1, META-INF/versions/9/org/apache/lucene/analysis/tokenattributes/CharTermAttributeImpl.class=org.apache.lucene.analysis.tokenattributes.CharTermAttributeImpl, META-INF/versions/9/org/apache/lucene/document/LatLonShapeBoundingBoxQuery$EncodedRectangle.class=org.apache.lucene.document.LatLonShapeBoundingBoxQuery$EncodedRectangle, META-INF/versions/9/org/apache/lucene/document/RangeFieldQuery$QueryType$1.class=org.apache.lucene.document.RangeFieldQuery$QueryType$1, META-INF/versions/9/org/apache/lucene/util/bkd/BKDRadixSelector.class=org.apache.lucene.util.bkd.BKDRadixSelector, META-INF/versions/9/org/apache/lucene/index/MergeReaderWrapper.class=org.apache.lucene.index.MergeReaderWrapper, META-INF/versions/9/org/apache/lucene/util/CharsRef.class=org.apache.lucene.util.CharsRef, META-INF/versions/9/org/apache/lucene/document/DoubleRange.class=org.apache.lucene.document.DoubleRange, META-INF/versions/9/org/apache/lucene/document/FloatRange.class=org.apache.lucene.document.FloatRange, META-INF/versions/9/org/apache/lucene/util/bkd/BKDReader.class=org.apache.lucene.util.bkd.BKDReader, META-INF/versions/9/org/apache/lucene/document/LatLonPointInPolygonQuery$1.class=org.apache.lucene.document.LatLonPointInPolygonQuery$1, META-INF/versions/9/org/apache/lucene/util/CharsRe
f$UTF16SortedAsUTF8Comparator.class=org.apache.lucene.util.CharsRef$UTF16SortedAsUTF8Comparator, META-INF/versions/9/org/apache/lucene/util/compress/LZ4$FastCompressionHashTable.class=org.apache.lucene.util.compress.LZ4$FastCompressionHashTable, META-INF/versions/9/org/apache/lucene/util/compress/LZ4$HighCompressionHashTable.class=org.apache.lucene.util.compress.LZ4$HighCompressionHashTable, META-INF/versions/9/org/apache/lucene/search/comparators/NumericComparator$NumericLeafComparator$1.class=org.apache.lucene.search.comparators.NumericComparator$NumericLeafComparator$1, META-INF/versions/9/org/apache/lucene/search/BooleanScorer$TailPriorityQueue.class=org.apache.lucene.search.BooleanScorer$TailPriorityQueue, META-INF/versions/9/org/apache/lucene/document/LongDistanceFeatureQuery$DistanceScorer$2.class=org.apache.lucene.document.LongDistanceFeatureQuery$DistanceScorer$2, META-INF/versions/9/org/apache/lucene/search/PointInSetQuery$SinglePointVisitor.class=org.apache.lucene.search.PointInSetQuery$SinglePointVisitor, META-INF/versions/9/org/apache/lucene/search/TopFieldCollector.class=org.apache.lucene.search.TopFieldCollector, META-INF/versions/9/org/apache/lucene/util/bkd/BKDWriter.class=org.apache.lucene.util.bkd.BKDWriter, META-INF/versions/9/org/apache/lucene/util/BytesRefArray.class=org.apache.lucene.util.BytesRefArray, META-INF/versions/9/org/apache/lucene/index/BitsSlice.class=org.apache.lucene.index.BitsSlice, META-INF/versions/9/org/apache/lucene/document/RangeFieldQuery$QueryType$3.class=org.apache.lucene.document.RangeField
Query$QueryType$3}
[WARNING] Bundle org.opencastproject:opencast-elasticsearch-impl:bundle:11-SNAPSHOT : Classes found in the wrong directory: {META-INF/versions/9/org/apache/logging/log4j/core/util/SystemClock.class=org.apache.logging.log4j.core.util.SystemClock}
```

**Comment by KatrinIhler** [comment]
> Hi Katrin, I'm reviewing this PR, from what are you saying, is needed to try with #2742 ? It could not be better to merge the two pr into one? If that is, I tried to merge this pr into #2742, and I found some merge conflicts.

No, you don't! That PR (along with two others) are already included here, so you just need all commits from this PR. :)

**Comment by KatrinIhler** [comment]
> is normal to get those warnings when building?

Eh, I don't know. That doesn't quite look right...

**Comment by gregorydlogan** [comment]
> > is normal to get those warnings when building?
> 
> Eh, I don't know. That doesn't quite look right...

These are present in unmodified 9.x. Whether they're supposed to be there or not...

**Comment by mliradelc** [comment]
After our meeting of today, we know that:
- The elastic search warnings came from 9.X so in this case is not a problem.
- The bug #2831 for 10.X seems to be fixed, ~but we encountered a very strange error when you publish.~
I will try to isolate the publishing error, maybe our publishing workflows need some changes.


Update: We confirm that this PR fixes #2831, this PR is **Needed for OC 10.x distributed installation**

**Pull request merged**
