### PR TITLE
Paella 7: Use the localstorage to store the user preferences and upgrades Paella core to 1.43

### PR DESCRIPTION
**Pull request by miesgre**
This PR updates the paella to last version and updates the config file to save the user preferences in the localstorage instead of cookies.
Fixes a "HTTP 431 header too large" bug when user's preferences are too large.
See polimediaupv/paella-core#322

### Your pull request should…

* [x] have a concise title
* [ ] [close an accompanying issue](https://help.github.com/en/articles/closing-issues-using-keywords) if one exists
* [ ] [be against the correct branch](https://docs.opencast.org/develop/developer/development-process#acceptance-criteria-for-patches-in-different-versions)
* [ ] include migration scripts and documentation, if appropriate
* [x] pass automated tests
* [x] have a clean commit history
* [x] [have proper commit messages (title and body) for all commits](https://medium.com/@steveamaza/e028865e5791)

### CODE REVIEW

**Comment by mliradelc** [comment]
@miesgre how I can test this?, also, because this solves a bug, should be on `r/13.x`?

**Comment by miesgre** [comment]
> @miesgre how I can test this?, also, because this solves a bug, should be on `r/13.x`?

You can check that preferences are now in localstorage instead of cookies.
Maybe @karendolan can review it and test with large user preferences in her installation.


About r/13.x, This PR requiere to update paella-core version to 1.43, that's why I sent it to develop

Oc version | paella version
------|-------
r/13.x | 1.25.0
r/14.x | 1.39.2
develop | 1.42.0

**Comment by mliradelc** [comment]
Now you said it, It seems dependabot is not making PR updates to paella. I haven't seen one for core in a while.

**Comment by mliradelc** [comment]
@miesgre Yesterday I spoke with Lars and I forgot completely, we decided that the only branch with automatic updates will go to the develop branch.
The other branches need paella to be manually updated.

Should I take the json and the config files to the other versions so you can rollback this bugfix and the other to r/13.x?

**Comment by miesgre** [comment]
> @miesgre Yesterday I spoke with Lars and I forgot completely, we decided that the only branch with automatic updates will go to the develop branch. The other branches need paella to be manually updated.
> 
> Should I take the json and the config files to the other versions so you can rollback this bugfix and the other to r/13.x?

If there is no problem in changing the version of paella and modifying the config.json file, I can rebase to r/13.x if you want.

**Comment by mliradelc** [comment]
That is a good idea, please rebase r/13.× and I will try it and merge it today

**Comment by miesgre** [comment]
> That is a good idea, please rebase r/13.× and I will try it and merge it today

Done. Test it!

**Review by mliradelc — APPROVED** [review]
Works for me, shows Paella is using the local storage instead.

**Comment by KatrinIhler** [comment]
@mliradelc Did you test other player behavior as well? If I understand this correctly, this version update will contain more than just this bugfix, so we need to ensure it's safe before putting it into a minor Opencast version.

**Comment by mliradelc** [comment]
Yes, this version also upgrades the core of paella, that is already in the `develop` branch. From what I tested is working well. I'm waiting for @karendolan comments over the localstorage.

**Comment by karendolan** [comment]
HI @mliradelc, just saw this! For the intermediate solution at our site, we have increased our allowed header sizes on the server so we have not yet adopted saving preferences in storage, but will in the next couple weeks. For students getting the 
"header to large" error, we ask them to clear their cookies, try an anonymous browser, or different browser. 

An example of the  issue is that my own Paella preference cookie for our site is now 2102 bytes big, and that is a lot to send back to Opencast on each request along with our other session related cookies. Sites like github commonly use browser storage for preferences, instead of the cookie. If you look in your browser inspector storage/application tab right now, you will see the refs.

**Pull request merged**
