### PR TITLE
MH-13564, Media Module Configuration

### PR DESCRIPTION
**Pull request by lkiesow**
This patch moves the media module configuration from the organization
configuration to the user interface configuration service to provide a
better structure for those components.

Instead of using JSON directly, I opted for using YAML for the
configuration file since that allows us to add proper comments to the
configuration file.

### CODE REVIEW

**Comment by staubesv** [comment]
@lkiesow The upgrade guide should contain information for Adopters that some configuration keys need to be moved to other locations.

**Comment by mliradelc** [comment]
Got it! I will look on that.

PS: I will port the theodul player config to another place (Like this) to have their settings in a separate file.  But it will be in other PR

**Comment by lkiesow** [comment]
@mliradelc, you should now be able to assign pull requests. If you ever want to grab a pull request, feel free to just assign yourself. That indicates to others that you will take care of the review and is already visible on the overview page. Here, I just went ahead and assigned you ;-)

**Comment by mliradelc** [comment]
I Build it, and passed all the tests, no problems so far.

Also I use as a base for my next PR.

If there are no more topics about this PR I will merge it ~~on monday~~ after decide if another PR that is based on this should be merged to this or merge them separately.

**Comment by lkiesow** [comment]
> …after decide if another PR that is based on this should be merged to this or merge them separately.

Please treat it separately. One change, one pull request makes it way easier to find out what has been done later. And I assume the other patch you are talking about is the one for the player which is another module entirely.

**Comment by mliradelc** [comment]
Ok, I will merge this.

**Review by mliradelc — COMMENTED** [review]
All good! Tested succesfully

**Comment by lkiesow** [comment]
Thanks for the review

**Pull request merged**
