### PR TITLE
add chevron to <details> in docs

### PR DESCRIPTION
**Pull request by ziegenberg**
This adds a little up/down chevron using the glyphicons font, making it easier to spot and also shows the current status: folded/unfolded.

### Your pull request should…

* [x] have a concise title
* [x] ~~[close an accompanying issue](https://help.github.com/en/articles/closing-issues-using-keywords) if one exists~~
* [x] [be against the correct branch](https://docs.opencast.org/develop/developer/development-process#acceptance-criteria-for-patches-in-different-versions)
* [x] ~~include migration scripts and documentation, if appropriate~~
* [x] pass automated tests
* [x] have a clean commit history
* [ ] [have proper commit messages (title and body) for all commits](https://medium.com/@steveamaza/e028865e5791)

### CODE REVIEW

**Comment by KatrinIhler** [comment]
Could you show us a quick screenshot with the difference? :)

**Comment by ziegenberg** [comment]
Two screenshots in folded/unfolded state:

Screenshot from 2023-10-27 18-30-10
Screenshot from 2023-10-27 18-30-16


And what it looked like before:

Screenshot from 2023-10-27 11-24-42

**Review by KatrinIhler — APPROVED** [review]
Looks nice :)

**Comment by ziegenberg** [comment]
> Looks nice :)

Thx! ☺️

**Comment by KatrinIhler** [comment]
Don't we have to talk about this in the Technical Meeting yet? Or doesn't that rule apply to docs changes? I'm not sure rn.

**Comment by ziegenberg** [comment]
That happened yesterday already :)

**Comment by KatrinIhler** [comment]
> That happened yesterday already :)

Oh damn, I completely forgot that not everyone had a holiday on Tuesday :see_no_evil:

**Pull request merged**
