### PR TITLE
MH-13509, Upgrade Admin Interface Libraries (Including AngularJS)

### PR DESCRIPTION
**Pull request by lkiesow**
One step in the direction of getting AngularJS updated.

*Work sponsored by SWITCH*

### CODE REVIEW

**Comment by lkiesow** [comment]
Added update to AngularJS 1.7.8 since the update from 1.6.10 seems to work without any required changes.

**Comment by lkiesow** [comment]
I guess that's it for now. :)

**Comment by staubesv** [comment]
@lkiesow Note that NOTICES mentions the versions of those libraries and should be adapted, too

**Comment by lkiesow** [comment]
done.

**Comment by lkiesow** [comment]
Fixed merge conflicts

**Comment by mliradelc** [comment]
Reviewing this right now

**Comment by mliradelc** [comment]
I Installed opencast from this PR, build it, passed all the tests and I created some events. No problems

**Comment by staubesv** [comment]
@mliradelc Thanks! As far as I know, you haven't yet signed the Apereo forms, have you? If not I can take the job to hit the merge button if you officially approve the pull request.

**Comment by mliradelc** [comment]
> @mliradelc Thanks! As far as I know, you haven't yet signed the Apereo forms, have you? If not I can take the job to hit the merge button if you officially approve the pull request.

No @staubesv I haven't yet, also I don't have the rights to merge yet.

Please merge for me instead 😄

**Comment by staubesv** [comment]
Done.

**Comment by lkiesow** [comment]
Thanks for the review and the merge

**Pull request merged**
