### PR TITLE
Subtitles as tracks in transcription services

### PR DESCRIPTION
**Pull request by Arnei**
*This PR aims at contributing to the implementation of #4407, but touches on just one of the aspects to realize #4407's vision. It should therefore likely not be merged alone, but alongside other PRs.*

This changes the "Attach" WOHs for our Speech-to-Text integrations. The subtype of the target flavor can now be set freely, default output format is vtt, default output type is track. 

Due to lack of access to the various external Speech-To-Text services this PR is not particularly well tested. It would be great if someone with access to one ore more services could test those!

### CODE REVIEW

**Comment by gregorydlogan** [comment]
@karendolan @rute-santos Can you test Watson?
@lkiesow Can you test Amberscript?  Or know someone who is using Amberscript?
@wsmirnow Are ~you guys~ ETH using Azure?

Now we just need someone who uses the Google side of things.

**Comment by wsmirnow** [comment]
The Azure side was completly rewritten and will be pushed upstreem soon. I would also update the code to be compatible with #4407.

**Comment by mliradelc** [comment]
Unfortunately I can't review:

- Amberscript
- Azure
- Watson
- Google

But I reviewed #e82dc6f and #f4d9acd. Would be possible to split this PR?

**Review by mliradelc — APPROVED** [review]
From the general STT WoH is all good. Tested and working.

**Comment by mliradelc** [comment]
This PR has been opened since April and there are no remarks regarding the transcription services. I will suppose that the transcription services work properly.

**Comment by lkiesow** [comment]
> This PR has been opened since April and there are no remarks regarding the transcription services. I will suppose that the transcription services work properly.

Unfortunately, it does not. This has been a valid configuration before and is still valid according to the documentation:

```yaml
  - id: amberscript-attach-transcription                                                                                 
    fail-on-error: true                                                                                                  
    exception-handler-workflow: partial-error                                                                            
    description: Attach captions/transcription                                                                           
    configurations:                                                                                                      
      - transcription-job-id: ${transcriptionJobId}                                                                      
      - target-caption-format: vtt                                                                                       
      - target-tag: engage-download 
```

The `target-flavor` should be derived from `target-caption-format`.

But this now fails with:

```
2023-09-01 12:50:30,122 | ERROR | (WorkflowOperationWorker:140) - Workflow operation 'operation:'amberscript-attach-transcription, state:'FAILED'' failed
org.opencastproject.workflow.api.WorkflowOperationException: Configuration key 'target-flavor' must be set
        at org.opencastproject.workflow.api.AbstractWorkflowOperationHandler.getTagsAndFlavors(AbstractWorkflowOperationHandler.java:489) ~[?:?]
        at org.opencastproject.transcription.workflowoperation.AmberscriptAttachTranscriptionOperationHandler.start(AmberscriptAttachTranscriptionOperationHandler.java:95) ~[?:?]
        at org.opencastproject.workflow.impl.WorkflowOperationWorker.start(WorkflowOperationWorker.java:212) ~[?:?]
        at org.opencastproject.workflow.impl.WorkflowOperationWorker.execute(WorkflowOperationWorker.java:117) ~[?:?]
        at org.opencastproject.workflow.impl.WorkflowServiceImpl.runWorkflowOperation(WorkflowServiceImpl.java:723) ~[?:?]
        at org.opencastproject.workflow.impl.WorkflowServiceImpl.process(WorkflowServiceImpl.java:1741) ~[?:?]
        at org.opencastproject.workflow.impl.WorkflowServiceImpl$JobRunner.call(WorkflowServiceImpl.java:2102) ~[?:?]
        at org.opencastproject.workflow.impl.WorkflowServiceImpl$JobRunner.call(WorkflowServiceImpl.java:2068) ~[?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
        at java.lang.Thread.run(Thread.java:829) ~[?:?]
```

**Pull request merged**
