### PR TITLE
Enforce Maven Dependency Checks on some more modules

### PR DESCRIPTION
**Pull request by SijmenHuizenga**
Fixed problems reported by the maven dependency plugin in the following modules:
* publication-service-youtube-v3
* admin-ui
* search

Tested the changes using the method described by @lkiesow in the comments below.

* [x] have a concise title
* [x] this pr works towards closing #1893 
* [x] be against the correct branch (features can only go into develop)
* [x] include migration scripts and documentation, if appropriate
* [x] pass automated testing
* [x] have a clean commit history
* [x] have proper commit messages (title and body) for all commits
* [x] have appropriate tags applied

### CODE REVIEW

**Comment by lkiesow** [comment]
>  Test! (I have to figure out how to do that)

For a quick test, the following should be sufficient:

```bash
# build Opencast (-Pdev will give you a distribution which is slightly easier to test – no tarballs to unpack, …)
% mvn clean install -Pdev
% cd docs/scripts/devel-dependency-containers/
# the next command will give you all necessary runtime dependencies (search index & message broker)
# alternatively, use  docker-compose up -d  if you prefer Docker
% podman-compose up -d
% cd ../../../build/opencast-dist-develop-9-SNAPSHOT/
% ./bin/start-opencast
# wait a few seconds until the logs have calmed down
# Go to http://localhost:8080
# Use “add event” to upload a video
# If it processes successfully, everything should be fine
```

We can run a few more tests as part of the review if necessary

**Comment by SijmenHuizenga** [comment]
Thanks for the instructions @lkiesow! The `publication-service-youtube-v3` is finished. Compilation takes ages on my laptop, so testing and going back to fix problems is quite slow. I will do the `admin-ui` module next.

**Comment by lkiesow** [comment]
> Compilation takes ages on my laptop, so testing and going back to fix problems is quite slow.

Then here is another tip: If you have built it already once and just modified one module, you can just compile that module ans assembly the distribution again. Basically:

```
cd modules/admin-ui
mvn clean install -Pdev
cd ../../assemblies/
mvn clean install -Pdev
```

If you don't need the unit tests, you can also speed things up by adding `-DskipTests` to your `mvn` command.
There are a number of variation on this which work better or worse in different scenarios but this is the basic one and already speeds things up quite a bit ;-)

Edit: Though it seems like the unit tests on the `admin-ui` module may now fail due to removed dependencies.
Not sure which specifically but my guess would be that the tests use an internal h2 database for testing.

**Comment by SijmenHuizenga** [comment]
@lkiesow Thanks a lot :heart: This is some next-level maven configuration ;) Good thing we have travis to point out these failing tests, trying to fix them atm

**Comment by lkiesow** [comment]
Patch looks hood → merged.
Thanks again for the help.

**Pull request merged**
