### PR TITLE
Temporarily Ignore Failing Test

### PR DESCRIPTION
**Pull request by lkiesow**
This patch is a temporary fix for #1111, preventing CI failures.

### Your pull request should…

* [ ] have a concise title
* [ ] [close an accompanying issue](https://help.github.com/en/articles/closing-issues-using-keywords) if one exists
* [ ] be against the correct branch (features can only go into develop)
* [ ] include migration scripts and documentation, if appropriate
* [ ] pass automated testing
* [ ] have a clean commit history
* [ ] have proper commit messages (title and body) for all commits
* [ ] have appropriate tags applied

### CODE REVIEW

**Comment by gregorydlogan** [comment]
Is this still an issue?  I'm not seeing a ton of errors on this anymore...

**Comment by lkiesow** [comment]
I have seen this once or twice since though not that often. So, yes, it's still an issue.
Even if it is not popping up that often right now it can again at any time.
So, I'm very much in favor of merging this.

**Comment by lkiesow** [comment]
@gregorydlogan, and here we go again. [New failures today](https://travis-ci.org/opencast/opencast/jobs/616612215?utm_medium=notification&utm_source=email). Inconsistently broken things don't get better just because they don't show up once.

**Comment by gregorydlogan** [comment]
Reminder to @JamesUoM that this has been disabled.

**Pull request merged**
