### PR TITLE
Missing setting track logical name when serverless HLS in process-smil

### PR DESCRIPTION
**Pull request by rute-santos**
### Your pull request should…

* [ ] have a concise title
* [ ] [close an accompanying issue](https://help.github.com/en/articles/closing-issues-using-keywords) if one exists
* [ ] [be against the correct branch](https://docs.opencast.org/develop/developer/development-process#acceptance-criteria-for-patches-in-different-versions)
* [ ] include migration scripts and documentation, if appropriate
* [ ] pass automated tests
* [ ] have a clean commit history
* [ ] [have proper commit messages (title and body) for all commits](https://medium.com/@steveamaza/e028865e5791)

### CODE REVIEW

**Comment by rute-santos** [comment]
This was in our code base but missing from the community PR.

**Comment by mtneug** [comment]
What is happening when the logical name is unset? We already package for HLS using `process-smil`.

**Comment by rute-santos** [comment]
Hi @mtneug ,
I don't recall exactly because it's been a few months, but I believe it would cause problems if the recording was re-used later and needed sanitize-adaptive to re-calculate the references in the m3u8 files.

**Comment by mtneug** [comment]
mmh strange. I never noticed problems when running `sanitize-adaptive`. But probably good to have that info in there.

**Comment by rute-santos** [comment]
Hmm. Maybe you use multiencode and not process-smil? Multiencode had this missing piece...

**Comment by gregorydlogan** [comment]
@mtneug is this ready to go for upstream? Looks like you've merged it locally...

**Comment by mtneug** [comment]
I did not yet test with `process-smil`. As @rute-santos said, we package for HLS with `multiencode` and not `process-smil` so we never encountered the issue.

**Pull request merged**
