### PR TITLE
LTI Tool Updates

### PR DESCRIPTION
**Pull request by lkiesow**
This patch updates some of the LTI tool dependencies and lifts
restrictions previously set on updates.

### Your pull request should…

* [x] have a concise title
* [x] [close an accompanying issue](https://help.github.com/en/articles/closing-issues-using-keywords) if one exists
* [x] be against the correct branch (features can only go into develop)
* [x] include migration scripts and documentation, if appropriate
* [x] pass automated tests
* [x] have a clean commit history
* [x] [have proper commit messages (title and body) for all commits](https://medium.com/@steveamaza/e028865e5791)

### CODE REVIEW

**Comment by lkiesow** [comment]
Fixed merge conflicts

**Review by Arnei — APPROVED** [review]

**Comment by lkiesow** [comment]
Fixed merge conflicts

**Review by Arnei — APPROVED** [review]

**Comment by lkiesow** [comment]
@Arnei, anything holding a merge of this back?

**Comment by Arnei** [comment]
Now that you mention it, I don't think so.

**Pull request merged**
