### PR TITLE
MH-13477, Faster Asset Manager Property Access

### PR DESCRIPTION
**Pull request by lkiesow**
This patch uses the new native asset manager property access for
workflow property retrieval.

*Work sponsored by SWITCH*

### CODE REVIEW

**Comment by smarquard** [comment]
Does this improve the underlying mysql query that gets generated?

**Comment by lkiesow** [comment]
Yes. The current one still joins the snapshot and property tables

**Comment by smarquard** [comment]
This is a performance optimization rather than feature, so perhaps redirect to 7.x ?

**Comment by lkiesow** [comment]
Moved to `r/7.x`.

Note that I'm on vacation for the next two weeks.

I specifically allowed edits from maintainers. Hence, feel free to modify anything that needs modification if you do not want to wait or contact someone else at [ELAN e.V.](mailto:opencast-support@elan-ev.de) to fix problems

**Comment by smarquard** [comment]
We have merged this into our (modified) 6.x and it is running in production. If no issues show up in the next day or two, I will merge this.

**Pull request merged**
