### PR TITLE
MH-12323: Add `package-lock.json`

### PR DESCRIPTION
**Pull request by JulianKniephoff**
[As discussed on list](https://groups.google.com/a/opencast.org/forum/#!topic/dev/jCqzhkIUCZU), here is a PR adding `package-lock.json`.

This implements [MH-12323](https://opencast.jira.com/browse/MH-12323) which could be understood as a feature, but it also fixes [MH-12865](https://opencast.jira.com/browse/MH-12865) making this kind of a bug fix; so I hope it's okay for me to file this against 3.x, but I can change that of course if the review gods decide that. :)

One important thing to note here is: Some care must be taken into forward merging this pull request. For example: #146, merged into 5.x, introduced a few updates to some npm dependencies. This will change `package-lock.json` on build, which is fine (necessary even), but these changes then need to be committed as well.

### CODE REVIEW

**Comment by gregorydlogan** [comment]
Is this safe to merge into 4/4.x as is?  I'll do the full merge from 3.x, to 4.x, to 5.x, but it's also a new file in 4.x.  I'm assuming the versions specified in the lock are correct for 4.x at least?

**Comment by lkiesow** [comment]
While merging this, we would at least need to check.
If I would do the merge, I would simply remove it for each version and rebuild the admin module to check if there are any changes.

**Comment by gregorydlogan** [comment]
As discussed on IRC, @lkiesow will merge this forward and do the appropriate checks.

**Comment by JulianKniephoff** [comment]
In my own tests, building the admin UI on 4.x without a `package-lock.json` resulted in the same one committed here. 5.x produced a different one, and there were also differences between building 5.x without a `package-lock.json` and building it with this one. You see, npm **can** update the `package-lock.json` if necessary, but I think it tries to minimize the changes, which is sensible, IMO. So it should not actually be necessary to do a clean rebuild for every branch.

**Pull request merged**
