### PR TITLE
MH-12937: Correctly place admin UI test helper

### PR DESCRIPTION
**Pull request by JulianKniephoff**
I forgot to move a file when retargeting #255
from `r/3.x` to `r/5.x`.
This fixes that.

### CODE REVIEW

**Comment by staubesv** [comment]
Hi @JulianKniephoff I think that PR should go into r/5.x, right?

**Comment by JulianKniephoff** [comment]
In my head this is a feature, so it should go into `develop`, right?

~~But I can of course retarget it if you want, I have no hard opinion on that. Just say the word. :slightly_smiling_face:

---

**EDIT**: It's too hot. I thought this was #266 ...

Yes you are right of course, will retarget momentarily.

**Comment by staubesv** [comment]
I thought that you have applied a PR to r/3.x and merged this upwards to r/4.x and r/5.x but forgot about the folder structure between r/4.x and r/5.x are different. 

How can this (put file into admin-ui instead of matterhorn-admin-ui-ng) be a feature?

Update: Just had a closer look at it: #255 has already been merged to r/5.x. As this fixes an error in #255, it should go to r/5.x.

**Comment by JulianKniephoff** [comment]
See my edit, I thought we were talking about another PR. ;)

**Comment by JulianKniephoff** [comment]
done

**Review by staubesv — APPROVED** [review]
Thanks ;-)

**Pull request merged**
