### PR TITLE
MH-12367: Renaming all database tables

### PR DESCRIPTION
**Pull request by gregorydlogan**
Continuing on our rebranding journey, this PR renames all of our current database tables, as well as cleans up two icons which remained in the old bundle naming structure.

### CODE REVIEW

**Comment by gregorydlogan** [comment]
Updates re: #20 complete, rebased onto tip of develop.  Ready for review.

**Comment by lkiesow** [comment]
I get a few database errors when running the upgrade script on a vanilla oc4 database:

```
ERROR 1091 (42000) at line 339 in file: '../../upgrade/4_to_5/mysql5.sql': Can't DROP FOREIGN KEY `FK_mh_user_setting_organization`; check that it exists                                                          
Query OK, 0 rows affected (0.03 sec)                                                                                                                                                                               
Records: 0  Duplicates: 0  Warnings: 0                                                                                                                                                                             
                                                                                                                                                                                                                   
ERROR 1091 (42000) at line 341 in file: '../../upgrade/4_to_5/mysql5.sql': Can't DROP FOREIGN KEY `FK_mh_user_setting_username`; check that it exists                                                              
Query OK, 0 rows affected (0.02 sec)                                                                                                                                                                               
Records: 0  Duplicates: 0  Warnings: 0 
```

**Comment by lkiesow** [comment]
However, apart from those errors, there are actually no differences in an OC4 database which was upgraded and a new OC database. Still, there should be no errors.

**Comment by lkiesow** [comment]
I also get an error building Opencast (DB errors during testing):

    [INFO] Opencast :: event-comment .......................... FAILURE [  4.240 s]

The modules error log: https://paste.fedoraproject.org/paste/puLscts9UbD0hthcWz5c4g

**Comment by lkiesow** [comment]
The latest patch now results in a different database structure when I take an OC4 database and upgrade it compared to a vanilla oc5 database:

```diff
% diff oc4to5.sql oc5.sql                                                                                                                                                   (git)-[develop] [0]
3c3
< -- Host: localhost    Database: oc4to5
---
> -- Host: localhost    Database: oc5
1581c1581,1583
<   KEY `IX_oc_user_setting_organization` (`organization`)
---
>   KEY `IX_oc_user_setting_organization` (`organization`),
>   CONSTRAINT `FK_oc_user_setting_organization` FOREIGN KEY (`organization`) REFERENCES `oc_user` (`organization`),
>   CONSTRAINT `FK_oc_user_setting_username` FOREIGN KEY (`username`) REFERENCES `oc_user` (`username`)
1603c1605
< -- Dump completed on 2018-02-07 13:23:58
---
> -- Dump completed on 2018-02-07 13:24:08
```

**Comment by gregorydlogan** [comment]
Should be fixed now.  That's what I get for working with a headcold.

**Comment by staubesv** [comment]
@gregorydlogan Please note that this script does not work with MariaDB (doesn't support the IF EXISTS).

I've also found that the key names of foreign keys will still contain the "mh_" prefix. But it is absolutely possible that this is just my fault - I'm an absolute dummy considering databases.

**Comment by lkiesow** [comment]
hmm… I'm pretty sure I've tested this on a MariaDB and not on MySQL

**Comment by gregorydlogan** [comment]
Yep, me too. If anything I would expect it to be under tested on MySQL.

**Pull request merged**
