### PR TITLE
Add Event Metrics

### PR DESCRIPTION
**Pull request by lkiesow**
This patch adds an additional series to the metrics endpoint, providing
the current number of events per organization in the asset manager.

### Your pull request should…

* [x] have a concise title
* [x] [close an accompanying issue](https://help.github.com/en/articles/closing-issues-using-keywords) if one exists
* [x] be against the correct branch (features can only go into develop)
* [x] include migration scripts and documentation, if appropriate
* [x] pass automated tests
* [x] have a clean commit history
* [x] [have proper commit messages (title and body) for all commits](https://medium.com/@steveamaza/e028865e5791)

### CODE REVIEW

**Review by gregorydlogan — APPROVED** [review]
This looks good to me, but I've never used the events metrics so I'm not hugely comfortable with merging it without properly testing.  Has this been thrown onto a testing system with actual data in it?

**Comment by KatrinIhler** [comment]
I'm planning to throw this onto the SWITCH test system since we are currently setting up a Prometheus instance. But we are currently waiting on firewall stuff to happen, so no idea when we can actually test this.

**Comment by lkiesow** [comment]
> But we are currently waiting on firewall stuff to happen, so no idea when we can actually test this.

None of the firewall problems should apply here since this is going out of the admin via HTTPS and Prometheus just collects the metrics.

---

@gregorydlogan, if you want to test it, just [download Prometheus](https://prometheus.io/download/) and run it with a configuration like this:

```yml
global:
  scrape_interval:     30s
  evaluation_interval: 30s

scrape_configs: 
  - job_name: opencast
    scheme: http
    basic_auth:
      username: admin
      password: opencast
    static_configs:
      - targets:
        - localhost:8080
```

Then you can query the metrics via the Prometheus web interface.

**Comment by KatrinIhler** [comment]
@lkiesow The firewall stuff is on the Prometheus end. :D No idea how much Nesibe can test if she can't get to the UI...

**Review by KatrinIhler — APPROVED** [review]
I actually took the time and set up a local Prometheus and attached it to the SWITCH staging system. Beware my first ever Prometheus graph! :D
image

So yeah, this works just as I would expect.

**Comment by lkiesow** [comment]
It doesn't seem like there was a lot happening in that second :laughing: 
Thanks for the review.

**Pull request merged**
