### PR TITLE
MH-12177 TimeZone threadsafe and bulk schedule across DST (NEW)

### PR DESCRIPTION
**Pull request by krinnewitz**
This is a continuation of PR #604 by @karendolan .

The PR basically resolves problems where testcases were failing depending on which system default timezone was set in the executing VM.

We have tried executing the tests with the following timezones:
- Europe/Berlin
- America/Phoenix
- America/St_Johns
- Africa/Johannesburg

You can pass timezones to maven or the JVM using e.g. `-Duser.timezone=America/Phoenix`.

Due to a bug in ical4j, we had to create a patched version of ical4j which is available here: https://github.com/plapadoo/ical4j/releases/tag/ical4j-3.0.6-patched

In order for the build to complete, we need someone with access rights to push the jars to Opencast's private maven repository with ` -DgroupId=org.mnode.ical4j -DartifactId=ical4j -Dversion=3.0.6-patched -Dpackaging=jar`

Our PR against ical4j can be found here: https://github.com/ical4j/ical4j/pull/314

### CODE REVIEW

**Comment by krinnewitz** [comment]
Just noticed that there are still issues with javax.cache dependency. Working on it.

EDIT: It turned out that there is a problem with ical4j and OSGi: 

- https://github.com/ical4j/ical4j/issues/115 
- https://github.com/ical4j/ical4j/pull/116

I included the workaround from https://github.com/ical4j/ical4j/issues/115  in my 3.0.6-patched build and it's working now.

**Comment by krinnewitz** [comment]
So since there are two problems in ical4j, I guess it makes sense to push the patched version to Opencast's private maven repo. Even if ical4j/ical4j#314 is merged, I think it will take longer until     ical4j/ical4j#115 gets fixed.

**Comment by gregorydlogan** [comment]
I'm checking this locally now, will push the patched version to Nexus, then merge this once it's re-checked.

**Comment by gregorydlogan** [comment]
This works as expected in 6.x, so I'm going to push it.  The merge to develop is ugly though, so that will probably be the rest of my day.

**Pull request merged**
