### PR TITLE
MH-12969, Ensure formatting of OSGI configuration

### PR DESCRIPTION
**Pull request by lkiesow**
This ensures a homogeneous style for all OSGI configuration files based
on the Intellij IDEA code formatter.

### CODE REVIEW

**Comment by staubesv** [comment]
Happy to take the review ;-)

**Comment by staubesv** [comment]
@lkiesow 

Hmm... this PR would cause merge conflicts in quite a number of long out-standing PRs. For reasons of fairness, I suggest to hold this back for now.

**Comment by karendolan** [comment]
@lkiesow Can this be added to the checkstyle? What are the  prefs for Intellij IDEA code formatter that I can add to Eclipse/oXygen?
eclipsexmlprefs

**Comment by lkiesow** [comment]
@staubesv, when do you want to apply this?

---

@karendolan, this pull request was my reaction of @staubesv's suggestion to unify the formatting of all those files manually over time. I just used the current IDEA defaults set in the Opencast style.

Looking at your screenshot, setting line length to 120 characters and indentation to 2 spaces should definitely make sense. I'm not sure if Eclipse supports attribute alignment. If you figure something out to make things look more alike, can you maybe update the [eclipse_settings template](https://github.com/opencast/opencast/tree/develop/docs/eclipse_settings)?

**Comment by lkiesow** [comment]
@staubesv, ping.

**Comment by staubesv** [comment]
Hi @lkiesow 

Here a list of pull requests older than this one that potentially (I didn't check in detail) will end-up with merge conflicts if this one is merged:

#167, #178, #197, #208, #209, #232, #265, #299, #301, #303

Some of those have been waiting for code reviews for weeks and already had merge conflicts several times because of "waiting".

No strong opinion about this, but it seems unfair if a new pull request just gets merged sooner causes work for all others. In in my experience, this tends to happen quite often for larger pull requests which causes quite some developer time being wasted in the Opencast community.

The most efficient way to get this (formatting of XML) done would be to wait for those being merged and then apply the "new" formatting to just everything and ask any PR after this to come up with that formatting.

**Comment by gregorydlogan** [comment]
@karendolan ping re: the Eclipse formatting settings.  Is this doable?

I'm thinking this should go on hold until right before release to minimize disruption to existing PRs.

**Comment by karendolan** [comment]
HI @gregorydlogan can you clarify the doable regarding the Eclipse setting? The pull for optional import was already merged. A readme, doc, wiki somewhere probably needs to be updated to describe how to import it, is that the source of the ping?

**Comment by gregorydlogan** [comment]
@karendolan I was referring to the automated formatting rules for the Eclipse formatting system.

**Comment by lkiesow** [comment]
That's already reviewed and merged.
You just need to use the current setting from the Opencast repo.

**Comment by lkiesow** [comment]
In general, I think holding back pull requests even though they are completely fine, especially when they have a relatively small impact like this one does is a bad idea. I do not care much about this one since conflicts are easy to fix (though I am slightly annoyed about the additional work which is pushed to me for no reason).

First, think about how many pull requests you disrupt in either case. For that, you need to know how many pull requests will be released before and after a pull request like this. The simple answer is that you do not know since you cannot look into the future. Hence, the best guess is that an equal amount of pull requests will be released so that by merging it now you would create conflicts in an equal amount of pull requests as you would when waiting, merging it later and creating conflicts with the new pull requests. So looking at just that, it does not matter when you merge.

However, the work of fixing the conflicts within old pull requests does not go away if you wait. Sure, old pull requests have fewer conflicts, but it's just that the work is shifted to the creator of this pull request. In this case, you push the work to me. And that's not all since you also create conflicts with new pull requests. Hence, in the end, you create more work by waiting.

Finally to the point of fairness. By now I have reviewed a couple of the pull requests @staubesv  has mentioned. What's interesting is that some of those I reviewed are not at all affected by this pull requests and *none* of the other ones were ready to be merged when I started the review. So you are blocking a patch which is completely fine in favor of non-ready pull requests. Is that fair? I don't think so. In fact, acting like this, you do encourage people to open placeholder pull requests just to be first in line.

Just my few cents, but I don't like the direction this is turning in general…

**Comment by lkiesow** [comment]
Updated and rebased to the `HEAD` of `develop`.
Should be ready to go.

**Review by staubesv — APPROVED** [review]

**Comment by staubesv** [comment]
Hi @lkiesow Merged as promised. I went through the open pull requests and notified the authors about merge conflicts. The following PRs are affected:

https://github.com/opencast/opencast/pull/193
https://github.com/opencast/opencast/pull/208
https://github.com/opencast/opencast/pull/209
https://github.com/opencast/opencast/pull/301
https://github.com/opencast/opencast/pull/303
https://github.com/opencast/opencast/pull/319
https://github.com/opencast/opencast/pull/321

**Pull request merged**
