### PR TITLE
Show user information in event workflow details

### PR DESCRIPTION
**Pull request by Arnei**
Currently, if you go to the workflows tab of the event details modal and check which user started a workflow, you will see that users id. If you are using auth services like e.g. Shibboleth, the user id is likely to be a random assortment of letters and numbers that are not helpful in determining who started the workflow. This PR changes the "submitter" value returned from the backend, so that instead of the user id the user name and email are displayed.

How it currently looks:
Bildschirmfoto vom 2023-05-26 10-01-42
With the PR:
Bildschirmfoto vom 2023-05-26 10-02-04

This PR presumes that no one actually has a use for the user id in the workflow tab. If you think otherwise, please let me know. We can work something out, e.g. keeping the user id and creating an extra column for the user name and email.

### Your pull request should…

* [x] have a concise title
* ~[ ] [close an accompanying issue](https://help.github.com/en/articles/closing-issues-using-keywords) if one exists~
* [x] [be against the correct branch](https://docs.opencast.org/develop/developer/development-process#acceptance-criteria-for-patches-in-different-versions)
* ~[ ] include migration scripts and documentation, if appropriate~
* [x] pass automated tests
* [x] have a clean commit history
* [x] [have proper commit messages (title and body) for all commits](https://medium.com/@steveamaza/e028865e5791)

### CODE REVIEW

**Comment by ziegenberg** [comment]
Why not show the username in brackets?

**Comment by ziegenberg** [comment]
We have students and staff separated into different users, but they share the same email address if one person is a student and staff member at the same time. After this PR we would no longer be able to differentiate between them. The username would enable us to tell students and start members apart.

**Comment by Arnei** [comment]
Sure, if the user ids are useful to people then I'll put them back. Did you mean like this?:

Bildschirmfoto vom 2023-05-31 11-38-14

**Comment by ziegenberg** [comment]
> Sure, if the user ids are useful to people then I'll put them back. Did you mean like this?:

Yes, exactly!

**Comment by snoesberger** [comment]
Thanks for this improvement. I have successfully tested the change in our environment.

**Pull request merged**
