### PR TITLE
Change default captions flavor for Editor Service

### PR DESCRIPTION
**Pull request by KatrinIhler**
For more details, see this discussion: https://github.com/opencast/opencast-editor/issues/1189

### CODE REVIEW

**Comment by Arnei** [comment]
Might make sense to point this at `r/15.x`, since this config fix is related to the subtitle rework we did with 15.0?

**Comment by KatrinIhler** [comment]
Maybe, but then I might have to add release notes, and I was too lazy to do that :D

**Comment by KatrinIhler** [comment]
Need to think about what this means for editing captions.

**Comment by KatrinIhler** [comment]
Obsolete with #5862

**Pull request closed without merging**
