### PR TITLE
Replace Elastic "bool" query for roles with "terms" query

### PR DESCRIPTION
**Pull request by LukasKalbertodt**
The manually built "bool" query (i.e. "has this role OR has that role") can easily bloat the query a lot. When a user has lots of roles, it is possible to run into limits. Using the "terms" query seems more appropriate as we can provide all user roles as array. The JSON sent to Elastic is noticeably smaller with this and the "query limit" won't be a problem.

The ["terms" query](https://www.elastic.co/guide/en/elasticsearch/reference/7.17/query-dsl-terms-query.html) is described as:

> Returns documents that contain one or more exact terms in a provided
> field.

For array fields, this works as expected: it is matched if there is any overlap between the input roles and the roles in the ACL.

Before, each part of the bool query was a `matchQuery`, which can allow for fuzzy matching. However, the ACL fields have the type `keyword` (and not `text`), so no fuzzy analysis is done anyway. I tested this with a few examples.

<details>
<summary>New query sent to Elastic</summary>

```json
{
  "bool" : {
    "must" : [
      {
        "term" : {
          "org" : {
            "value" : "mh_default_org",
            "boost" : 1.0
          }
        }
      },
      {
        "term" : {
          "type" : {
            "value" : "Episode",
            "boost" : 1.0
          }
        }
      },
      {
        "match" : {
          "fulltext" : {
            "query" : "cat",
            "operator" : "OR",
            "prefix_length" : 0,
            "max_expansions" : 50,
            "fuzzy_transpositions" : true,
            "lenient" : false,
            "zero_terms_query" : "NONE",
            "auto_generate_synonyms_phrase_query" : true,
            "boost" : 1.0
          }
        }
      },
      {
        "terms" : {
          "searchable_acl.read" : [
            "ROLE_API_EVENTS_EDIT",
            "ROLE_USER",
            "ROLE_USER_PETER",
            "ROLE_ANONYMOUS"
          ],
          "boost" : 1.0
        }
      }
    ],
    "must_not" : [
      {
        "exists" : {
          "field" : "deleted",
          "boost" : 1.0
        }
      }
    ],
    "adjust_pure_negative" : true,
    "boost" : 1.0
  }
}
```
</details>

<details>
<summary>Old query sent to Elastic</summary>

```json
{
  "bool" : {
    "must" : [
      {
        "term" : {
          "org" : {
            "value" : "mh_default_org",
            "boost" : 1.0
          }
        }
      },
      {
        "term" : {
          "type" : {
            "value" : "Episode",
            "boost" : 1.0
          }
        }
      },
      {
        "match" : {
          "fulltext" : {
            "query" : "cat",
            "operator" : "OR",
            "prefix_length" : 0,
            "max_expansions" : 50,
            "fuzzy_transpositions" : true,
            "lenient" : false,
            "zero_terms_query" : "NONE",
            "auto_generate_synonyms_phrase_query" : true,
            "boost" : 1.0
          }
        }
      },
      {
        "bool" : {
          "should" : [
            {
              "match" : {
                "searchable_acl.read" : {
                  "query" : "ROLE_API_EVENTS_EDIT",
                  "operator" : "OR",
                  "prefix_length" : 0,
                  "max_expansions" : 50,
                  "fuzzy_transpositions" : true,
                  "lenient" : false,
                  "zero_terms_query" : "NONE",
                  "auto_generate_synonyms_phrase_query" : true,
                  "boost" : 1.0
                }
              }
            },
            {
              "match" : {
                "searchable_acl.read" : {
                  "query" : "ROLE_USER",
                  "operator" : "OR",
                  "prefix_length" : 0,
                  "max_expansions" : 50,
                  "fuzzy_transpositions" : true,
                  "lenient" : false,
                  "zero_terms_query" : "NONE",
                  "auto_generate_synonyms_phrase_query" : true,
                  "boost" : 1.0
                }
              }
            },
            {
              "match" : {
                "searchable_acl.read" : {
                  "query" : "ROLE_USER_PETER",
                  "operator" : "OR",
                  "prefix_length" : 0,
                  "max_expansions" : 50,
                  "fuzzy_transpositions" : true,
                  "lenient" : false,
                  "zero_terms_query" : "NONE",
                  "auto_generate_synonyms_phrase_query" : true,
                  "boost" : 1.0
                }
              }
            },
            {
              "match" : {
                "searchable_acl.read" : {
                  "query" : "ROLE_ANONYMOUS",
                  "operator" : "OR",
                  "prefix_length" : 0,
                  "max_expansions" : 50,
                  "fuzzy_transpositions" : true,
                  "lenient" : false,
                  "zero_terms_query" : "NONE",
                  "auto_generate_synonyms_phrase_query" : true,
                  "boost" : 1.0
                }
              }
            }
          ],
          "adjust_pure_negative" : true,
          "boost" : 1.0
        }
      }
    ],
    "must_not" : [
      {
        "exists" : {
          "field" : "deleted",
          "boost" : 1.0
        }
      }
    ],
    "adjust_pure_negative" : true,
    "boost" : 1.0
  }
}
```
</details>

### Your pull request should…

* [ ] have a concise title
* [ ] [close an accompanying issue](https://docs.opencast.org/develop/developer/#participate/development-process/#automatically-closing-issues-when-a-pr-is-merged) if one exists
* [ ] [be against the correct branch](https://docs.opencast.org/develop/developer/development-process#acceptance-criteria-for-patches-in-different-versions)
* [ ] include migration scripts and documentation, if appropriate
* [ ] pass automated tests
* [ ] have a clean commit history
* [ ] [have proper commit messages (title and body) for all commits](https://medium.com/@steveamaza/e028865e5791)

### CODE REVIEW

**Comment by LukasKalbertodt** [comment]
I only found these two cases where ACL/roles are converted into such a bool query. If there are more somewhere, let me know so that I can replace them too.

**Comment by lkiesow** [comment]
Did you also check the asset manager/index service queries? If I remember correctly, they do something similar.

**Comment by LukasKalbertodt** [comment]
I didn't check them explicitly, but now I grepped the whole project for `searchable_acl`, `INDEX_ACL`, `boolQuery` and `roleQuery`, without finding any other spot that would need adjustment. So I guess that's it?

**Comment by gregorydlogan** [comment]
Easy way to check, look for uses of `QueryBuilders` and its methods.  Looks like the class in in use in a few places, but `matchQuery` is only used twice, both times for full text search in the same class you've modified here.

**Pull request merged**
