### PR TITLE
Rename OSGi Core dependency artifact id

### PR DESCRIPTION
**Pull request by geichelberger**
The OSGi Core artifact moved from org.osgi:org.osgi.core to org.osgi:osgi.core.

* [x] have a concise title
* [x] [close an accompanying issue](https://help.github.com/en/articles/closing-issues-using-keywords) if one exists
* [ ] [be against the correct branch](https://docs.opencast.org/develop/developer/development-process#acceptance-criteria-for-patches-in-different-versions)
* [x] include migration scripts and documentation, if appropriate
* [x] pass automated tests
* [x] have a clean commit history
* [x] [have proper commit messages (title and body) for all commits](https://medium.com/@steveamaza/e028865e5791)

### CODE REVIEW

**Comment by lkiesow** [comment]
This seems to work as expected, but I don't see any good reason to increase the risk and bring this into the legacy release of Opencast. In general, I'd like to avoid all unnecessary changes there. Did I miss something? If not, can you target `develop` instead?

**Comment by geichelberger** [comment]
It would cause fewer troubles during merging. That's why I filed it against branch 12.x.

**Comment by lkiesow** [comment]
Not expecting any huge changes for `r/12.x` since it is the legacy release, can we at least move this to `r/13.x` instead? Personally, I would even move it to `develop`.

**Comment by geichelberger** [comment]
This PR is obsolete, superseded by #4930

**Pull request closed without merging**
