### PR TITLE
Update adopter-registration-rest.xml to solve #1934 issue

### PR DESCRIPTION
**Pull request by VictorSalgado**
Solving issue #1934 Rename /admin-ng/adopter/statistics #1934

### Your pull request should…

* [x] have a concise title
* [ ] [close an accompanying issue](https://help.github.com/en/articles/closing-issues-using-keywords) if one exists
* [ ] be against the correct branch (features can only go into develop)
* [x] include migration scripts and documentation, if appropriate
* [x] pass automated testing
* [x] have a clean commit history
* [x] have proper commit messages (title and body) for all commits
* [x] have appropriate tags applied

### CODE REVIEW

**Comment by lkiesow** [comment]
Thanks for the patch. Will review this later today.
If you are interested, there is also the related issue #1935

**Comment by VictorSalgado** [comment]
Thanks Lars, it was my first open source contribution, so in case something is wrong please let me know. 
In the following days I will review #1935 to continue contributing.

**Comment by lkiesow** [comment]
That's cool. I'll try to put some additional hints at the issue which might help. Feel free to ask if you have any questions. There is also a chat (linked on https://docs.opencast.org) where usually one or two developers hang around

**Comment by lkiesow** [comment]
@VictorSalgado, I did take a short first look. This changes the REST endpoint's location but does not change the usage. Shortly looking for places where it's being used (should all be in the `admin-ui-frontend` module revealed at least:

```
modules/adopter-statistics-impl/src/main/resources/OSGI-INF/adopter-registration-rest.xml:9:    <property name="opencast.service.path" value="/admin-ng/adopter/statistics"/>
modules/admin-ui-frontend/test/test/unit/shared/controllers/applicationControllerSpec.js:30:        $httpBackend.whenGET('/admin-ng/adopter/statistics/registration').respond(
modules/admin-ui-frontend/app/scripts/shared/resources/adopterRegistrationResource.js:25:  return $resource('/admin-ng/adopter/statistics/registration');
```

Can you check/update those additional places as well and update the pull request?

**Review by lkiesow — APPROVED** [review]
This looks good.

The only thing left to do it to redirect this pull request against the `r/9.x` branch instead of `develop`. To do that, the target branch of this pull request needs to be changed, and we need to rebase this against `r/9.x` using `git`.

I can do that for you or I can give you a few hints if want to try yourself. Let me know.

**Comment by VictorSalgado** [comment]
I prefer to learn how to do it! Please tell me the hints to change the
target branch please.

Thanks in advance Lars!

**Comment by lkiesow** [comment]
Here in GitHub it's simply clicking the “edit” button at the top right of the pull request and selecting `r/9.x` instead of `develop`. But in the current state, this would include several additional patches which are in `develop` but not in the release branch. That's something we need to change.

Opencast's  branching for the next release and the ongoing development branch looks more or less like this
```
               A     B  C
develop ---*---*--*--*--*--*-->
            \    /        /
      r/9.x  *--*--*--*--*-->
                         X
```

You have commits like `A`, `B` or `C` which are in `develop` only and which you don't want to bring to `r/9x` – they will become part of Opencast 10 in the long run. Your branch `patch-1` is currently based on `develop` and includes those patches. What we want is to put these patches at the end of `r/9.x` behind the commit `X`.

You can do this with a `git rebase` by running:

```
git checkout patch-1   <- make sure you are on your branch
git rebase -i r/9.x   <- rebase your patch
git push --force-with-lease origin patch-1   <- Overwrite your current pull request
```

The interactive rebase (`git rebase -i`) will open an editor and show you each patch which is in your current branch but not in the branch you are rebasing on from oldest to newest. So, your two patches should be at the end. this should look somewhat like this:
```
pick e6a285c780 Oldest patch                                                            
pick 0bfd3c62bf Second oldest patch
…
```
Delete all patches you don't want in your pull request (all but your two patches). Then save and close the file. Git will now start with `r/9.x` and put all patches you picked on top, one after another.

Using `git rebase` is also really handy if you want to update your patches e.g. before creating a pull request. In addition to using `pick`, you can also instruct `git` to combine patches, change the commit message, … But we don't need that here.

Finally, the forced push will overwrite your current pull request. As with all forced actions, be careful and check if you really want to do that ;-)

If you want to try this before actually working on your patch, create a temporary branch to play around with. Something like:

```
git checkout patch-1
git checkout -b tmp
git rebase -i r/9.x
git log --oneline --decorate
```

**Comment by VictorSalgado** [comment]
Hi Lars, 

I'm very grateful that you to showed me how to do it and all the tips that you've given to me. 

I've followed all the steps that you said to me and I think the pull request is ready.

**Comment by lkiesow** [comment]
Thanks again for the patch. Happy to talk anyone through something like this if they are interested ;-)

One very minor thing that was missing was to actually change the target branch here in GitHub's user interface. But since that's really just a click in the user interface… I just did that:
Screenshot from 2020-10-12 17-59-47

Have fun with other Hacktoberfest tasks! And let us know if you are looking for other small tasks to try (Also, what type of task JS, Java, Python, …)

**Pull request merged**
