### PR TITLE
MH-12747 Fix the JobProducerHeartbeat

### PR DESCRIPTION
**Pull request by smarquard**
This was failing on first run because of an NPE in AbstractUrlSigningProvider because the
organization context was not set for the URL.

Also add a try/catch block around the code so that errors are reported, and that an error
in one run doesn't prevent it from being invoked in future.

### CODE REVIEW

**Comment by smarquard** [comment]
ServiceRegistryJpaImpl looks like a lot of changes but it's just a try/catch block and indentation for the code inside.

**Comment by smarquard** [comment]
A git secret from https://blog.github.com/2011-10-21-github-secrets/! View diff ignoring whitespace:

https://github.com/opencast/opencast/pull/117/files?diff=unified&w=1

**Comment by CGreweling** [comment]
Code Looks good to me. I have seen the error in Opencast before. But i don't know how to reproduce this error. Any hint for me?

**Comment by smarquard** [comment]
You could switch on debug logging for serviceregistry, in org.ops4j.pax.logging.cfg:

    log4j.logger.org.opencastproject.serviceregistry=DEBUG

Then you should see the heartbeat start and stop every minute:

````
2018-03-08 16:11:26,537 | DEBUG | pool-33-thread-1 | (ServiceRegistryJpaImpl$JobProducerHeartbeat:3272) - Checking for unresponsive services
2018-03-08 16:11:26,946 | DEBUG | pool-33-thread-1 | (ServiceRegistryJpaImpl$JobProducerHeartbeat:3344) - Finished checking for unresponsive services
````

If you don't see that, then the JobProducerHeartbeat has stopped running.

**Review by gregorydlogan — APPROVED** [review]
This looks good to me

**Pull request merged**
