### PR TITLE
MH-10016 Default Workflow

### PR DESCRIPTION
**Pull request by KatrinIhler**
Setting org.opencastproject.workflow.default.definition in custom.properties currently doesn't have any effect in the admin-ui. With this patch the default workflow is preselected when creating a new event.

### CODE REVIEW

**Comment by staubesv** [comment]
Hi @KatrinIhler,

AFAIK, the default workflow setting is used to specify the workflow to be used in case no workflow was specified during ingest.
For the Admin UI, having one default workflow won't work in general as there are different types of workflows (upload, schedule, archive, delete, editor) used for different purposes. Each of this workflow type would require its own "default workflow"... seem from that point of view, using the existing "default workflow" property is somewhat smelly as there is no such thing as "the" default workflow in the context of Admin UI. Also, the "default workflow" (as used for ingest) is not necessarily a workflow that is used in the Admin UI at all.

**Comment by lkiesow** [comment]
@staubesv, this is the best we have at the moment for a default value and it is *not*  specified as service configuration but as a global configuration. hence, using this if applicable (workflow has the required tag) does make sense and makes Opencast's behavior better than it was before.

I agree, however, that adding an admin interface configuration file to specify defaults for different places in the ui would be nice. But that's outside of the scope for this ticket.

**Comment by staubesv** [comment]
Damn... just accidentally merged this PR (wanted to merge #2). Created #18 to revert that accidental merge.

**Comment by lkiesow** [comment]
@staubesv, it's probably easier to fix any outstanding issues instead of reverting the merge which then later would need to be reverted in turn. Do you have any specific issues with this code?

**Comment by staubesv** [comment]
Hi @KatrinIhler & @lkiesow:

I don't have a strong opinion about this PR, but it seems to just replace one issue by another new one.

I had a quick look at the code: The AbstractEventEndpoint is already using the AdminUIConfiguration class that provides access methods to properties specified in org.opencastproject.adminui.cfg. So, allternatively, you could add properties like: default.workflow.upload, default.workflow.schedule, default.workflow.delete ...

The advantage would be that default workflows could be set independently for different (unrelated) subsystems (ingest service vs. admin ui facade) and also for the different workflow types as used by the Admin UI.

What do you think?

**Comment by KatrinIhler** [comment]
@staubesv:
I see your point. However, when creating a new event, both upload and schedule workflows are presented in the drop-down menu for selection - if there is a default for both which possibly conflict, which one would be the default shown?

**Comment by staubesv** [comment]
@KatrinIhler: Well, that (both upload and schedule workflows shown) is a bug not related to this issue ;-)

**Comment by lkiesow** [comment]
Even if you introduce those additional options, I would still have them set to this as default since this option is defining a *global* default workflow which, by the way, was previously used in the admin interface for exactly this default selection already ;-P

**Comment by staubesv** [comment]
My key point was that there is no such thing as a global default workflow from point of view of the Admin UI as the Admin UI offers different workflow selections that require different default workflows since a workflow used in add event, for example, will in general not be applicate in Actions->Start Tasks. And even if it was, you don't necessarily want the same default in the different workflow selections.

Anyway, I took the review of this PR and will accept it post-merge - that seems the most reasonable way to proceed.

**Pull request merged**
