### PR TITLE
MH-12603, Take 'ng' out of the youtube composite operation

### PR DESCRIPTION
**Pull request by reiferschris**
- remove ng- prefix from exception-handler-workflow
- MH-12603 Take 'ng' out of the workflow filenames

### CODE REVIEW

**Comment by staubesv** [comment]
@reiferschris Since this is a bugfix, can you please redirect the pull request to r/5.x?

**Review by staubesv — CHANGES_REQUESTED** [review]
@reiferschris Since this is a simple low-risk bugfix, can you please redirect the pull request to r/5.x?

**Comment by reiferschris** [comment]
@staubesv i hopefully redirected it to r/5.x, now I'm wondering why all the previous commits are in this pull requests history? Did I mess up?

**Comment by KatrinIhler** [comment]
@reiferschris You probably need to rebase your commit on 5.x or your gonna introduce all the commits that aren't in 5.x.

**Comment by lkiesow** [comment]
> @staubesv i hopefully redirected it to r/5.x, now I'm wondering why all the previous commits are in this pull requests history? Did I mess up?

The reason is that your patch was based on a newer branch and by simply changing the target branch you are telling Github that you want the other branch plus your patch to be merged into `r/5.x`. What you need to do additionally to changing the target branch here in Github is to rebase your source branch using git. What you essentially need to do is:

```shell
git checkout develop
# Your develop since that is the branch your patch is in

git fetch upstream
# assuming that upstream is your remote name for the Opencast repo

git rebase -i upstream/r/5.x 
# This will ask which patches you want to add to `r/5.x`
# Delete everything except your patch

git push -f origin develop
# Overwrite your remote branch
```

In general, I recommend to always create a branch as first step since having a develop which really is a r/5.x plus a patch can be confusing although it is no technical problem.

**Comment by staubesv** [comment]
@reiferschris Sorry for the trouble my request has caused... but for low-risk bugs like this, it makes sense to include it in all supported version - otherwise, another person might raise another pull request to fix it in older versions.

In case you are unfamiliar with git command line, you can also just close this pull request, redo the change (but this time branching away from r/5.x) and raise new pull requests against r/5.x.

**Comment by reiferschris** [comment]
@staubesv I will close this pull request and raise a new one from my own fork. Thank you for being so patient with me, I am indeed new to this. Hopefully next time I will make fewer mistakes. I fully understand your reasoning for the request.
Also thanks to @lkiesow and @KatrinIhler for explaining what I could do to fix this, next time I will create a new branch first, so I don't run into issues later.

**Comment by staubesv** [comment]
@reiferschris Thanks a lot for contributing to Opencast!

**Pull request closed without merging**
