### PR TITLE
Remove Dead OpenID Module

### PR DESCRIPTION
**Pull request by lkiesow**
This patch removes the opencast-openid module. It seems like it belonged
to Opencast's CAS stack at some point but is not used in any way any
longer. It also does not contain any code but just includes some
dependencies which we then ignore.

This module currently holds the broken dependency which makes Opencast
fail to build.

### Your pull request should…

* [x] have a concise title
* [x] [close an accompanying issue](https://help.github.com/en/articles/closing-issues-using-keywords) if one exists
* [x] be against the correct branch (features can only go into develop)
* [x] include migration scripts and documentation, if appropriate
* [x] pass automated testing
* [x] have a clean commit history
* [x] have proper commit messages (title and body) for all commits
* [x] have appropriate tags applied

### CODE REVIEW

**Comment by mliradelc** [comment]
All good from this side, Merged!

**Review by mliradelc — COMMENTED** [review]
All good!!

**Comment by mtneug** [comment]
`spring-security-openid` is still included and NOTICE is not updated.

**Comment by lkiesow** [comment]
You are right, I've addressed this in  #1894

**Pull request merged**
