### PR TITLE
Editor Service Build

### PR DESCRIPTION
**Pull request by lkiesow**
This patch fixes the concurrency problem when building the editor
service endpoint remote and tries to simplify the architecture to make
it easier to understand what is going on.

Most of the changes are just moving around code with no major
modifications but this:

- Switched to using OSGi annotations from manually specifying components
  in XML files.
- Moved the core functionality of the endpoint into the API module
  instead of manually copying it to other modules.
- Implements the actual endpint in the service modules (basically just
  annotations and docs).

### Your pull request should…

* [x] have a concise title
* [x] [close an accompanying issue](https://help.github.com/en/articles/closing-issues-using-keywords) if one exists
* [x] [be against the correct branch](https://docs.opencast.org/develop/developer/development-process#acceptance-criteria-for-patches-in-different-versions)
* [x] include migration scripts and documentation, if appropriate
* [x] pass automated tests
* [x] have a clean commit history
* [x] [have proper commit messages (title and body) for all commits](https://medium.com/@steveamaza/e028865e5791)

### CODE REVIEW

**Review by lwillmann — COMMENTED** [review]
Looks good for me. Thanks for the cleanup

**Review by mtneug — APPROVED** [review]
Don't we need the Swagger definition?

What does `_dsannotations-options` mean?

**Comment by lkiesow** [comment]
> Don't we need the Swagger definition?

They aren't used and aren't accurate any longer already. But I can keep it around if you like?

> What does _dsannotations-options mean?

This controls the OSGi bundler. You remember people complaining that OSGi annotations and manual created OSGi XML files don't play nicely with each other? This makes them. In short, the annotations generate stricter requirements which our old bundles do not provide. This prevents that, keeping it to the service level (same as before). If you want more details, let's make this a topic at the technical meeting, unless you need that in order to let this pull request pass.

**Comment by mtneug** [comment]
No, it's fine. Already approved and those questions were just to clarify.

**Pull request merged**
