### PR TITLE
Fix NPE when signing publication URLs

### PR DESCRIPTION
**Pull request by mtneug**
Publication URLs might be null. Signing them leads to a NPE.

### Your pull request should…

* [x] have a concise title
* [x] [close an accompanying issue](https://help.github.com/en/articles/closing-issues-using-keywords) if one exists
* [x] [be against the correct branch](https://docs.opencast.org/develop/developer/development-process#acceptance-criteria-for-patches-in-different-versions)
* [ ] include migration scripts and documentation, if appropriate
* [x] pass automated tests
* [x] have a clean commit history
* [x] [have proper commit messages (title and body) for all commits](https://medium.com/@steveamaza/e028865e5791)

### CODE REVIEW

**Review by reiferschris — APPROVED** [review]
If I made no mistakes while testing this, I can approve this change. Our dev-system does not show errors in the assets/publications tab anymore after applying this fix. Thank you!

**Comment by KatrinIhler** [comment]
Is this going to be a problem for the External API as well? It can sign publication URLs since #3002.

**Comment by reiferschris** [comment]
I tried testing if the external api has problems but could not reproduce it with querying one of the /api/events//{eventId}/publications/{publicationId}?sign={sign} Endpoints.. But I am not even sure if that would cause it to fail in the first place.
I found this line in your code @KatrinIhler https://github.com/opencast/opencast/pull/3002/files#diff-606d2a3ea1a0603656eb303a059677b604f3bb095b7f81ec97519869f5a751d0R1620 which I would assume prevents this from being a problem, looks kind of similiar to the fix Matthias provided.

**Review by mliradelc — APPROVED** [review]
Can confirm, this fix works.

From @reiferschris confirmation, we are sure that the External API is not affected by this bug

**Comment by mtneug** [comment]
@mliradelc: I wondered as well and looked at the event endpoints. [The `getSignedUrl` method](https://github.com/opencast/opencast/blob/87d371ce918dd2b4009d17206d1b26ee6b8cb616/modules/external-api/src/main/java/org/opencastproject/external/endpoint/EventsEndpoint.java#L1620-L1633) actually has a null check so it should not be affected.

**Pull request merged**
