### PR TITLE
Update Mock Data

### PR DESCRIPTION
**Pull request by lkiesow**
This patch updates the mock data available when running

    npm run build

Some data was partly incorrect or missing.

### Your pull request should…

* [x] have a concise title
* [x] [close an accompanying issue](https://help.github.com/en/articles/closing-issues-using-keywords) if one exists
* [x] be against the correct branch (features can only go into develop)
* [x] include migration scripts and documentation, if appropriate
* [x] pass automated testing
* [x] have a clean commit history
* [x] have proper commit messages (title and body) for all commits
* [x] have appropriate tags applied

### CODE REVIEW

**Comment by felix-itz** [comment]
`/broker/status` is still 404. Is this by intention?

**Review by felix-itz — APPROVED** [review]
see no regression

**Comment by lkiesow** [comment]
> /broker/status is still 404. Is this by intention?

Yep. I was wondering if I should change that but I thought it's actually a good way to mock the warning

**Comment by lkiesow** [comment]
Thanks for the review, @felix-itz  → merging

**Pull request merged**
