### PR TITLE
Add checkstyle-enforced line length limit (with most modules being excluded for now)

### PR DESCRIPTION
**Pull request by LukasKalbertodt**
We just had a discussion about line length limit in ~~IRC~~ our Matrix room. It seemed like everyone agrees that we want this limit, but no one had the time yet to add this checkstyle rule.

Well, adding the rule is the simple part. But then, there are a gazillion style violations. The idea to gradually roll out this style rule is to define a list of exceptions. This is `checkstyle-suppressions.xml`. With this PR, it still contains a very big part of all modules. Over time, we can reformat module after module to make this list smaller until everything abides by the rule. At least that's the plan.

I also added an example commit which resolves all violations in all modules that only had one such violation. (Just for the protocol:  I just used the IDEA autoformatter; I personally would have formatted all of that differently, but I'm not gonna discuss code style here :D).
If you prefer, I can also submit this commit as separate PR. **Note for reviewers**: you probably want to review commit by commit.

---

Here are the remaining modules with violations:

<details>
<summary>Sorted by name</summary>

```
admin-ui => 501
annotation-impl => 41
asset-manager-api => 46
asset-manager-impl => 153
asset-manager-storage-aws => 13
authorization-manager => 31
authorization-xacml => 5
caption-impl => 19
capture-admin-service-impl => 7
comments-workflowoperation => 11
common => 104
common-jpa-impl => 33
composer-ffmpeg => 279
composer-service-api => 15
composer-service-remote => 5
composer-workflowoperation => 55
cover-image-impl => 11
crop-ffmpeg => 6
crop-workflowoperation => 2
distribution-service-api => 3
distribution-service-aws-s3 => 38
distribution-service-download => 9
distribution-service-streaming-wowza => 22
distribution-workflowoperation => 35
dublincore => 42
email-template-service-impl => 4
engage-theodul-core => 9
event-comment => 13
execute-impl => 11
execute-remote => 5
execute-workflowoperation => 9
external-api => 314
fileupload => 21
index-service => 73
ingest-download-service-impl => 6
ingest-download-service-workflowoperation => 2
ingest-service-impl => 169
inspection-service-ffmpeg => 16
kernel => 33
live-schedule-impl => 22
lti => 12
lti-service-impl => 25
message-broker-api => 3
mpeg7 => 33
notification-workflowoperation => 2
oaipmh => 19
oaipmh-persistence => 5
presets => 4
publication-service-api => 4
publication-service-configurable => 13
publication-service-oaipmh => 40
publication-service-oaipmh-remote => 4
publication-service-youtube-v3 => 30
runtime-info => 18
scheduler-api => 5
scheduler-impl => 213
scheduler-remote => 2
schema => 46
search-service-api => 2
search-service-impl => 56
search-service-remote => 2
series-service-api => 2
series-service-impl => 68
series-service-remote => 18
serviceregistry => 134
shared-filesystem-utils => 2
silencedetection-impl => 2
smil-impl => 37
sox-impl => 10
sox-workflowoperation => 2
static-file-service-api => 15
statistics-export-service-impl => 21
statistics-provider-influx => 5
statistics-service-api => 3
statistics-service-impl => 9
statistics-service-remote => 4
termination-state-aws => 20
termination-state-impl => 5
textanalyzer-impl => 4
textanalyzer-workflowoperation => 3
themes => 2
themes-workflowoperation => 3
timelinepreviews-api => 2
timelinepreviews-ffmpeg => 2
timelinepreviews-workflowoperation => 5
transcription-service-amberscript => 4
transcription-service-google-speech-impl => 27
transcription-service-ibm-watson-impl => 24
transcription-service-persistence => 12
transcription-service-workflowoperation => 16
urlsigning-common => 22
urlsigning-service-api => 2
urlsigning-service-impl => 48
urlsigning-verifier-service-impl => 16
user-interface-configuration => 3
userdirectory => 60
userdirectory-brightspace => 7
userdirectory-canvas => 8
userdirectory-ldap => 2
userdirectory-moodle => 3
userdirectory-sakai => 5
usertracking-impl => 74
videoeditor-ffmpeg-impl => 5
videoeditor-workflowoperation => 9
videogrid-service-impl => 3
videogrid-workflowoperation => 14
videosegmenter-ffmpeg => 8
waveform-ffmpeg => 5
waveform-remote => 2
waveform-workflowoperation => 10
workflow-condition-parser => 5
workflow-service-api => 12
workflow-service-impl => 129
workflow-service-remote => 5
workflow-workflowoperation => 24
working-file-repository-service-impl => 55
workspace-impl => 6
```
</details>

<details>
<summary>Sorted by number of violations (not number of files with violations)</summary>

```
crop-workflowoperation => 2
ingest-download-service-workflowoperation => 2
notification-workflowoperation => 2
scheduler-remote => 2
search-service-api => 2
search-service-remote => 2
series-service-api => 2
shared-filesystem-utils => 2
silencedetection-impl => 2
sox-workflowoperation => 2
themes => 2
timelinepreviews-api => 2
timelinepreviews-ffmpeg => 2
urlsigning-service-api => 2
userdirectory-ldap => 2
waveform-remote => 2
distribution-service-api => 3
message-broker-api => 3
statistics-service-api => 3
textanalyzer-workflowoperation => 3
themes-workflowoperation => 3
user-interface-configuration => 3
userdirectory-moodle => 3
videogrid-service-impl => 3
email-template-service-impl => 4
presets => 4
publication-service-api => 4
publication-service-oaipmh-remote => 4
statistics-service-remote => 4
textanalyzer-impl => 4
transcription-service-amberscript => 4
authorization-xacml => 5
composer-service-remote => 5
execute-remote => 5
oaipmh-persistence => 5
scheduler-api => 5
statistics-provider-influx => 5
termination-state-impl => 5
timelinepreviews-workflowoperation => 5
userdirectory-sakai => 5
videoeditor-ffmpeg-impl => 5
waveform-ffmpeg => 5
workflow-condition-parser => 5
workflow-service-remote => 5
crop-ffmpeg => 6
ingest-download-service-impl => 6
workspace-impl => 6
capture-admin-service-impl => 7
userdirectory-brightspace => 7
userdirectory-canvas => 8
videosegmenter-ffmpeg => 8
distribution-service-download => 9
engage-theodul-core => 9
execute-workflowoperation => 9
statistics-service-impl => 9
videoeditor-workflowoperation => 9
sox-impl => 10
waveform-workflowoperation => 10
comments-workflowoperation => 11
cover-image-impl => 11
execute-impl => 11
lti => 12
transcription-service-persistence => 12
workflow-service-api => 12
asset-manager-storage-aws => 13
event-comment => 13
publication-service-configurable => 13
videogrid-workflowoperation => 14
composer-service-api => 15
static-file-service-api => 15
inspection-service-ffmpeg => 16
transcription-service-workflowoperation => 16
urlsigning-verifier-service-impl => 16
runtime-info => 18
series-service-remote => 18
caption-impl => 19
oaipmh => 19
termination-state-aws => 20
fileupload => 21
statistics-export-service-impl => 21
distribution-service-streaming-wowza => 22
live-schedule-impl => 22
urlsigning-common => 22
transcription-service-ibm-watson-impl => 24
workflow-workflowoperation => 24
lti-service-impl => 25
transcription-service-google-speech-impl => 27
publication-service-youtube-v3 => 30
authorization-manager => 31
common-jpa-impl => 33
kernel => 33
mpeg7 => 33
distribution-workflowoperation => 35
smil-impl => 37
distribution-service-aws-s3 => 38
publication-service-oaipmh => 40
annotation-impl => 41
dublincore => 42
asset-manager-api => 46
schema => 46
urlsigning-service-impl => 48
composer-workflowoperation => 55
working-file-repository-service-impl => 55
search-service-impl => 56
userdirectory => 60
series-service-impl => 68
index-service => 73
usertracking-impl => 74
common => 104
workflow-service-impl => 129
serviceregistry => 134
asset-manager-impl => 153
ingest-service-impl => 169
scheduler-impl => 213
composer-ffmpeg => 279
external-api => 314
admin-ui => 501
```
</details>

If the community agrees that this PR should be merged, I would create an issue with all remaining modules in a `- [ ]` list to better track the progress on this.

---

### Your pull request should…

* [x] have a concise title
* [x] [close an accompanying issue](https://help.github.com/en/articles/closing-issues-using-keywords) if one exists
* [x] be against the correct branch (features can only go into develop)
* [x] include migration scripts and documentation, if appropriate
* [x] pass automated tests
* [x] have a clean commit history
* [x] [have proper commit messages (title and body) for all commits](https://medium.com/@steveamaza/e028865e5791)

### CODE REVIEW

**Review by lkiesow — APPROVED** [review]
`admin-ui => 501` :rofl: 

Looks like a reasonable approach to start like this.

**Comment by lkiesow** [comment]
Would this make sense in `r/9.x`?
It's an absolutely safe change and prevents things from breaking due to tests breaking after a forward merge.

**Comment by gregorydlogan** [comment]
+1 for moving this to `r/9.x`.  There is still room for fairly large code changes (or new code) there, so it would be preferable to move it there IMO.

**Comment by LukasKalbertodt** [comment]
I changed the base branch of this PR and rebased accordingly.

**Review by gregorydlogan — APPROVED** [review]
This looks reasonable to me.  I dislike some of the changes, but I also don't see a reasonable way of *not* fixing a couple of them since they're subjective.  Approved from my end.  Will wait for discussion at the dev meeting.

**Pull request merged**
