### PR TITLE
MH-12852 Required fields not indicated in the event details and series details modals

### PR DESCRIPTION
**Pull request by staubesv**
Note that this PR does not address the following related issues:

- [MH-12853 Event details and series details modals suggest that empty required fields are saved](https://opencast.jira.com/browse/MH-12853)

### CODE REVIEW

**Comment by staubesv** [comment]
Hi @lkiesow Thanks for taking the review! I assume that you already have seen that the build of this PR breaks because of the silence detection module (#205)

**Comment by gregorydlogan** [comment]
Merged #205, and did a mergeback.  This should resolve things, hopefully.

**Comment by staubesv** [comment]
Thanks @gregorydlogan! I've merged back r/5.x into this PR. Should build now.

**Comment by staubesv** [comment]
Now also merged back r/5.x with #206

**Pull request merged**
