### PR TITLE
Live scheduler fix issue #2504: query search index as admin 

### LINKED ISSUE #2504: liveevent scheduling loop when updating series metadata
**Describe the bug**
A clear and concise description of what you see:
*IUpdating series metadata (eg. title) in a series with a live event scheduled will cause the liveevent(s) to be republished over and over*

**To Reproduce**
1. Go to AdminUI and create a new series
2. Add  a live event in the series
3. Update series metadata (eg. title)
4. Go to events publication tab and watch live publications being added / see logs in admin and engage
5. Be prepared to stop the opencast service, deleting the event in the adminUI doesn't break the loop (logs for that are attached separately)

**Environment Information**
 - OS: [CentOS 7, CentOS 8.3]
 - Browser [Firefox]
 - Opencast version with minor release [OC 8, OC 9]
 - Capture Agents [pyCA, Extron SMP]
[opencast-2021-04-16-liveschedule.log](https://github.com/opencast/opencast/files/6323312/opencast-2021-04-16-liveschedule.log)
[opencast-2021-04-16-liveschedule-engage-deleteevent.log](https://github.com/opencast/opencast/files/6323313/opencast-2021-04-16-liveschedule-engage-deleteevent.log)
[opencast-2021-04-16-liveschedule-deleteevent.log](https://github.com/opencast/opencast/files/6323314/opencast-2021-04-16-liveschedule-deleteevent.log)
[opencast-2021-04-16-liveschedule-engage.log](https://github.com/opencast/opencast/files/6323315/opencast-2021-04-16-liveschedule-engage.log)
liveevent-publications

Initial topic on users list: 
https://groups.google.com/a/opencast.org/g/users/c/Zc_R42qBCcw

This is my first  bug report, please let me know if I missed anything. I'll be happy to provide further information.
regards
Christoph

### PR DESCRIPTION
**Pull request by rute-santos**
### Your pull request should…

* [x] have a concise title
* [x] [close an accompanying issue](https://help.github.com/en/articles/closing-issues-using-keywords) if one exists
* [x] be against the correct branch (features can only go into develop)
* [ ] include migration scripts and documentation, if appropriate
* [x] pass automated tests
* [x] have a clean commit history
* [x] [have proper commit messages (title and body) for all commits](https://medium.com/@steveamaza/e028865e5791)

### CODE REVIEW

**Comment by mliradelc** [comment]
Hi Rute,
First of all, I have to say thanks to deliver this PR.

I will do the review of this :)

**Comment by mliradelc** [comment]
I reviewed the code and work as it should, now I back ported to 8.x because the bug is also in that version and also solves the problem.

I can make a PR for 8.x, or you can change the target branch to 8.x. What do you prefer?

**Review by mliradelc — APPROVED** [review]
All good!

**Comment by rute-santos** [comment]
What's the normal process when the bug affects more than one version? I can create a duplicate PR for 8.x or rebase this one on 8.x and then it can be merged to both. Please let me know what you prefer. Thanks!

**Comment by mliradelc** [comment]
Normally, when a bug is present in more than one version, you made the PR to the oldest supported version. Then, when it is time to release, the release managers rebase each supported version up to develop.

**Comment by rute-santos** [comment]
Hi @mliradelc ,
I've redirected it to 8.x.
Thanks for reviewing!

**Pull request merged**
