### PR TITLE
MH-13283, Fix Custom CXF Error Handler

### PR DESCRIPTION
**Pull request by lkiesow**
This patch fixes two custom CFX error handlers which would not intercept
Opencast's own Exceptions otherwise and cause an internal server error.

### CODE REVIEW

**Comment by slampunk** [comment]
This patch fixes the issue. Can be merged.

**Comment by smarquard** [comment]
Thanks @lkiesow and @slampunk for the quick fix and review.

**Comment by karendolan** [comment]
@lkiesow and @slampunk is the fix to explicitly override the toResponse() method and the functional version was not doing that?

**Comment by lkiesow** [comment]
@karendolan, my guess is that CXF explicitly checks for the class type and I broke that check when I used the functional variant since the hook then became a generic callable. I did not dig into this in much detail though.

**Comment by karendolan** [comment]
Ah, the toResponse() method *is* the ExceptionMapper API https://javaee.github.io/javaee-spec/javadocs/javax/ws/rs/ext/ExceptionMapper.html. It defaults to  Response.Status.INTERNAL_SERVER_ERROR

**Pull request merged**
