### PR TITLE
MH-13087, Update Runtime UI Libraries

### PR DESCRIPTION
**Pull request by lkiesow**
This pull request updates and cleans out the libraries for the runtime
interface used by all non-admin nodes of Opencast. To make future
updates easier, `npm` is used to manage JavaScript libraries.

### CODE REVIEW

**Comment by staubesv** [comment]
@lkiesow How can I actually test this locally?

**Comment by lkiesow** [comment]
Start up a non-admin node (e.g. a worker) and head to http://localhost:8080

**Comment by staubesv** [comment]
Yep, but what is the easiest way to start a non-admin node?

**Comment by lkiesow** [comment]
```sh
% mvn clean install
% cd build
% tar xf *worker*
% cd *worker*
# Make sure activemq is running
./bin/start-opencast
```

**Review by staubesv — APPROVED** [review]

**Pull request merged**
