### PR TITLE
Support faster playback rates in paella video player

### PR DESCRIPTION
**Pull request by LinqLover**
Depending on your lecturer, 1.5x can really be way to slow.

Please review, this is my first contribution to this repository!

### Your pull request should:

* [x] have a concise title
* ~~[close an accompanying issue](https://help.github.com/en/articles/closing-issues-using-keywords) if one exists~~
* [x] be against the correct branch (features can only go into develop)
* ~~include migration scripts and documentation, if appropriate~~
* [x] pass automated tests
* [x] have a clean commit history
* [x] [have proper commit messages (title and body) for all commits](https://medium.com/@steveamaza/e028865e5791)

### CODE REVIEW

**Comment by lkiesow** [comment]
Hi @LinqLover, thanks for the patch and welcome to the community. We are happy to see you here.

The patch looks good and works as expected although I'm not sure if speed > 2× is really still useful. Do you think people will actually use those?

Could you maybe [submit an ICLA to Apereo Foundation](https://www.apereo.org/licensing/agreements/icla) (I'm assuming you have none filed yet) that gives us a bit of legal protection. Essentially, you are declaring that you cannot make claims to your contributions later on, causing trouble for the project. That's probably not strictly necessary for this kind of patch but itstill makes things easier for us if you don't mind.

Finally, I'm wondering if you want this to go into older versions of Opencast. This would probably also be valid for 9.x at least. The `develop` branch is what will become Opencast 10 around July next year. On the other hand, if you target `r/9.x` that will be released in ~3 weeks.

Finally, feel free if you have any questions.

**Comment by LinqLover** [comment]
> I'm not sure if speed > 2× is really still useful. Do you think people will actually use those?

2.5× can definitively be useful if someone is speaking slowly), 3× was rather intended for fast-forwarding (for instance, you can still watch all slides or screencast activities). Personally, I'd rather like to support as much speed as possible because it does not harm, but it is a pity even if only a single student is getting bored because a video is going on too slow ...

> Could you maybe submit an ICLA to Apereo Foundation (I'm assuming you have none filed yet) that gives us a bit of legal protection.

Done.

> Finally, I'm wondering if you want this to go into older versions of Opencast.

Oh, I did not notice this, thanks for the pointer! What's the backport process for this repository? Should I simply open another PR against the `r/8.x` branch to cherry-pick 997e9fe or would you recommend something else?

**Comment by lkiesow** [comment]
If you are a bit familiar with git, you can just update this branch (e.g. rebase to a release branch and then force-push to your GitHub repo). That will automatically update this pull request. Then hit the edit button at the top -right of this pull request and update the target branch.

If you don't feel comfortable doing that, closing this and just opening a new pull request against the release branch will work just fine.

Finally, if you have trouble, let me know and I can update this.

> 2.5× can definitively be useful…

Fair enough.

**Comment by LinqLover** [comment]
Thank you, I'm trying that. How can I find out as a student which version of opencast my university is using?

**Comment by LinqLover** [comment]
Hm ... What did I do wrong? :-(

**Comment by lkiesow** [comment]
Hi @LinqLover, you probably rebased while including a few too many commits.
I've just rebased this for you, recording what I did:

- https://asciinema.org/a/375081

I've set this to `r/8.x` since `r/7.x` is more or less and of life and while there will be a last release there shouldn't be any changes without a very good reason. I would probably have gone for `r/9.x` but I've set this to `r/8.x` instead since you seem to want it in older releases.

If you are okay with my update, we can merge this.

**Comment by LinqLover** [comment]
Wow, thanks a lot for the extra tutorial! :-) I did not know the interactive option for rebase, this was exactly what I was looking for. The patch looks good to me, ready to merge. :-)

**Review by lkiesow — APPROVED** [review]

**Pull request merged**
