### PR TITLE
MH-12735, Remove Undocumented Operations

### PR DESCRIPTION
**Pull request by lkiesow**
As proposed on list, this pull request removes the following undocumented and seemingly unused workflow operations:

 - capture    
 - coverart    
 - ingest    
 - log-warning          
 - searchindex-remove 
 - watermark

Note that I left out the following two pull requests since @gregorydlogan  promised to document them in time for the 5.x feature freeze:

 - publish-youtube    
 - retract-youtube

### CODE REVIEW

**Review by staubesv — APPROVED** [review]
Still works ;-)

**Comment by gregorydlogan** [comment]
We're removing both the WOH, and the functionality here?  I didn't realiize it was a wholesale removal, but I suppose that makes sense.

**Comment by lkiesow** [comment]
@gregorydlogan, what's the sense in keeping that as dead code? Btb, the functionality of the watermark operation (I guess you are referring to that) is still there since composite also supports adding watermarks

**Comment by gregorydlogan** [comment]
Fair enough.  Not a big deal, it's always in the history, I just figured we were doing the WOHs only.

**Pull request merged**
