### PR TITLE
Replace “Click Here” Links on Documentation Landing Page

### PR DESCRIPTION
**Pull request by lkiesow**
This patch modifies the documentation landing page and…

- Replaces the „click here“ link, which is generally not a good idea to use. For some details, see for example, [Why Your Links Should Never Say “Click Here”](https://uxmovement.com/content/why-your-links-should-never-say-click-here/)
- Adds where webinars will be announced
- Fixes a typo

### Your pull request should…

* [x] have a concise title
* [x] [close an accompanying issue](https://help.github.com/en/articles/closing-issues-using-keywords) if one exists
* [x] [be against the correct branch](https://docs.opencast.org/develop/developer/development-process#acceptance-criteria-for-patches-in-different-versions)
* [x] include migration scripts and documentation, if appropriate
* [x] pass automated tests
* [x] have a clean commit history
* [x] [have proper commit messages (title and body) for all commits](https://medium.com/@steveamaza/e028865e5791)

### CODE REVIEW

**Comment by mliradelc** [comment]
I've never known about the "Don't Click here", but it's a very good tip! Also, the page is more easier to read.

**Comment by ebbertd** [comment]
Looks good to me.

**Review by ebbertd — APPROVED** [review]
Looks good to me.

**Comment by lkiesow** [comment]
Okay, merging…

**Pull request merged**
