### PR TITLE
Check for Apereo CLA

### PR DESCRIPTION
**Pull request by lkiesow**
This patch adds a bot checking if there exists an individual
contributor license agreement filed with Apereo which has the pull
request author's username attached to it.

If we want this, we should check if the GitHub user names of our regular
contributors are filed correctly since we were on Bitbucket when we
started filing them with Apereo.

### Your pull request should…

* [ ] have a concise title
* [ ] [close an accompanying issue](https://help.github.com/en/articles/closing-issues-using-keywords) if one exists
* [ ] be against the correct branch (features can only go into develop)
* [ ] include migration scripts and documentation, if appropriate
* [ ] pass automated tests
* [ ] have a clean commit history
* [ ] [have proper commit messages (title and body) for all commits](https://medium.com/@steveamaza/e028865e5791)

### CODE REVIEW

**Comment by gregorydlogan** [comment]
@turro @mtneug neither of you seem to have ICLAs on file.  Please get those done and put your GitHub username on them so that this filter doesn't complain when you file PRs :)

**Review by gregorydlogan — APPROVED** [review]
Looks good to me.  I can merge it in my next round of reviews.

**Comment by mtneug** [comment]
@gregorydlogan could you check if I now successfully agreed to the ICLA or how would I check?

**Comment by gregorydlogan** [comment]
@mtneug not showing up yet, but I'm unsure how quickly that page updates since it's powered by an Excel spreadsheet.

To check yourself: `pip3 install apereocla && apereocla -g mtneug` should not spit out any errors

**Comment by lkiesow** [comment]
@mtneug, Apereo git your submission but someone has to properly file it. You will get a mail back once that's done. All filed CLAs can be found on http://licensing.apereo.org/

**Comment by lkiesow** [comment]
Adding that kind of information to the comment may make sense. Will do so later. We should also shortly discuss this at the next meeting to nor surprise people.

**Pull request merged**
