### PR TITLE
Add additional s3 operations

### PR DESCRIPTION
**Pull request by mtneug**
This PR adds additional S3 distribution operations:

* Rename existing `publish-aws` und `retract-aws` to `publish-engage-aws` and `retract-engage-aws` to make it clear where they publish to
* Add `retract-partial-aws` (This uses the `engage` channel as well, but there is currently no partial retract for other channels)
* Add `publish-configure-aws`
* Add `retract-configure-aws`

### Your pull request should…

* [x] have a concise title
* [x] [close an accompanying issue](https://help.github.com/en/articles/closing-issues-using-keywords) if one exists
* [x] be against the correct branch (features can only go into develop)
* [x] include migration scripts and documentation, if appropriate
* [x] pass automated tests
* [x] have a clean commit history
* [x] [have proper commit messages (title and body) for all commits](https://medium.com/@steveamaza/e028865e5791)

### CODE REVIEW

**Comment by CGreweling** [comment]
@mtneug Just one question. Is it possible to use the OSGI ``@Reference`` Binding in the Java Class instead of the OSGI-XML here?

**Review by gregorydlogan — CHANGES_REQUESTED** [review]
Concur with @CGreweling, this should use the newer OSGi bits.  Otherwise looks good to me.

**Comment by mtneug** [comment]
@CGreweling, @gregorydlogan: can you tell me how this would be done in this case? I have two OSGi services per class with varying references some even missing.

**Comment by gregorydlogan** [comment]
@mtneug this style: https://github.com/opencast/opencast/blob/develop/modules/capture-admin-service-impl/src/main/java/org/opencastproject/capture/admin/impl/CaptureAgentAdminRoleProviderImpl.java

Edit: The above is not what the issue is, the issue is that multiple instances of the same class need to use different dependencies and we're not sure how to do that with the annotations.

**Comment by gregorydlogan** [comment]
@mtneug aside from the conflicts I'd say this is ready to go in.

**Review by gregorydlogan — APPROVED** [review]

**Comment by mtneug** [comment]
@gregorydlogan: conflicts are fixed and since the new workflows don't use S3 they don't need to be updated.

**Pull request merged**
