### PR TITLE
Update karaf version to 4.4.6

### PR DESCRIPTION
**Pull request by geichelberger**
This updates Karaf from version 4.4.4 to version 4.4.6 and updates the following dependencies:

- commons-compress 1.26.1
- commons-lang3 3.14.0
- commons-logging 1.3.1

* [ ] have a concise title
* [ ] [close an accompanying issue](https://docs.opencast.org/develop/developer/#participate/development-process/#automatically-closing-issues-when-a-pr-is-merged) if one exists
* [ ] [be against the correct branch](https://docs.opencast.org/develop/developer/development-process#acceptance-criteria-for-patches-in-different-versions)
* [ ] include migration scripts and documentation, if appropriate
* [ ] pass automated tests
* [ ] have a clean commit history
* [ ] [have proper commit messages (title and body) for all commits](https://medium.com/@steveamaza/e028865e5791)

### CODE REVIEW

**Review by lkiesow — APPROVED** [review]
Seems to work as expected.
Any reason to update `r/16.x` and not just `develop`?

**Comment by gregorydlogan** [comment]
Regardless of whether this makes 16, it should definitely go into develop sooner than later since this may affect the Spring upgrade.

**Comment by geichelberger** [comment]
>  Any reason to update r/16.x and not just develop?
Developer Joy, because the next version, 4.4.7, will contain the EclisepLink upgrade, allowing developers to switch between branches without funny stack traces while using Java 21.

Karaf 4.4.5 fixes a CVE regarding jetty and http2; the feature is not enabled by default, and maybe no opencast adopter has enabled it.

**Comment by lkiesow** [comment]
Fine. I'll merge it. In general, I always think that this is the type of patch that can easily break something we don't notice since far less testing is going to happen before this ends up in a release and this means that adopters which just want a minor update to fix some bugs are effected.

**Pull request merged**
