### PR TITLE
MH-13368, Added color property to waveform operation handler

### PR DESCRIPTION
**Pull request by tyfranck**
color property added to waveform operation handler

### CODE REVIEW

**Review by lkiesow — CHANGES_REQUESTED** [review]
While I haven't tested this in action, a first glance at the code looks good except for the broken JavaDoc (see Travis CI test failure). Can you fix that?

**Comment by smarquard** [comment]
What is the range of possible values for the color property? There should be some reference to that in the WOH doc.

**Comment by lkiesow** [comment]
Valid options should be valid options to the color option of FFmpeg's [showwavespic](https://ffmpeg.org/ffmpeg-filters.html#showwavespic) filter

**Comment by tyfranck** [comment]
Comments addressed, thanks guys

**Pull request merged**
