### PR TITLE
Fix race condition when loading workflow definitions

### PR DESCRIPTION
**Pull request by mtneug**
There is a race between the OrganizationDirectoryService and WorkflowDefinitionScanner: workflow definitions that set the organization field must be loaded after the organization is loaded. If the org is not loaded beforehand the workflow definition would error out and not be available. This registers an organization listener. If a new organization is loaded previously error out workflow definitions are tried to be loaded in again.

### Your pull request should…

* [ ] have a concise title
* [ ] [close an accompanying issue](https://help.github.com/en/articles/closing-issues-using-keywords) if one exists
* [ ] [be against the correct branch](https://docs.opencast.org/develop/developer/development-process#acceptance-criteria-for-patches-in-different-versions)
* [ ] include migration scripts and documentation, if appropriate
* [ ] pass automated tests
* [ ] have a clean commit history
* [ ] [have proper commit messages (title and body) for all commits](https://medium.com/@steveamaza/e028865e5791)

### CODE REVIEW

**Comment by geichelberger** [comment]
Wouldn't it be easier to remove the exception which causes the problem?

https://github.com/opencast/opencast/blob/89909d2eff63587599253c2242351295a2404952/modules/workflow-service-impl/src/main/java/org/opencastproject/workflow/impl/WorkflowDefinitionScanner.java#L211

A workflow with an organization that does not (yet) exist will be installed without effect. This function `getAvailableWorkflowDefinitions` can only return workflows for existing organizations. If there is a workflow with a faulty organization, nothing happens. 
If the organization is registered, later on, everything is fine. The function will return it.

**Comment by Arnei** [comment]
I would prefer going with Matthias solution and keeping the exception. In case you made a mistake in the organization field (e.g. due to a typo), it gives you quick feedback. And if the faulty organization is intentional (because you know it will be added later on), you can just ignore the exception.

**Comment by geichelberger** [comment]
> I would prefer going with Matthias solution and keeping the exception. In case you made a mistake in the organization field (e.g. due to a typo), it gives you quick feedback. And if the faulty organization is intentional (because you know it will be added later on), you can just ignore the exception.

You can still log an error that the workflow organization does not exist, which would have the same effect.

**Comment by gregorydlogan** [comment]
I would not expect to be able to register workflow definitions for an organization that does not exist, so @mtneug's approach seems like a better option.  There's nothing wrong with the other way, but it's inconsistent with the rest of Opencast's approach to things.

**Pull request merged**
