### PR TITLE
MH-13147 (6.x): OptimisticLockException in ServiceRegistry dispatchJob

### PR DESCRIPTION
**Pull request by rute-santos**

### CODE REVIEW

**Comment by lkiesow** [comment]
@rute-santos, can you please add a description to this pull request and explain what you are trying to do here? The title only gives you a vague idea and the commit description does not contain a lot of information as well.

And this is modifying the database, isn't it? That would cause massive problems within a maintenance update. Please redirect this to `develop` for Opencast 7. Additionally, this is missing a database upgrade script and the necessary modification to the database set-up script. Can you add that?

**Comment by smarquard** [comment]
@lkiesow, this is a 6.x version of #664 - see discussion there.

**Comment by smarquard** [comment]
We have this code running in our 6.x production system and hasn't caused any issues so far.

**Comment by smarquard** [comment]
Hm, apologies, I merged the wrong PR here...

**Comment by smarquard** [comment]
This looks like a clean change, and applies to 6.x without requiring any database modifications. The db conversions will get handled in PR #664.

We have been running this at UCT in production for a few days, and have seen no further OptimisticLockExceptions and also no regressions in workflow or job handling.

**Pull request merged**
