### PR TITLE
Update Studio from 2020-06-25 to 2020-09-14

### PR DESCRIPTION
**Pull request by LukasKalbertodt**
The Studio update contains a **breaking change** regarding the Studio configuration.
- The configuration format is now TOML and no longer JSON (https://github.com/elan-ev/opencast-studio/pull/657)
- Change ACL template view (https://github.com/elan-ev/opencast-studio/pull/673)
  - This is relevant to you if you are using the`userName`, `userRole`, `ltiCourseId` or `default*Roles` variables in your ACL templates. Those variables have been removed from the template view.

Apart from that, see the commit messages for more details.

Someone who knows about the Admin-UI code should review to make sure my changes make sense.

### Your pull request should…

* [x] have a concise title
* [ ] [close an accompanying issue](https://help.github.com/en/articles/closing-issues-using-keywords) if one exists
* [x] be against the correct branch (features can only go into develop)
* [x] include migration scripts and documentation, if appropriate
* [ ] pass automated testing
* [ ] have a clean commit history
* [x] have proper commit messages (title and body) for all commits
* [x] have appropriate tags applied

### CODE REVIEW

**Comment by LukasKalbertodt** [comment]
I pushed another commit that updates to Studio 2020-09-14. Changelog:

> ### Fixed
> - **Security**: Studio does not allow arbitrary `return.target` URLs anymore. Instead, there is a whitelist that can only be specified in `settings.toml`. Only the domain studio is deployed on and the domains in that whitelist are allowed as `return.target`.
> - Settings given via the `config=` parameter do not allow parsing during validation anymore. That means that `loginProvided = "true"` will not work anymore. It's highly unlikely someone actually used it that way.
>
> ### Changed
> - Slightly improve English translation strings

**Comment by JulianKniephoff** [comment]
I'ma go ahead and claim this for Review Friday(TM), since I really want to see this go in for Innsbruck.

**Comment by JulianKniephoff** [comment]
Nevermind, I'm not allowed to merge, yet. :( Will still review, of course, if no one beats me to it.

**Review by JulianKniephoff — APPROVED** [review]
I just built this and tested some basic things. Most of the new features already went through a more thorough review over at https://github.com/elan-ev/opencast-studio. A few of those reviews were even done by me. :D

Also, this already runs in production in Innsbruck, for example, and they successfully use some of the new features as well.

So from my point of view, this can safely go in, functionality-wise. But as I said, I'm not allowed to merge it yet. @mliradelc voiced concerns (in IRC) about the lack of documentation about the breaking changes in the upgrade docs. Maybe @LukasKalbertodt could add something there?

On the other hand, I remember a somewhat big discussion about whether or not config changes (be it breaking ones or not) need to be listed in the upgrade guide. I personally would say that if you do your due diligence and just diff the entire config you will notice anyway.

**Comment by LukasKalbertodt** [comment]
I didn't know PRs are expected to adjust upgrade docs/release announcements, too. I assumed release docs are written by release managers at some point by looking through all the PRs. But I can of course add some information to the docs, if that's what everyone wants.

**Comment by lkiesow** [comment]
If I remember the discussion correctly some were all for PRs updating that, others were strictly against it.
Conclusion: Do what you like.

And re the what to list, I want only important changes which really need attention in there. Definitely not every small change ;-)

**Comment by mliradelc** [comment]
@LukasKalbertodt Here you can put the notice: https://docs.opencast.org/develop/admin/#upgrade/#configuration-changes
 
It's ok if you make another PR before the launch with that warning. :smiley:

**Comment by mliradelc** [comment]
@LukasKalbertodt I forgot, can you squash your commits?

With that, we are ready to merge

**Comment by JulianKniephoff** [comment]
@mliradelc you can do that yourself by clicking on the little arrow next to the merge button and selecting "Squash and merge". 😉

**Pull request merged**
