### PR TITLE
Replace Deprecated Code

### PR DESCRIPTION
**Pull request by lkiesow**
Mini patch. Replace deprecated `PathSupport::concat`.

### Your pull request should…

* [x] have a concise title
* [x] [close an accompanying issue](https://help.github.com/en/articles/closing-issues-using-keywords) if one exists
* [x] [be against the correct branch](https://docs.opencast.org/develop/developer/development-process#acceptance-criteria-for-patches-in-different-versions)
* [x] include migration scripts and documentation, if appropriate
* [x] pass automated tests
* [x] have a clean commit history
* [x] [have proper commit messages (title and body) for all commits](https://medium.com/@steveamaza/e028865e5791)

### CODE REVIEW

**Review by geichelberger — APPROVED** [review]
LGTM

**Comment by lkiesow** [comment]
@geichelberger, since you now can, do you want to merge this?

**Comment by geichelberger** [comment]
Are there any rules when merging a PR into develop? I could not find something in the dev docs.

**Comment by lkiesow** [comment]
Not really. Most limitations are targeted a release branches. To quote from our developer docs:

> ### Acceptance Criteria for Patches in Different Versions [🔗](https://docs.opencast.org/develop/developer/development-process/#acceptance-criteria-for-patches-in-different-versions)
>
> Updates between minor versions should be as smooth as possible and should usually not need manual intervention. That is why patches may only be accepted into releases branches (`r/?.x`) if they meet the following criteria:
>
> - Patches must not modify existing database tables
> - Patches must not modify the indexes or otherwise cause re-indexing
> - Patches must not require a different ActiveMQ configuration
> - Patches must not modify existing translation keys
> - Patches must work with the same configuration within a major version
>
> Patches which do not meet these criteria should target the branch `develop` to become part of the next major version.
>
> To determine the acceptance of patches, all pull requests will be discussed in the technical meeting. This protects against inclusion of controversial changes with no broader consent among committers.

So, this must have been in the technical meeting (it was) and someone needed to review this (you did). That's it.  Other than that, someone would have had to actively say something against this patch for it to not be allowed.

**Pull request merged**
