### PR TITLE
Annoy adopters who haven't registered

### PR DESCRIPTION
**Pull request by gregorydlogan**
This pull request makes a lack of up-to-date registration annoying, by raising an error in the admin UI service monitor bell.  Also added a missing rest doc in the same endpoint class.

Pull request now includes #4320 

### Your pull request should…

* [x] have a concise title
* [ ] ~[close an accompanying issue](https://help.github.com/en/articles/closing-issues-using-keywords) if one exists~
* [x] [be against the correct branch](https://docs.opencast.org/develop/developer/development-process#acceptance-criteria-for-patches-in-different-versions)
* [ ] ~include migration scripts and documentation, if appropriate~
* [x] pass automated tests
* [x] have a clean commit history
* [x] [have proper commit messages (title and body) for all commits](https://medium.com/@steveamaza/e028865e5791)

### CODE REVIEW

**Comment by lkiesow** [comment]
Can I still decide not to share my information and get rid of the warning?

**Comment by gregorydlogan** [comment]
There isn't a way to record that currently. Guess that should be added.

**Comment by lkiesow** [comment]
The problem I see with this is, that, for example, it may be hard in some cases to get the okay to officially put your organization on the Opencast map. Or there could be several other reasons that you don't want to register.

In these cases, Opencast will now constantly tell you that something is wrong. That's not really true.

In general, the registration form already pops up every time an admin opens the admin interface, unless you tell Opencast you don't want to register. That's why I'm not really sure about this.

If we want more reminders, could it be better for the registration form to pop up again, maybe after each update? E.g. storing that the user hid this when running 11.1, but I'm now running 12.3 → Let's show it again.

**Comment by gregorydlogan** [comment]
Error has been demoted to a warning, so now the bell isn't constantly red.  Same logic as having an out-of-date Opencast install.  Clicking on the warning now opens the modal as well.  Regarding repeated popups, the adopter isn't marked as registered until they actually agree to send things now, so the popup will continue to appear at 30-day intervals until that happens.  I feel like that's close enough to on-new-release that we don't need any additional logic there?

**Comment by gregorydlogan** [comment]
It occurs to me that one thing that's *not* being checked here is whether the communication with the registration server is actually succeeding. I'll add that soon.

**Comment by gregorydlogan** [comment]
Done.  Requested @lkiesow review since he was looking at #4320, which was superseded by this one.

**Comment by gregorydlogan** [comment]
Merging this so that it gets into the next 12.x release.

**Pull request merged**
