### PR TITLE
Remove references to removed modules

### PR DESCRIPTION
**Pull request by lkiesow**
This patch removes a few references to modules removed in pull request ##1887

### Your pull request should…

* [ ] have a concise title
* [ ] [close an accompanying issue](https://help.github.com/en/articles/closing-issues-using-keywords) if one exists
* [ ] be against the correct branch (features can only go into develop)
* [x] include migration scripts and documentation, if appropriate
* [x] pass automated testing
* [x] have a clean commit history
* [x] have proper commit messages (title and body) for all commits
* [x] have appropriate tags applied

### CODE REVIEW

**Comment by gregorydlogan** [comment]
I see a few bits in the fontawesome bits:

```
docs/guides/developer/docs/css/font-awesome.min.css
modules/admin-ui/src/main/webapp/styles/base/fontawesome/_icons.scss
modules/admin-ui/src/main/webapp/styles/base/fontawesome/_variables.scss
```

I'm not hugely worried about it, but is that something we can fix?

**Comment by mtneug** [comment]
@gregorydlogan is this related to another PR? I can't make sense of your comment 🙈.

**Review by mtneug — APPROVED** [review]

**Comment by gregorydlogan** [comment]
@mtneug When you grep the codebase for `openid`, those three files still reference it.  SInce it's a library let's just leave it alone.

**Comment by lkiesow** [comment]
Okay, that's just that FontAwesome has an OpenID icon:
https://fontawesome.com/icons/openid?style=brands

**Pull request merged**
