### PR TITLE
Removed Solr from Series Service

### PR DESCRIPTION
**Pull request by Arnei**
Removes all Solr functionality from the series service. Functions that relied on the solr index were either removed or now query the database directly.

- Moved the series filter query endpoint to the external api, while trying to preserve as much functionality as possible (for example, there is no pagination, so instead an offset variable is offered)

This PR can wait until Opencast 12, it is mainly open for reviewing purposes.

Work sponsored by our generous Crowdfunding initiatives!

### Your pull request should…

* [x] have a concise title
* [ ] [close an accompanying issue](https://help.github.com/en/articles/closing-issues-using-keywords) if one exists
* [x] [be against the correct branch](https://docs.opencast.org/develop/developer/development-process#acceptance-criteria-for-patches-in-different-versions)
* [ ] include migration scripts and documentation, if appropriate
* [ ] pass automated tests
* [ ] have a clean commit history
* [ ] [have proper commit messages (title and body) for all commits](https://medium.com/@steveamaza/e028865e5791)

### CODE REVIEW

**Comment by mtneug** [comment]
Do you expect/observe performance degradations? Should this maybe instead query Elastic-/OpenSearch (though I do expect the DB to scale quite good for normal queries)?

**Comment by Arnei** [comment]
I did not observe performance degradations, but I also only tested this on my local machine, where database and server run on the same hardware. However, the DB queries are quite simple, so I also expect this to scale well.

Lars and I had discussed that we did not want to query the Elastic-/OpenSearch, in order to get away from the currently somewhat cyclic dependency where the External API and the Series Service are trying to get information from each other.

**Review by mliradelc — CHANGES_REQUESTED** [review]
Thanks for the PRs 😄 

Because of the changes in the pagination feature in the api, A comment in the documentation and in the changelog is required

**Comment by mliradelc** [comment]
I will Merge it, but this needs the notes to be added before the release in one month ;)

**Comment by Arnei** [comment]
Sorry for the late response @mliradelc , we discussed in the technical meeting that it would be fine for this PR to wait for Opencast 12, but I forgot you weren't there. I was gonna add the notes after the branch cut, especially since Matthias also mentioned that this changes the External API and would therefore need a new API version (*sigh*). I think it would be better to revert the merge if can still reasonably do so?

**Comment by mliradelc** [comment]
Hi @Arnei  thanks for your comment, of course we can revert the commit 🙂 , ~~I will do that after the tech meeting of today and mark it as a draft. Feel free to undraftit  when you feel that is ready for review.~~

After the meeting was decided to hold the revert because more info is needed.

Update: After conversation with @Arnei this PR will be reverted

**Pull request merged**
