### PR TITLE
Remove Dead Feedback Url

### PR DESCRIPTION
**Pull request by gregorydlogan**
This PR removes an unused configuration key.  This has been dead for a _very_ long time, and does nothing anyway.

### Your pull request should…

* [x] have a concise title
* [ ] ~[close an accompanying issue](https://docs.opencast.org/develop/developer/#participate/development-process/#automatically-closing-issues-when-a-pr-is-merged) if one exists~
* [x] [be against the correct branch](https://docs.opencast.org/develop/developer/development-process#acceptance-criteria-for-patches-in-different-versions)
* [ ] ~include migration scripts and documentation, if appropriate~
* [x] pass automated tests
* [x] have a clean commit history
* [x] [have proper commit messages (title and body) for all commits](https://medium.com/@steveamaza/e028865e5791)

### CODE REVIEW

**Comment by lkiesow** [comment]
This can still be used in the old admin interface. Did you maybe confuse this with the old ping back URL that was configured in the `config.properties` in “the good old days”? Still, this can go with the old admin interface. So, target this towards `develop`?

**Comment by gregorydlogan** [comment]
Sure, base changed and rebased.

Edit: Are we dropping the old UI with OC17?  I can't remember.  If this could still in theory be used by that UI maybe this should be on hold until that removal happens.

**Comment by lkiesow** [comment]
This is also still in the new admin interface. See:
https://github.com/opencast/opencast-admin-interface/blob/5a92fdedde971d5b056ca04924451fce464d7b18/src/components/Footer.tsx#L17

I don't mind removing this, but then it should also be removed in the admin interface.

**Comment by gregorydlogan** [comment]
Closing this in favour of #6095.  People might want this, so just removing JIRA references is better.

**Pull request closed without merging**
