### PR TITLE
MH-12656 Updates to Theodul Matomo (formerly Piwik) Plugin

### PR DESCRIPTION
**Pull request by rrolf**
Changed the Piwik name to Matomo, as the project was renamed. Added client (usually label for player) as a 5th custom variable to logged data in Matomo. Changed how actions are tracked, as identical events that are send multiple times (usually for security reasons) will only be tracked once.

### CODE REVIEW

**Review by gregorydlogan — APPROVED** [review]
The changes to the non-en-US translations are probably going to be lost to updates from Crowdin, but the translations look right so I'm going to allow it :)

**Review by gregorydlogan — CHANGES_REQUESTED** [review]
Missed the docs at docs/guides/admin/docs/modules/player.piwik.tracking.md, both in terms of filename and content!

**Comment by rrolf** [comment]
I updated the documentation. The one remaining "Piwik Javascript" is intentional, as this has not been renamed by their developers yet.

**Comment by rrolf** [comment]
PR #162 introduces a small enhancement to this PR

**Review by gregorydlogan — APPROVED** [review]

**Pull request merged**
