### PR TITLE
MH-12739 Transcription Service updated to support Paella 

### PR DESCRIPTION
**Pull request by rute-santos**
Changes:
* Dfxp captions are now attachments.
* Captions are flavored as 'captions/<format>+<language>' to work with Paella. 
* Documentation updated.

Detailed discussion in PR #98.

### CODE REVIEW

**Comment by gregorydlogan** [comment]
So to test this we would need to set up a Watson account, correct?

**Comment by rute-santos** [comment]
Hi @gregorydlogan, yes, but I think I can create an instance for you to test. i will email you the details.

**Comment by gregorydlogan** [comment]
I have verified that transcription works as expected - the normal demo media actually works surprisingly well considering the audio quality.  Paella is not included in my current build however, so I'm unable to merge this just yet.  Will look at this tomorrow.

**Comment by gregorydlogan** [comment]
My only major complaint here is that the workflow which submits the transcription request completes (which is good), but there's no indication that things are still processing on Watson's end (which is bad).  I don't, however, see a clear way to do this right now - what we need is a separate tab at the Events & Series tab which handles async jobs, but that's waay outside of the scope of this PR.  Will accept once I've verified that Paella's support is working, but I can see that the transcription itself is working.

**Comment by gregorydlogan** [comment]
Subtitles are available in both players, approved!

**Pull request merged**
