### PR TITLE
Better documentation for AAI DynamicLoginHandler

### LINKED ISSUE #1999: Documentation of AAI DynamicLoginHandler must be improved
**Describe the bug**
The documentation of the possible configuration at https://docs.opencast.org/r/9.x/admin/#configuration/security.aai/#dynamic-login-handler-configuration is very minimal. This must be improved to help adopters understanding and using the AAI loginhandler

### PR DESCRIPTION
**Pull request by hsssystems**
This PR should fix #1999

### CODE REVIEW

**Comment by hsssystems** [comment]
What is wrong? Online linter https://dlaa.me/markdownlint/ can't find any problems anymore...

**Comment by gregorydlogan** [comment]
@hsssystems we're also enforcing a trailing spaces check, which is what's failing: https://travis-ci.com/github/opencast/opencast/jobs/407245563#L254

**Comment by gregorydlogan** [comment]
@hsssystems the security XML is also checked for trailing spaces, so still failing.

**Review by gregorydlogan — CHANGES_REQUESTED** [review]
Somehow, and I'm not entirely sure how, the security xml changes break startup:

```
2020-11-02T16:12:17,218 | ERROR | (SpringSecurityConfigurationArtifactInstaller:102) - Unable to refresh spring security configuration file /home/greg/opencast/upstream/build/opencast-dist-develop-9-SNAPSHOT/etc
/security/mh_default_org.xml: {}
org.springframework.beans.factory.xml.XmlBeanDefinitionStoreException: Line 775 in XML document from OSGi resource[file:/home/greg/opencast/upstream/build/opencast-dist-develop-9-SNAPSHOT/etc/security/mh_default
_org.xml|bnd.id=125|bnd.sym=opencast-kernel] is invalid; nested exception is org.xml.sax.SAXParseException; lineNumber: 775; columnNumber: 9; cvc-complex-type.2.3: Element 'beans' cannot have character [children
], because the type's content type is element-only.
        at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.doLoadBeanDefinitions(XmlBeanDefinitionReader.java:396) ~[!/:3.1.4.RELEASE]
        at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.loadBeanDefinitions(XmlBeanDefinitionReader.java:334) ~[!/:3.1.4.RELEASE]
        at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.loadBeanDefinitions(XmlBeanDefinitionReader.java:302) ~[!/:3.1.4.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanDefinitionReader.loadBeanDefinitions(AbstractBeanDefinitionReader.java:174) ~[!/:3.1.4.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanDefinitionReader.loadBeanDefinitions(AbstractBeanDefinitionReader.java:209) ~[!/:3.1.4.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanDefinitionReader.loadBeanDefinitions(AbstractBeanDefinitionReader.java:180) ~[!/:3.1.4.RELEASE]
        at org.springframework.osgi.context.support.OsgiBundleXmlApplicationContext.loadBeanDefinitions(OsgiBundleXmlApplicationContext.java:164) ~[?:?]
        at org.springframework.osgi.context.support.OsgiBundleXmlApplicationContext.loadBeanDefinitions(OsgiBundleXmlApplicationContext.java:136) ~[?:?]
        at org.springframework.context.support.AbstractRefreshableApplicationContext.refreshBeanFactory(AbstractRefreshableApplicationContext.java:131) ~[!/:3.1.4.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.obtainFreshBeanFactory(AbstractApplicationContext.java:530) ~[!/:3.1.4.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:444) ~[!/:3.1.4.RELEASE]
        at org.springframework.osgi.context.support.AbstractDelegatedExecutionApplicationContext.access$301(AbstractDelegatedExecutionApplicationContext.java:69) ~[!/:1.2.1]
        at org.springframework.osgi.context.support.AbstractDelegatedExecutionApplicationContext$1.run(AbstractDelegatedExecutionApplicationContext.java:186) ~[!/:1.2.1]
        at org.springframework.osgi.util.internal.PrivilegedUtils.executeWithCustomTCCL(PrivilegedUtils.java:85) ~[!/:1.2.1]
        at org.springframework.osgi.context.support.AbstractDelegatedExecutionApplicationContext.normalRefresh(AbstractDelegatedExecutionApplicationContext.java:182) ~[!/:1.2.1]
        at org.springframework.osgi.context.support.AbstractDelegatedExecutionApplicationContext$NoDependenciesWaitRefreshExecutor.refresh(AbstractDelegatedExecutionApplicationContext.java:89) ~[!/:1.2.1]
        at org.springframework.osgi.context.support.AbstractDelegatedExecutionApplicationContext.refresh(AbstractDelegatedExecutionApplicationContext.java:175) ~[!/:1.2.1]
        at org.opencastproject.kernel.security.SpringSecurityConfigurationArtifactInstaller.install(SpringSecurityConfigurationArtifactInstaller.java:100) [!/:?]
        at org.apache.felix.fileinstall.internal.DirectoryWatcher.install(DirectoryWatcher.java:950) [!/:3.6.6]
        at org.apache.felix.fileinstall.internal.DirectoryWatcher.install(DirectoryWatcher.java:884) [!/:3.6.6]
        at org.apache.felix.fileinstall.internal.DirectoryWatcher.doProcess(DirectoryWatcher.java:489) [!/:3.6.6]
        at org.apache.felix.fileinstall.internal.DirectoryWatcher.process(DirectoryWatcher.java:365) [!/:3.6.6]
        at org.apache.felix.fileinstall.internal.DirectoryWatcher.run(DirectoryWatcher.java:316) [!/:3.6.6]
Caused by: org.xml.sax.SAXParseException: cvc-complex-type.2.3: Element 'beans' cannot have character [children], because the type's content type is element-only.
        at org.apache.xerces.util.ErrorHandlerWrapper.createSAXParseException(Unknown Source) ~[org.apache.servicemix.bundles.xerces-2.12.0_1.jar:?]
        at org.apache.xerces.util.ErrorHandlerWrapper.error(Unknown Source) ~[org.apache.servicemix.bundles.xerces-2.12.0_1.jar:?]
        at org.apache.xerces.impl.XMLErrorReporter.reportError(Unknown Source) ~[org.apache.servicemix.bundles.xerces-2.12.0_1.jar:?]
        at org.apache.xerces.impl.XMLErrorReporter.reportError(Unknown Source) ~[org.apache.servicemix.bundles.xerces-2.12.0_1.jar:?]
        at org.apache.xerces.impl.XMLErrorReporter.reportError(Unknown Source) ~[org.apache.servicemix.bundles.xerces-2.12.0_1.jar:?]
        at org.apache.xerces.impl.xs.XMLSchemaValidator$XSIErrorReporter.reportError(Unknown Source) ~[org.apache.servicemix.bundles.xerces-2.12.0_1.jar:?]
        at org.apache.xerces.impl.xs.XMLSchemaValidator.reportSchemaError(Unknown Source) ~[org.apache.servicemix.bundles.xerces-2.12.0_1.jar:?]
        at org.apache.xerces.impl.xs.XMLSchemaValidator.elementLocallyValidComplexType(Unknown Source) ~[org.apache.servicemix.bundles.xerces-2.12.0_1.jar:?]
        at org.apache.xerces.impl.xs.XMLSchemaValidator.elementLocallyValidType(Unknown Source) ~[org.apache.servicemix.bundles.xerces-2.12.0_1.jar:?]
        at org.apache.xerces.impl.xs.XMLSchemaValidator.processElementContent(Unknown Source) ~[org.apache.servicemix.bundles.xerces-2.12.0_1.jar:?]
        at org.apache.xerces.impl.xs.XMLSchemaValidator.handleEndElement(Unknown Source) ~[org.apache.servicemix.bundles.xerces-2.12.0_1.jar:?]
        at org.apache.xerces.impl.xs.XMLSchemaValidator.endElement(Unknown Source) ~[org.apache.servicemix.bundles.xerces-2.12.0_1.jar:?]
        at org.apache.xerces.impl.XMLNSDocumentScannerImpl.scanEndElement(Unknown Source) ~[org.apache.servicemix.bundles.xerces-2.12.0_1.jar:?]
        at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContentDispatcher.dispatch(Unknown Source) ~[org.apache.servicemix.bundles.xerces-2.12.0_1.jar:?]
        at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source) ~[org.apache.servicemix.bundles.xerces-2.12.0_1.jar:?]
        at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source) ~[org.apache.servicemix.bundles.xerces-2.12.0_1.jar:?]
        at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source) ~[org.apache.servicemix.bundles.xerces-2.12.0_1.jar:?]
        at org.apache.xerces.parsers.XMLParser.parse(Unknown Source) ~[org.apache.servicemix.bundles.xerces-2.12.0_1.jar:?]
        at org.apache.xerces.parsers.DOMParser.parse(Unknown Source) ~[org.apache.servicemix.bundles.xerces-2.12.0_1.jar:?]
        at org.apache.xerces.jaxp.DocumentBuilderImpl.parse(Unknown Source) ~[org.apache.servicemix.bundles.xerces-2.12.0_1.jar:?]
        at org.springframework.beans.factory.xml.DefaultDocumentLoader.loadDocument(DefaultDocumentLoader.java:75) ~[!/:3.1.4.RELEASE]
        at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.doLoadBeanDefinitions(XmlBeanDefinitionReader.java:388) ~[!/:3.1.4.RELEASE]
        ... 22 more
```

**Comment by hsssystems** [comment]
Hi Greg,

sorry for that typo, there was an `-->` that my editor did not show as error or comment. :-(

**Pull request merged**
