### PR TITLE
MH-12718, Animate Service

### PR DESCRIPTION
**Pull request by lkiesow**
This patch adds an Opencast animate service which, by using synfig
[https://synfig.org] for rendering, can be used to automatically
generate custom animated video sequences which use Opencast metadata
like the author's name or the event's title.
    
This is useful, for example, to automatically generate animated intro
sequences to ensure having a homogeneous corporate design for all video
recordings.

For an introduction, please watch my talk at the Opencast summit in Vienna.

### CODE REVIEW

**Comment by lkiesow** [comment]
Unfortunately, it seems like Travis ships a broken version of synfig. I updated the configuration to include a known working version instead. Now the builds are passing and all tests are run.

**Review by staubesv — CHANGES_REQUESTED** [review]
Hi @lkiesow, this PR seems to currently break Opencast:

2018-02-27 13:07:46,631 | ERROR | (BootFeaturesInstaller:126) - Error installing boot features
org.osgi.service.resolver.ResolutionException: Unable to resolve root: missing requirement [root] osgi.identity; osgi.identity=opencast-allinone; type=karaf.feature; version="[0,0.0.0]"; filter:="(&(osgi.identity=opencast-allinone)(type=karaf.feature)(version>=0.0.0)(version<=0.0.0))" [caused by: Unable to resolve opencast-allinone/0.0.0: missing requirement [opencast-allinone/0.0.0] osgi.identity; osgi.identity=opencast-animate-impl; type=osgi.bundle; version="[5.0.0.SNAPSHOT,5.0.0.SNAPSHOT]"; resolution:=mandatory [caused by: Unable to resolve opencast-animate-impl/5.0.0.SNAPSHOT: missing requirement [opencast-animate-impl/5.0.0.SNAPSHOT] osgi.wiring.package; filter:="(&(osgi.wiring.package=javax.ws.rs)(version>=1.1.0)(!(version>=2.0.0)))"]]
	at org.apache.felix.resolver.ResolutionError.toException(ResolutionError.java:42)[6:org.apache.karaf.features.core:4.0.9]
	at org.apache.felix.resolver.ResolverImpl.doResolve(ResolverImpl.java:389)[6:org.apache.karaf.features.core:4.0.9]
	at org.apache.felix.resolver.ResolverImpl.resolve(ResolverImpl.java:375)[6:org.apache.karaf.features.core:4.0.9]
	at org.apache.felix.resolver.ResolverImpl.resolve(ResolverImpl.java:347)[6:org.apache.karaf.features.core:4.0.9]
	at org.apache.karaf.features.internal.region.SubsystemResolver.resolve(SubsystemResolver.java:216)[6:org.apache.karaf.features.core:4.0.9]
	at org.apache.karaf.features.internal.service.Deployer.deploy(Deployer.java:263)[6:org.apache.karaf.features.core:4.0.9]
	at org.apache.karaf.features.internal.service.FeaturesServiceImpl.doProvision(FeaturesServiceImpl.java:1176)[6:org.apache.karaf.features.core:4.0.9]
	at org.apache.karaf.features.internal.service.FeaturesServiceImpl$1.call(FeaturesServiceImpl.java:1074)[6:org.apache.karaf.features.core:4.0.9]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)[:1.8.0_161]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)[:1.8.0_161]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)[:1.8.0_161]
	at java.lang.Thread.run(Thread.java:748)[:1.8.0_161]

**Comment by staubesv** [comment]
... probably because of https://github.com/opencast/opencast/pull/83

**Comment by lkiesow** [comment]
This should now work again despite the java8 patch

**Comment by staubesv** [comment]
@lkiesow Please note that this PR currently has conflicts.

**Comment by lkiesow** [comment]
Fixed the merge conflicts

**Review by staubesv — APPROVED** [review]

**Pull request merged**
