### PR TITLE
MH-13447 && MH-13425 - Feeds-Tab / adds a new tab in series properties.

### PR DESCRIPTION
**Pull request by ek926m**
I got some errors due to very old branches, I decided to create a new PR from a current upstream.

related to #845 #912 

In this pullrequest I do add a feed tab to the series modal window, the new links in the tab are clickable and they guide you to the atom/rss xml. To achieve this I had to add the feed function to the backend and to adjust the configuration file in etc/feeds/series.properties.

(see an example image below this comment)

### CODE REVIEW

**Comment by ek926m** [comment]
@gregorydlogan pls look at this PR #1050, this is a updated one #845 and #912

**Comment by ek926m** [comment]
Screenshot from 2019-09-09 14-48-47

**Comment by lkiesow** [comment]
@ek926m, can you

- [ ] Rebase your commits and quash it into one commit with a [proper git commit message](https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53)
- [ ] Add a proper title and description to this pull request, explaining what this change does

**Comment by gregorydlogan** [comment]
@ek926m this looks good, aside from @lkiesow's comments.  You're very close to out of time wrt to getting this into 8.0.

**Comment by ek926m** [comment]
> @ek926m this looks good, aside from @lkiesow's comments. You're very close to out of time wrt to getting this into 8.0.

I updated the PR text and with @lkiesow's help I did a rebase. Now I am waiting for travis-ci to give me a green check. I hope everything is fine now.

**Pull request merged**
