### PR TITLE
Paella 7: Fix vertically stretched thumbnails in transcriptions plugin

### LINKED ISSUE #5186: Paella7: Vertically stretched thumbnails in audio transcriptions plugin
**Describe the bug**

Thumbnails in the audio transcriptions plugin in Paella Player 7 are vertically stretched to the size of the textbox next to it. Naturally the problem becomes more appearent if a slide contains a lot of text.

**To Reproduce**

- Upload a video containing a lot of text using a workflow that uses the segmentation and extract text operations
- Open the video in paella Player 7 and look at the audio transciptions submenu.

**Expected behavior**

The aspect ratio of the original image should be used to display the thumbnails.

**Screenshots**

screenshot_bug

**User environment:**

 - Device: PC
 - OS: Debian 12
 - Browser: Chrome
 - Version: 116.0.5845.110

### PR DESCRIPTION
**Pull request by miesgre**
### Your pull request should…

* [x] have a concise title
* [x] [close an accompanying issue](https://help.github.com/en/articles/closing-issues-using-keywords) closes #5186 
* [x] [be against the correct branch](https://docs.opencast.org/develop/developer/development-process#acceptance-criteria-for-patches-in-different-versions)
* [ ] include migration scripts and documentation, if appropriate
* [x] pass automated tests
* [x] have a clean commit history
* [x] [have proper commit messages (title and body) for all commits](https://medium.com/@steveamaza/e028865e5791)

### Screenshot
Captura de pantalla 2023-09-14 a las 8 32 16

### CODE REVIEW

**Review by mliradelc — APPROVED** [review]
All good

**Comment by mliradelc** [comment]
Is This bug affecting also  `13.x`?

**Comment by miesgre** [comment]
> Is This bug affecting also `13.x`?

I haven't tried it, but I think so. I will redirect it to 13.x if you want

**Comment by miesgre** [comment]
@mliradelc I can not rebase it to 13.x because the paella version of 13.x is not compatible with some of the changes.

**Comment by mliradelc** [comment]
No worries Miguel, we can let into `14.x` and later onwards.

**Pull request merged**
