### PR TITLE
Add silient detection based on subtitles (webvtt-to-cutmarks woh)

### PR DESCRIPTION
**Pull request by darolfes**
This pullrequests adds a workflow operation, which transforms a WebVTT Subtitle file into a CutMarkJson, which can then be used for cutting.
Primary use case is silence detection based on subtitle information.

It also moves the WebVTT parser into its own module, so that the parser can be included in different modules.

Documentation: `docs/guides/admin/docs/workflowoperationhandlers/webvtt-to-cutmarks.md`

### CODE REVIEW

**Review by Arnei — APPROVED** [review]
Works as advertised, code looks fine, documentation is there, LGTM!

**Comment by mtneug** [comment]
@Arnei this could go into r/13.x right?

**Comment by Arnei** [comment]
Doesn't change existing behaviour, just moves some code around and adds a new WOH, so it should be fine to go into r/13.x I think.

**Comment by darolfes** [comment]
rebased to r/13.x

**Pull request merged**
