### PR TITLE
MH-13431 Remove unfinished feature "Bulk Messaging"

### PR DESCRIPTION
**Pull request by staubesv**
Opencast contains quite a bit of code to the unfinished feature "Bulk messaging". The idea behind that feature is that Opencast allows users to send e-mails to some technical contact of events.

The feature would include:

- Management of e-mail templates
- Management of e-mail signatures
- Persistence of SMTP configurations (per tenant)
- Bulk action "Send message" to actually send messages

The goal of this task is to removed that unfinished feature from the Opencast codebase.

### CODE REVIEW

**Comment by lkiesow** [comment]
Just checking: This is not used in any way by the email workflow operation, is it?

**Comment by staubesv** [comment]
This is neither related to the email workflow operation nor the email template service used by that workflow operation.

**Comment by staubesv** [comment]
Oh, just realised that the security configuration has rules related to the e-mail templates that can also be removed... will update the PR tomorrow.

**Comment by staubesv** [comment]
@lkiesow PR updated.

**Pull request merged**
