### PR TITLE
MH-12387 - Fix CAS

### PR DESCRIPTION
**Pull request by miesgre**
In commit 132065b6a9b9c804c9e6fca08ebf5958b15d0988 opensaml library was update to 2.6.4 version. That change broke CAS.

This PR fix CAS.

### CODE REVIEW

**Comment by lkiesow** [comment]
I've asked on list if anyone can help to test this since I have no CAS set-up. If no one speaks up, I'll just do a best-effort review early next week.

**Comment by lkiesow** [comment]
Andrew Wilson from Manchester agreed to test this, yay:

> Hi Lars
> i'll review this pull request, it may take me a little bit to get going
> thanks
> -andy

**Comment by hanserasmus** [comment]
Hi guys

Tested this patch by first creating a vanilla install and making sure all is well. I was able to successfully login to my opencast page. Then moved my install out, and replaced with this patched version via Lars' tarball. I copied my initial version of custom.properties to ensure the settings to the DB and activemq stay consistent, and only edited the files according to [the docs](https://docs.opencast.org/r/5.x/admin/configuration/security.cas/) but are getting the following now in my logfiles:

`2018-08-02 10:48:47,902 | ERROR | (SpringSecurityConfigurationArtifactInstaller:102) - Unable to refresh spring security configuration file /opt/opencast/etc/security/mh_default_org.xml: {}
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springframework.security.filterChains': Cannot resolve reference to bean 'org.springframework.security.web.DefaultSecurityFilterChain#0' while setting bean property 'sourceList' with key [0]; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springframework.security.web.DefaultSecurityFilterChain#0': Cannot resolve reference to bean 'singleLogoutFilter' while setting constructor argument with key [3]; nested exception is org.springframework.beans.factory.CannotLoadBeanClassException: Cannot find class [org.jasig.cas.client.session.SingleSignOutFilter] for bean with name 'singleLogoutFilter' defined in OSGi resource[file:/opt/opencast/etc/security/mh_default_org.xml|bnd.id=108|bnd.sym=opencast-kernel]; nested exception is java.lang.ClassNotFoundException: org.jasig.cas.client.session.SingleSignOutFilter not found from bundle [opencast-kernel]
	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveReference(BeanDefinitionValueResolver.java:329)[333:org.springframework.beans:3.1.4.RELEASE]
	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveValueIfNecessary(BeanDefinitionValueResolver.java:107)[333:org.springframework.beans:3.1.4.RELEASE]
	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveManagedList(BeanDefinitionValueResolver.java:354)[333:org.springframework.beans:3.1.4.RELEASE]
	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveValueIfNecessary(BeanDefinitionValueResolver.java:154)[333:org.springframework.beans:3.1.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyPropertyValues(AbstractAutowireCapableBeanFactory.java:1360)[333:org.springframework.beans:3.1.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1118)[333:org.springframework.beans:3.1.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:517)[333:org.springframework.beans:3.1.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:456)[333:org.springframework.beans:3.1.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:294)[333:org.springframework.beans:3.1.4.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:225)[333:org.springframework.beans:3.1.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:291)[333:org.springframework.beans:3.1.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:193)[333:org.springframework.beans:3.1.4.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:589)[333:org.springframework.beans:3.1.4.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:925)[334:org.springframework.context:3.1.4.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:472)[334:org.springframework.context:3.1.4.RELEASE]
	at org.springframework.osgi.context.support.AbstractDelegatedExecutionApplicationContext.access$301(AbstractDelegatedExecutionApplicationContext.java:69)[339:org.springframework.osgi.core:1.2.1]
	at org.springframework.osgi.context.support.AbstractDelegatedExecutionApplicationContext$1.run(AbstractDelegatedExecutionApplicationContext.java:186)[339:org.springframework.osgi.core:1.2.1]
	at org.springframework.osgi.util.internal.PrivilegedUtils.executeWithCustomTCCL(PrivilegedUtils.java:85)[339:org.springframework.osgi.core:1.2.1]
	at org.springframework.osgi.context.support.AbstractDelegatedExecutionApplicationContext.normalRefresh(AbstractDelegatedExecutionApplicationContext.java:182)[339:org.springframework.osgi.core:1.2.1]
	at org.springframework.osgi.context.support.AbstractDelegatedExecutionApplicationContext$NoDependenciesWaitRefreshExecutor.refresh(AbstractDelegatedExecutionApplicationContext.java:89)[339:org.springframework.osgi.core:1.2.1]
	at org.springframework.osgi.context.support.AbstractDelegatedExecutionApplicationContext.refresh(AbstractDelegatedExecutionApplicationContext.java:175)[339:org.springframework.osgi.core:1.2.1]
	at org.opencastproject.kernel.security.SpringSecurityConfigurationArtifactInstaller.install(SpringSecurityConfigurationArtifactInstaller.java:100)[108:opencast-kernel:5.0.0.SNAPSHOT]
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.install(DirectoryWatcher.java:937)[4:org.apache.felix.fileinstall:3.6.0]
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.install(DirectoryWatcher.java:871)[4:org.apache.felix.fileinstall:3.6.0]
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.doProcess(DirectoryWatcher.java:485)[4:org.apache.felix.fileinstall:3.6.0]
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.process(DirectoryWatcher.java:361)[4:org.apache.felix.fileinstall:3.6.0]
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.run(DirectoryWatcher.java:312)[4:org.apache.felix.fileinstall:3.6.0]
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springframework.security.web.DefaultSecurityFilterChain#0': Cannot resolve reference to bean 'singleLogoutFilter' while setting constructor argument with key [3]; nested exception is org.springframework.beans.factory.CannotLoadBeanClassException: Cannot find class [org.jasig.cas.client.session.SingleSignOutFilter] for bean with name 'singleLogoutFilter' defined in OSGi resource[file:/opt/opencast/etc/security/mh_default_org.xml|bnd.id=108|bnd.sym=opencast-kernel]; nested exception is java.lang.ClassNotFoundException: org.jasig.cas.client.session.SingleSignOutFilter not found from bundle [opencast-kernel]
	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveReference(BeanDefinitionValueResolver.java:329)[333:org.springframework.beans:3.1.4.RELEASE]
	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveValueIfNecessary(BeanDefinitionValueResolver.java:107)[333:org.springframework.beans:3.1.4.RELEASE]
	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveManagedList(BeanDefinitionValueResolver.java:354)[333:org.springframework.beans:3.1.4.RELEASE]
	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveValueIfNecessary(BeanDefinitionValueResolver.java:154)[333:org.springframework.beans:3.1.4.RELEASE]
	at org.springframework.beans.factory.support.ConstructorResolver.resolveConstructorArguments(ConstructorResolver.java:616)[333:org.springframework.beans:3.1.4.RELEASE]
	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:148)[333:org.springframework.beans:3.1.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1035)[333:org.springframework.beans:3.1.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:939)[333:org.springframework.beans:3.1.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:485)[333:org.springframework.beans:3.1.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:456)[333:org.springframework.beans:3.1.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:294)[333:org.springframework.beans:3.1.4.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:225)[333:org.springframework.beans:3.1.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:291)[333:org.springframework.beans:3.1.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:193)[333:org.springframework.beans:3.1.4.RELEASE]
	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveReference(BeanDefinitionValueResolver.java:323)[333:org.springframework.beans:3.1.4.RELEASE]
	... 26 more
Caused by: org.springframework.beans.factory.CannotLoadBeanClassException: Cannot find class [org.jasig.cas.client.session.SingleSignOutFilter] for bean with name 'singleLogoutFilter' defined in OSGi resource[file:/opt/opencast/etc/security/mh_default_org.xml|bnd.id=108|bnd.sym=opencast-kernel]; nested exception is java.lang.ClassNotFoundException: org.jasig.cas.client.session.SingleSignOutFilter not found from bundle [opencast-kernel]
	at org.springframework.beans.factory.support.AbstractBeanFactory.resolveBeanClass(AbstractBeanFactory.java:1262)[333:org.springframework.beans:3.1.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:433)[333:org.springframework.beans:3.1.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:294)[333:org.springframework.beans:3.1.4.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:225)[333:org.springframework.beans:3.1.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:291)[333:org.springframework.beans:3.1.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:193)[333:org.springframework.beans:3.1.4.RELEASE]
	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveReference(BeanDefinitionValueResolver.java:323)[333:org.springframework.beans:3.1.4.RELEASE]
	... 40 more
Caused by: java.lang.ClassNotFoundException: org.jasig.cas.client.session.SingleSignOutFilter not found from bundle [opencast-kernel]
	at org.springframework.osgi.util.BundleDelegatingClassLoader.findClass(BundleDelegatingClassLoader.java:103)[339:org.springframework.osgi.core:1.2.1]
	at org.springframework.osgi.util.BundleDelegatingClassLoader.loadClass(BundleDelegatingClassLoader.java:156)[339:org.springframework.osgi.core:1.2.1]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)[:1.8.0_181]
	at org.springframework.util.ClassUtils.forName(ClassUtils.java:258)[336:org.springframework.core:3.1.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanDefinition.resolveBeanClass(AbstractBeanDefinition.java:417)[333:org.springframework.beans:3.1.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doResolveBeanClass(AbstractBeanFactory.java:1283)[333:org.springframework.beans:3.1.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.resolveBeanClass(AbstractBeanFactory.java:1254)[333:org.springframework.beans:3.1.4.RELEASE]
	... 46 more
Caused by: java.lang.ClassNotFoundException: org.jasig.cas.client.session.SingleSignOutFilter not found by opencast-kernel [108]
	at org.apache.felix.framework.BundleWiringImpl.findClassOrResourceByDelegation(BundleWiringImpl.java:1550)[org.apache.felix.framework-5.6.4.jar:]
	at org.apache.felix.framework.BundleWiringImpl.access$200(BundleWiringImpl.java:79)[org.apache.felix.framework-5.6.4.jar:]
	at org.apache.felix.framework.BundleWiringImpl$BundleClassLoader.loadClass(BundleWiringImpl.java:1958)[org.apache.felix.framework-5.6.4.jar:]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)[:1.8.0_181]
	at org.apache.felix.framework.Felix.loadBundleClass(Felix.java:1926)[org.apache.felix.framework-5.6.4.jar:]
	at org.apache.felix.framework.BundleImpl.loadClass(BundleImpl.java:978)[org.apache.felix.framework-5.6.4.jar:]
	at org.springframework.osgi.util.BundleDelegatingClassLoader.findClass(BundleDelegatingClassLoader.java:99)[339:org.springframework.osgi.core:1.2.1]
	... 52 more
`
and also a 403 forbidden on the webpage now. Don't know  if it due to some other issues, and if it pertains to this PR? 

`java -version
openjdk version "1.8.0_181"
OpenJDK Runtime Environment (build 1.8.0_181-b13)
OpenJDK 64-Bit Server VM (build 25.181-b13, mixed mode)
`

**Comment by miesgre** [comment]
Thanks for merging this. Will this be merged into develop or Do I have to make another PR to develop branch?

**Comment by lkiesow** [comment]
By now, it's already in `develop`. The release branches are merged downwards on a regular basis (`r/4.x` → `r/5.x` → `develop`) and I've just done that today. So you only need to provide a patch once.

Btb. I've tested this patch as you instructed and had no problems at all to get it running. Thanks for the patch.

**Pull request merged**
