### PR TITLE
Create JpaUserReference for LTI user (update to 9.x)

### LINKED ISSUE #1168: LTI Users are not persisted, causing workflow failures
Via https://opencast.jira.com/browse/MH-8955

In the absence of a UserProvider, users who authenticate via LTI are not visible beyond the LTI session.

This prevents users from taking operations such as scheduling, as workflow operations subsequently fail when the user cannot be resolved.

Opencast should optionally persist LTI users into the mh_user_ref table.

Similar to:

https://bitbucket.org/opencast-community/matterhorn/pull-requests/1348/mh-12029-as-a-user-i-want-to-use-my/diff

From @smarquard in 2019:
> AFAIK if you run Opencast using LTI but without a userprovider, workflows started by LTI users fail because the resolution of those usernames on worker nodes fails.

### PR DESCRIPTION
**Pull request by darolfes**
This pull request adds documentation for 9.x and reverts the changes made for the backport in #1482 . The feature is now enabled by default.

Originaltext:
This pull request persists users, which login through LTI, by adding them to the JpaUserReference table on login. This allows users to take actions, which take longer than the LTI session, as otherwise the user lookups would fail.

closes opencast#1168

### CODE REVIEW

**Comment by gregorydlogan** [comment]
@darolfes I took a quick look through this and everything looks good.  Is this ready for a proper review?

**Comment by darolfes** [comment]
@gregorydlogan after additional testing this is now ready for a proper review.

**Comment by darolfes** [comment]
rebased and fixed merge conflict in upgrade.md

**Comment by smarquard** [comment]
Is this optional? Sites which also resolve LTI users through a user directory provider don't need this additional user reference stored in OC.

**Comment by gregorydlogan** [comment]
@smarquard It doesn't look optional to me.  @darolfes can you add an option for that?

**Comment by gregorydlogan** [comment]
Is work on this still pending?

**Comment by darolfes** [comment]
Sorry for the delay, the feature can now be disabled using the `lti.create_jpa_user_reference` option.
By default the feature is activated.

**Comment by darolfes** [comment]
this will be updated, when the backport #1482 has been integrated into develop

**Comment by darolfes** [comment]
Updated the pull request:
This pull request adds documentation for 9.x and reverts the changes made for the backport in #1482 . The feature is now enabled by default.

**Review by lkiesow — APPROVED** [review]

**Comment by gregorydlogan** [comment]
@darolfes conflicts.

**Comment by darolfes** [comment]
resolved

**Pull request merged**
