### PR TITLE
Bump java version to 17

### PR DESCRIPTION
**Pull request by geichelberger**
This bumps the Java version to 17 and tests against 21

* [ ] have a concise title
* [ ] [close an accompanying issue](https://docs.opencast.org/develop/developer/#participate/development-process/#automatically-closing-issues-when-a-pr-is-merged) if one exists
* [ ] [be against the correct branch](https://docs.opencast.org/develop/developer/development-process#acceptance-criteria-for-patches-in-different-versions)
* [ ] include migration scripts and documentation, if appropriate
* [ ] pass automated tests
* [ ] have a clean commit history
* [ ] [have proper commit messages (title and body) for all commits](https://medium.com/@steveamaza/e028865e5791)

### CODE REVIEW

**Comment by gregorydlogan** [comment]
Both 17 and 21 seem like they work to me, at least with the things I can test.  IMO this should be in OC 16 since we're going to have a bunch of breaking changes anyway.  @geichelberger can you add a bit into the release notes for this?

**Comment by lkiesow** [comment]
Which version of Java do we want to support? If we continue to support 11, shouldn't we ttest against 11.  So… maybe 11 and 21?

**Comment by geichelberger** [comment]
The idea is to drop support for 11 and require Java 17.

**Comment by lkiesow** [comment]
Actually, looking at https://endoflife.date/redhat-build-of-openjdk, maybe it makes sense to require 17 after all. But then I would suggest applying this patch after the OC 16 branch cut and making this a requirement for Opencast 17.

*(you were faster)*

**Comment by geichelberger** [comment]
And the other reason is developer joy.

**Comment by gregorydlogan** [comment]
We talked about this in the meeting last week. The sense was that we've already got a bunch of breaking changes with 16, moving the jdk requirements might make sense as well.

Tbh I don't particularly care, as long as it's clear :)

**Comment by gregorydlogan** [comment]
@geichelberger This needs release notes before it can go in.

**Comment by mtneug** [comment]
FYI: I changed to a Java 17 container base image since 15.0.

**Pull request merged**
