### PR TITLE
MH-13719: Update to paella player 6.2.2

### PR DESCRIPTION
**Pull request by miesgre**
Update to paella player 6.2.2

**This PR contains PR #1054 , so shouldn't be merged before that one!**

### CODE REVIEW

**Comment by karendolan** [comment]
HI @miesgre , the new "es.upv.paella.defaultKeysPlugin" is missing from the Opencast Paella config. 
https://github.com/polimediaupv/paella/blob/develop/config/config.json#L186-L187
https://github.com/opencast/opencast/blob/develop/etc/ui-config/mh_default_org/paella/config.json

**Comment by miesgre** [comment]
Thanks @karendolan. I updated the config file

**Comment by miesgre** [comment]
Conflicts resolved. @lkiesow can you review it?

**Comment by karendolan** [comment]
Not part of the pull, but a bug making it hard to test the pull...

```
  getAudioTagFromTrack(currentTrack) {
    let audioTagConfig = this.getAudioTagConfig();
    let audioTag;
    let tags = [];

    if (currentTrack.tags && currentTrack.tags.tag) {
      tags = [currentTrack.tags.tag];    <------- re-wrapping a potential array as a double array

      if (!(currentTrack.tags.tag instanceof Array)) { <--- wrapping a non-array as an array
        tags = [currentTrack.tags.tag];
      }
```

should be 

```
  getAudioTagFromTrack(currentTrack) {
    let audioTagConfig = this.getAudioTagConfig();
    let audioTag;
    let tags = [];

    if (currentTrack.tags && currentTrack.tags.tag) {
      tags = currentTrack.tags.tag;

      if (!(tags instanceof Array)) { <--- wrapping a non-array as an array
        tags = [tags];
      }
```

**Comment by miesgre** [comment]
@karendolan Fixed. Thanks.

**Comment by karendolan** [comment]
Looks good to me. I can't verify in my test environment, the auth order change. But it makes more sense to me in the new order.

**Review by karendolan — APPROVED** [review]
Seems to be working correctly.

**Pull request merged**
