### PR TITLE
Update Test Server Builds

### PR DESCRIPTION
**Pull request by lkiesow**
This patch includes the preparation for updating the test servers into
the main repository builds by building the distribution tarballs on
`push` events and uploading them to S3.

### Your pull request should…

* [x] have a concise title
* [x] [close an accompanying issue](https://help.github.com/en/articles/closing-issues-using-keywords) if one exists
* [x] be against the correct branch (features can only go into develop)
* [x] include migration scripts and documentation, if appropriate
* [x] pass automated tests
* [x] have a clean commit history
* [x] [have proper commit messages (title and body) for all commits](https://medium.com/@steveamaza/e028865e5791)

### CODE REVIEW

**Comment by lkiesow** [comment]
Not sure if anyone wants to try testing this or if we just want to deploy this and see if it works (I tested it on my account)

**Comment by gregorydlogan** [comment]
Imma do this. I can see a sec issue already I suspect :)

**Comment by lkiesow** [comment]
> I can see a sec issue already I suspect

If you suspect a security issue, I'm not going to deploy this :D
Can you give me more details?

If it's that this workflow is also run on pull request, be aware that from such a run you cannot access secrets even if you modify the Actions workflow. So you can't push arbitrary code via pull request. It only works if it is already in the repository.

**Comment by gregorydlogan** [comment]
Yep, that's what I missed.  I thought this was firing on PRs, which presents the obvious issue of echoing the creds to the log, or sending them somewhere via some other method.

My only other complaint here is that this won't fire on develop since it's not prefixed with `r/`.

**Comment by lkiesow** [comment]
> My only other complaint here is that this won't fire on develop since it's not prefixed with r/.

Good catch. Hopefully fixed that.

**Comment by gregorydlogan** [comment]
Lgtm

**Pull request merged**
