### PR TITLE
Update accesspolicies.md: fixed grammar issues

### PR DESCRIPTION
**Pull request by csingam**
Fixed grammar issues in the accesspolicies.md documentation file.

### CODE REVIEW

**Comment by smarquard** [comment]
Looks good. If you adjust the target branch to 8.x, it would get into an OC release sooner.

**Comment by gregorydlogan** [comment]
If this applies to 7.x (or even 6.x) feel free to go back that far too.  The documentation gets rebuilt even without a release, so the further back the better.

**Comment by lkiesow** [comment]
@smarquard, will you take the official review for this patch?

**Comment by lkiesow** [comment]
@smarquard, please don't merge pull requests with failing tests. I've fixed the issue on `develop` but this directly caused #1133 to fail as well.

**Comment by smarquard** [comment]
Sorry, I assumed the failure was from one of the many other failure-inducing issues in develop recently. Maybe time to change the github config to require a passing CI test before merge is allowed?

**Pull request merged**
