### PR TITLE
MH-12830: Add Maven site distribution information

### PR DESCRIPTION
**Pull request by gregorydlogan**
Fixing mvn site distribution information.  This data is fakee, but since we are not using Maven to distribute the site then it does not matter.

### CODE REVIEW

**Comment by lkiesow** [comment]
`mvn site site:stage -DstagingDirectory=foo` did run through with this merged into `r/4.x` with the following patch applied:

```diff
diff --git a/modules/matterhorn-scheduler-api/src/main/java/org/opencastproject/scheduler/api/SchedulerService.java b/modules/matterhorn-scheduler-api/src/main/java/org/opencastproject/scheduler/api/SchedulerService.java
index 16f6f9ac1..7e6620e17 100644
--- a/modules/matterhorn-scheduler-api/src/main/java/org/opencastproject/scheduler/api/SchedulerService.java
+++ b/modules/matterhorn-scheduler-api/src/main/java/org/opencastproject/scheduler/api/SchedulerService.java
@@ -281,7 +281,7 @@ public interface SchedulerService {
    *          the optional scheduling source from which the event comes from
    * @param modificationOrigin
    *          the origin of the modifier which adds the event
-   * @return A {@link Map>} of mediapackage ID and {@link Period} where the event occurs
+   * @return A {@link Map} of mediapackage ID and {@link Period} where the event occurs
    * @throws UnauthorizedException
    *           if the caller is not authorized to take this action
    * @throws SchedulerConflictException
```

However,  the result was that all module sites ended up in `foo` subdirectories of each module making the links not work on the main site. There still seems to be something wrong with this. Or did I miss anything?

**Comment by gregorydlogan** [comment]
Note to self: Read the documentation.  From https://maven.apache.org/plugins/maven-site-plugin/stage-mojo.html's description of stagingDirectory, bolding mine

> Staging directory location. This needs to be an **absolute path**, like C:\stagingArea\myProject\ on Windows or /stagingArea/myProject/ on Unix. If this is not specified, the site will be staged in ${project.build.directory}/staging.


This works on my end:
```mvn site -Daggregate=true site:stage -DstagingDirectory=/home/greg/opencast/mine/foo -P none```

**Comment by lkiesow** [comment]
Great, now I managed to get a proper report using `mvn site -Daggregate=true site:stage "-DstagingDirectory=$(pwd)/foo" -Pnone`. What do you think, should we add that to Travis instead of the simple `mvn site`?

**Comment by gregorydlogan** [comment]
The only thing that site:stage does is move things into the appropriate place for distributing the site.  Since we're not doing that (yet) then we don't need to worry about it for travis.  I've already made the relevant change in the BuildBot scripts so ones that goes live things ought to just work.

**Pull request merged**
