### PR TITLE
MH-13694 Sort roles alphabetically in UI

### PR DESCRIPTION
**Pull request by KatrinIhler**
Instead of a roles listprovider, which returns the roles as a map, hand the roles to the admin ui as a list by a dedicated endpoint so the alphabetical order won't get lost.

**This PR contains PR #1046, so shouldn't be merged before that one!** 

_This work was sponsored by the ETH Zürich._

### CODE REVIEW

**Comment by gregorydlogan** [comment]
@KatrinIhler conflicts

**Comment by gregorydlogan** [comment]
@KatrinIhler conflicts again, sigh.

**Comment by gregorydlogan** [comment]
@KatrinIhler conflicts.  Also, should this go into 8.x, or develop?

**Comment by gregorydlogan** [comment]
On hold pending #1046, and conflict resolution here.

**Comment by KatrinIhler** [comment]
Ready for review, finally.

**Comment by gregorydlogan** [comment]
@KatrinIhler Please rebase :)

**Comment by KatrinIhler** [comment]
@gregorydlogan Done! :)

**Pull request merged**
