### PR TITLE
MH-13101 Update paella dependencies

### PR DESCRIPTION
**Pull request by miesgre**
Jira Ticket: https://opencast.jira.com/browse/MH-13101

Update Paella dependencies

### CODE REVIEW

**Comment by lkiesow** [comment]
Generally looks good though I'm wondering where these messages come fron:

```
.../engage-paella-player% mvn -B -e clean install
[...]
[INFO] Building Opencast :: engage-paella-player 6-SNAPSHOT
[...]
[INFO] --- frontend-maven-plugin:1.5:gulp (gulp build) @ opencast-engage-paella-player ---
[INFO] Running 'gulp paella-opencast:build' in /home/lars/dev/opencast/modules/engage-paella-player
[INFO] [14:59:00] Using gulpfile ~/dev/opencast/modules/engage-paella-player/gulpfile.js
[INFO] [14:59:00] Starting 'paella-opencast:prepare:source'...
[INFO] [14:59:00] Finished 'paella-opencast:prepare:source' after 231 ms
[INFO] [14:59:00] Starting 'paella-opencast:prepare'...
[WARNING] npm WARN deprecated gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
[WARNING] npm WARN deprecated connect@2.30.2: connect 2.x series is deprecated
[WARNING] npm WARN deprecated gulp-util@2.2.20: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
[WARNING] npm WARN deprecated http2@3.3.7: Use the built-in module in node 9.0.0 or newer, instead
[WARNING] npm WARN deprecated graceful-fs@3.0.11: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
[WARNING] npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
[WARNING] npm WARN deprecated socks@1.1.10: If using 2.x branch, please upgrade to at least 2.1.6 to avoid a serious bug with socket data flow and an import issue introduced in 2.1.0
[WARNING] npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
[WARNING] npm WARN deprecated graceful-fs@1.2.3: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
[ERROR] npm notice created a lockfile as package-lock.json. You should commit this file.
[INFO] added 704 packages in 5.261s
[INFO] [14:59:06] Finished 'paella-opencast:prepare' after 5.69 s
[...]
```

**Review by staubesv — APPROVED** [review]
Thanks for cleaning this up!

**Comment by staubesv** [comment]
@lkiesow As far as I understand, those messages come from the external Paella that is built by the task paella-opencast:prepare which runs the build task of the Paella Player we externally "downloaded" and therefore are not caused by the gulp file of "our repository" but rather by the gulp file of the "Paella repository".

> package.json:     "paellaplayer": "github:polimediaupv/paella#5.3.10"
>
> [...]
>
> var s1 = gulp.src('node_modules/paellaplayer/**').pipe(gulp.dest(buildPath + '/paella'));
> 
> [...] 
>
> gulp.task('paella-opencast:compile.release', ['paella-opencast:prepare'], function(cb){
>  	var cmd_npm = spawn('node', ['node_modules/gulp/bin/gulp.js', 'build.release'], {cwd: buildPath + '/paella'/*, stdio: 'inherit'*/});
>  	cmd_npm.on('close', function (code) {
>  		cb(code);
>  	});
>  });

@miesgre Is this correct?

**Comment by miesgre** [comment]
@staubesv Yes, it is correct.

**Pull request merged**
