### PR TITLE
Properly configure AWS S3 distribution on startup by default

### PR DESCRIPTION
**Pull request by gregorydlogan**
Properly configuring S3 distribution on startup.  This leaves your bucket wide open for read access, which is required for S3 dist to work as the current code stands.  See #2044 for a more secure way.

### Your pull request should…

* [x] have a concise title
* [ ] [close an accompanying issue](https://help.github.com/en/articles/closing-issues-using-keywords) if one exists
* [x] be against the correct branch (features can only go into develop)
* [x] ~include migration scripts and documentation, if appropriate~
* [x] pass automated tests
* [x] have a clean commit history
* [x] [have proper commit messages (title and body) for all commits](https://medium.com/@steveamaza/e028865e5791)

### CODE REVIEW

**Comment by lkiesow** [comment]
@Gao-Jun, seeing that you worked on the code anyway. Would you mind taking a look at this and giving some feedback. That would be awesome.

**Comment by Gao-Jun** [comment]
This PR add setting of some default pages for S3 static site. The purpose of this is good, it can help people get some useful information.

Once I doubted if this is conflict to presigned URL feature (#2044) which require the bucket not open to public. And then I found this was only work for a non-exist bucket, and set the bucket publicly readable and add some default pages. So, these changes would not break any logic for current behaviors.

When #2044 could be accepted, the doc of AWS features is needed to be updated to ask admins manually create bucket first.

**Comment by gregorydlogan** [comment]
Yep, my intention is to get the docs updated after #2044 is merged.

**Comment by gregorydlogan** [comment]
This is now done with 67c23da641 in 9.x.

**Comment by gregorydlogan** [comment]
@lkiesow this is ready for review (or dispatch)

**Review by pascalseeland — APPROVED** [review]
Changes look fine.

**Review by pascalseeland — APPROVED** [review]

**Pull request merged**
