### PR TITLE
Migrate to annotations cleanup

### PR DESCRIPTION
**Pull request by geichelberger**
Merge after #3255

Removes OSGi XML files and pom Service-Component section.

* [ ] have a concise title
* [ ] [close an accompanying issue](https://help.github.com/en/articles/closing-issues-using-keywords) if one exists
* [ ] [be against the correct branch](https://docs.opencast.org/develop/developer/development-process#acceptance-criteria-for-patches-in-different-versions)
* [ ] include migration scripts and documentation, if appropriate
* [ ] pass automated tests
* [ ] have a clean commit history
* [ ] [have proper commit messages (title and body) for all commits](https://medium.com/@steveamaza/e028865e5791)

### CODE REVIEW

**Comment by gregorydlogan** [comment]
Considering that #3255 isn't merged yet, and I'd only review them both together anyway, why don't you squash 'em both into one PR or the other?

**Comment by geichelberger** [comment]
I thought it would be easier to review if 300 files less were changed, and it's some kind of documentation if the XML files still exist. If you prefer, I can squash them.

**Comment by gregorydlogan** [comment]
Nah, I got through the first PR today, so lets just leave them separately now.

**Comment by gregorydlogan** [comment]
@geichelberger #3255 merged, can take a look at this tomorrow if you've got time to fix conflicts

**Pull request merged**
