### PR TITLE
Add tests to engage-paella-player-7 module

### PR DESCRIPTION
**Pull request by miesgre**
**Warning**: PR https://github.com/opencast/opencast/pull/4953 should me merged first!

This PR adds some basic E2E tests to the engage-paella-player-7 module.
As a working opencast server is required, the tests runs against devel.opencat.org
A few tests are being done for now, more will be added in the future.

### Your pull request should…

* [ ] have a concise title
* [ ] [close an accompanying issue](https://help.github.com/en/articles/closing-issues-using-keywords) if one exists
* [ ] [be against the correct branch](https://docs.opencast.org/develop/developer/development-process#acceptance-criteria-for-patches-in-different-versions)
* [ ] include migration scripts and documentation, if appropriate
* [ ] pass automated tests
* [ ] have a clean commit history
* [ ] [have proper commit messages (title and body) for all commits](https://medium.com/@steveamaza/e028865e5791)

### CODE REVIEW

**Comment by mliradelc** [comment]
Hi Miguel, I saw that you were updating the Skins PRs. Because of that, I was waiting to start reviewing.

**Comment by miesgre** [comment]
> Hi Miguel, I saw that you were updating the Skins PRs. Because of that, I was waiting to start reviewing.

PR #4953 should be merged first. Please review #4953 if you have time to be in time with opencast 14.

**Review by mliradelc — COMMENTED** [review]
https://github.com/opencast/opencast/actions/runs/5252527431/jobs/9488694027?pr=5036 Shows that your tests are working as expected.

@miesgre There are some conflicts; can you solve them?

**Review by mliradelc — APPROVED** [review]
All Good

**Pull request merged**
