### PR TITLE
Run Tests Only If Necessary

### PR DESCRIPTION
**Pull request by lkiesow**
This patch makes a number of tests run only if necessary since the
relevant parts of the code have changed. This is similar to pull
request #2249.

### Your pull request should…

* [x] have a concise title
* [x] [close an accompanying issue](https://help.github.com/en/articles/closing-issues-using-keywords) if one exists
* [x] be against the correct branch (features can only go into develop)
* [x] include migration scripts and documentation, if appropriate
* [x] pass automated tests
* [x] have a clean commit history
* [x] [have proper commit messages (title and body) for all commits](https://medium.com/@steveamaza/e028865e5791)

### CODE REVIEW

**Comment by mliradelc** [comment]
Hi I haven't Seen this
I will test right away. :)

Question: Before merge, should we discuss it?

**Comment by lkiesow** [comment]
I wouldn't assume this to be controversial and no one complained at the technical meeting.
Do you assume it to be? If so we can, if not, we don't need to.

**Comment by mliradelc** [comment]
Is all good, for some reason, sometimes github actions fails in compile, now I restarted and worked
@lkiesow  I think is not necessary to discuss is a complement for opencast development and only affects github behaviour.

**Review by mliradelc — APPROVED** [review]
All ok! works!

**Pull request merged**
