### PR TITLE
MH-13596, Drop Distribution “adminworker”

### PR DESCRIPTION
**Pull request by lkiesow**
As discussed on list, this drops the “adminworker” distribution from the
set of default distributions.

### CODE REVIEW

**Comment by staubesv** [comment]
@lkiesow Not in scope of this PR, but it might make sense to consider removing the distribution adminpresentation, too.

**Review by staubesv — APPROVED** [review]

**Comment by mtneug** [comment]
If I recall correctly, UTC is using `adminpresentation`. They extended the LTI tools with features that require access to APIs that only the `admin` distribution provides. Authenticating via LTI agains `presentation` only is therefore not enough.

**Comment by lkiesow** [comment]
There are a few installations I know which are using `adminpresentation`. Just none I know of which are using `adminworker`.

**Comment by staubesv** [comment]
@lkiesow & @mtneug Fine for me.

**Pull request merged**
