### PR TITLE
MAT-281, use the opencast storage dir not java.io.tmpdir for large editor files

### PR DESCRIPTION
**Pull request by JamesUoM**

### CODE REVIEW

**Comment by JamesUoM** [comment]
This should also merge to 4.x. Should I create a separate PR for develop?

**Comment by gregorydlogan** [comment]
Nope, we should be merging 4.x back into develop for a while yet.  It's just a matter of waiting :)

**Comment by lkiesow** [comment]
This is already fixed in `r/4.x` and `develop` by commit 3ba4e2221.
Note that that patch uses different directories which is probably not ideal for migrations.
Is there any reason why you did not use that patch?

**Comment by JamesUoM** [comment]
Because I've searched for a ticket on this issue several times and for whatever reason that ticket never came up.

Feel free to reject this, we needed it to mitigate some storage issues here and Manchester.

**Comment by gregorydlogan** [comment]
@lkiesow @JamesUoM, take a look at #107, which is the backport Lars is talking about.  I'd say let's decline this in favour of something that's going to cause fewer merge conflicts?

**Comment by lkiesow** [comment]
I'm declining this in favor of pull request #107

**Pull request closed without merging**
