### PR TITLE
duplicate WFH changes title and StartDateTime

### PR DESCRIPTION
**Pull request by ts23**
For rolling forward Lectures from one year to the next we need to be able to change the Title and Start Date and Time of the duplicated mediapackage.

### CODE REVIEW

**Comment by joneug** [comment]
I tested this and the given title is set correctly. However, the given date is only reflected in the "Created" metadata filed not in the "Start date" field. Is this what you wanted?

Also, I cannot start the duplicate-event workflow without specifying a start date. If I try that the following exception is thrown: `java.lang.RuntimeException: Bug. At least one of the value columns must be non null.`

**Comment by gregorydlogan** [comment]
@ts23 ping

**Comment by ts23** [comment]
@gregorydlogan Pong ... still looking at it ... making progress ... trying to sort startDate

**Comment by gregorydlogan** [comment]
Converting to a draft since I almost accidentally merged this today :D

**Comment by tyfranck** [comment]
I'll pick this one up. I don't have access to  @ts23 repository so will probably have to create a new pull request based on this.

**Comment by tyfranck** [comment]
I've created a new PR #3805 which should address the issue highlighted.  Please take a look. 
I'm going to close this PR.

**Comment by tyfranck** [comment]
> I tested this and the given title is set correctly. However, the given date is only reflected in the "Created" metadata filed not in the "Start date" field. Is this what you wanted?

Should now be fixed please see PR #3805

> Also, I cannot start the duplicate-event workflow without specifying a start date. If I try that the following exception is thrown: `java.lang.RuntimeException: Bug. At least one of the value columns must be non null.`

This is an UI issue with input set as date.  Should now be possible to run duplicate-event workflow without start date.

**Comment by tyfranck** [comment]
See PR #3805

**Pull request closed without merging**
