### PR TITLE
MH-12607 fast composer operations

### PR DESCRIPTION
**Pull request by karendolan**
MH-12607 fast-composer-operations: lossless concat, demux, multiencode, process-smil
This patch is created by @phoebem at HUDCE. 

Originally on bitbucket at https://bitbucket.org/opencast-community/opencast/pull-requests/1880
This patch has been been updated to the latest develop and rebased over pull #8.
This patch depends on https://github.com/opencast/opencast/pull/8

The purpose is increase the speed of transcoding tasks. Features include:

- Lossless concat for multipart chunked video source(same codec)

- Demux to deal with multipart files (epiphan)

- Multiencode to encode multiple files by encoding profile in one operation

- Process-smiltrack to concatenate trimmed clips and encode to multiple delivery formats by encoding profile in one operation

### CODE REVIEW

**Comment by staubesv** [comment]
@karendolan Please note that this PR currently has conflicts that must be resolved.

**Comment by karendolan** [comment]
@staubesv  thanks for the heads up. Github is different from Bitbucket by having issues based on timing of the commit. I've updated with a rebase on top of develop. (will need it again before merge, not doubt)

**Comment by karendolan** [comment]
@phoebem is looking into this, but we noticed that 1 junit (of the 50) in this pull has difficulty in some versions of ffmpeg. This is related to open FFmpeg defect that does not manifest in Ubuntu and Linux versions of ffmpeg but does in Apple versions.

FFmpeg tracking ticket: https://trac.ffmpeg.org/ticket/6375

The newer Apple ffmpegs have an issue with audio in certain processes and errors with "Too many packets buffered for output stream". Related to this Junit: ComplexCmdsEncoderEngineTest.testMultiEncodeSingleProfile:389

Works with Ubuntu versions of ffmpeg: 
ffmpeg version 3.2.4 Copyright (c) 2000-2017 the FFmpeg developers
  built with gcc 4.8 (Ubuntu 4.8.4-2ubuntu1~14.04.3)

Works with the version of ffmpeg used in OC CI test: 
ffmpeg version 3.4.1-static https://johnvansickle.com/ffmpeg/  Copyright (c) 2000-2017 the FFmpeg developers
  built with gcc 6.4.0 (Debian 6.4.0-10) 20171112

Works with older Mac OS X ffmpeg version:
ffmpeg version 3.0.1 Copyright (c) 2000-2016 the FFmpeg developers
built with Apple LLVM version 7.3.0 (clang-703.0.31)

Doesn't work in newer versions of Apple LLVM ffmpeg  (also in 3.4.1 built with Apple LLVM):
ffmpeg version 3.3.4 Copyright (c) 2000-2017 the FFmpeg developers
  built with Apple LLVM version 8.1.0 (clang-802.0.42)

Another ffmpeg ticket that references the issue (https://trac.ffmpeg.org/ticket/6472)
ffmpeg version N-86889-g1daacba91f Copyright (c) 2000-2017 the FFmpeg developers
  built with Apple LLVM version 8.1.0 (clang-802.0.42)

**Comment by phoebem** [comment]
The video in question ran to completion with ffmpeg3.4 on ubuntu, but prints a decoder error.
The error was absent from older ffmpegs.
I re-saved the file with 3.4 and the error is gone. Hopefully, this will work on more ffmpeg installations.
The command in question is:
       ffmpeg -i src/test/resources/audiovideo.mov -filter_complex "[0:v]scale=iw*.5:-1[ov0]" -map [ov0] -map 0:a -strict -2 -vcodec libx264 -b:a 48k -movflags faststart /tmp/av.m4v

As for the ffmpeg defect, it is present in 3.3 onwards and the workaround is to either use 3.2 or older or add 
-max_muxing_queue_size [some number bigger >= 1024]
to the encoding profiles.

**Comment by lkiesow** [comment]
I'm currently working on this, going through documentation and code. The documentation contains quite a few errors, but since I need to understand what's going on anyway, I'm in the process of updating it along the way. I'll provide a patch for that in the next days.

Still, going through it, I was already wondering:

- `multiencode` does basically replace both the `compose` and the `encode` operation handlers. Especially to `compose` it would seem like a drop-in replacement if we just rename it to `compose` and throw the old one away. Mid-term, we could then also get rid of `encode`. That would remove redundancies and would make the composer code simpler.
- `process-smil` sounds like it would completely replace the `videoeditor-*` modules since it will process the output of the admin interfaces video editor front-end. Is there any need for those modules? Or could they simply be replaced by this as well?

Any thoughts on this? Of course, we don't need to get all of it done as part of this pull request. But we might consider doing at least parts of it ;-)

**Comment by phoebem** [comment]
> On Jan 31, 2018, at 4:41 PM, Lars Kiesow <notifications@github.com> wrote:
> 
> I'm currently working on this, going through documentation and code. The documentation contains quite a few errors, but since I need to understand what's going on anyway, I'm in the process of updating it along the way. I'll provide a patch for that in the next days.
> 
Thanks so much for tackling this huge PR. I hope that there are not too many documentation bugs!
> Still, going through it, I was already wondering:
> 
> multiencode does basically replace both the compose and the encode operation handlers. Especially to compose it would seem like a drop-in replacement if we just rename it to compose and throw the old one away. Mid-term, we could then also get rid of encode. That would remove redundancies and would make the composer code simpler.
The code does have the limitation that the encoding profiles cannot contain complex filters as it would be very difficult to rewrite the command.
I don’t know if anyone is using them because if they do, they will have to use the original compose/encode.
I can rewrite the code so that in the case of a single target, multi-encode will not rewrite the command, this will work better as a replacement.

I notice that the sample adaptive encoding profile all have the same suffix -preview.mp4 and that the parallel encode version has different suffices. 
multiencode (and process-smil) have the same requirement as parallelencode - that all targets have different suffices. 
So the sample adaptive encoding profiles will have to change to use this code.
> process-smil sounds like it would completely replace the videoeditor-* modules since it will process the output of the admin interfaces video editor front-end. Is there any need for those modules? Or could they simply be replaced by this as well?
Yes. The video editor UI will only need to produce a SMIL file. There is no need for a separate videoeditor ffmpeg module to do encoding.
I’d like to add transitions (SMIL 2.0), so that process-smil can do theming and clip edits all in one command, but that would be way in the future.
> Of course, we don't need to get all of it done as part of this pull request. But we might consider doing at least parts of it ;-)
> 
I’d like to make the deadline for the next release!! :-)

**Comment by staubesv** [comment]
Hi @phoebem & @rute-santos While I am looking very much forwards to use this new WOHs in Opencast 5.0 and highly appreciate your work, I would like to share a concern:
I'm coming from the old Apple Podcast Producer world where it was possible to specify dependencies between "workflow operations" in "workflows" so that the "workflow engine" could run "workflow operations" in parallel (if not dependent on each other).
From that perspective, WOHs like multiencode look more like a workaround for our workflow engine missing the capability of doing so. If our workflow engine had that capability, you could simply use multiple WOH compose (and more importantly, any other WOHs) to achieve the same result (parallel execution) in a much more flexible way...

Example:

```
<operation type="cut video" id="cut"/>
<operation type="compose" id="compose-low-res" dependsOn="cut"/>
<operation type="compose" id="compose-high-res dependsOn="cut/>
```

-> No reason to execute the compose operations in sequence if dependencies are known. Works with any operation.

... but I see that it would be quite some work to make our workflow engine supporting this feature. Just hope we don't end up with a few heavily specialised WOHs which are kind of hard-coded workflow engine themselves.


Anyway... I'm looking forwards to use those new WOH!

**Comment by lkiesow** [comment]
@staubesv, true, that would be a nice feature but that's way outside of the scope of this pull request. It also seems like I misinterpreted what `multi-encode` does anyway and the way it's implemented is not unlike previous operations which will already spawn multiple jobs simultaneously if there are multiple input files.

In fact, going through the code a bit more, it seems like `multi-encode` does exactly the same thing `encode` does: For each input file, launch an encoding job which may produce multiple outputs. The only difference is the configuration: While `encode` will use the same encoding profile and mostly the same output tags and flavors, these can be specified separately with `multi-encode`.

@phoebem, there also seems to be a technical difference about which I'm not quite sure yet. Let's say that `multi-encode` is configured to use the following encoding profiles:

```
...ffmpeg.command = -i #{in.video.path} -c:v libx264 -filter:v yadif,scale=-2:288 -preset slower -crf 28 -r 25 -profile:v baseline \
  -tune film -pix_fmt yuv420p -movflags faststart -c:a aac -strict -2 -ar 22050 -ab 64k #{out.dir}/#{out.name}#{out.suffix}

...ffmpeg.command = -i #{in.video.path} -c:v libx264 -vf scale=800:-2 -preset slow -crf 34 -r 25 -profile:v high \
  -level 4.0  -pix_fmt yuv420p -tune animation -movflags faststart -c:a aac -strict -2 -ar 22050 -ab 64k #{out.dir}/#{out.name}#{out.suffix}

...ffmpeg.command = -i #{in.video.path} -c:v libx264 -crf 23 -maxrate 10000k -bufsize 10000k -profile:v high -level 4.0 -pix_fmt yuv420p \
  -x264opts keyint=25:min-keyint=25:no-scenecut -movflags +faststart \
  -filter:v scale='-2:min(ih\\,2160)',fps=fps=25 -c:a aac -b:a 96k -ac 1  -f mp4 #{out.dir}/#{out.name}#{out.suffix}
```

Skimming through the code, it seems like quite some effort goes into constructing a single FFmpeg command from these three encoding profiles. Especially in parsing filters and constructing a complex filter chain which will result in a command like this:

```
ffmpeg -nostats -i test.mp4 \
  \
  -filter_complex '[0:a]asplit=3[oa0][oa1][oa2];[0:v]split=3[ov00][ov01][ov02];[ov00]yadif,scale=-2:288[ov0];[ov01]scale=800:-2[ov1];[ov02]scale=-2:min(ih\,720),fps=fps=25[ov2]' \
  \
  -map [ov0] -map [oa0] -c:v libx264 -preset slower -crf 28 -r 25 -profile:v baseline -tune film -pix_fmt yuv420p -movflags faststart \
  -c:a aac -strict -2 -ar 22050 -ab 64k out-low.mp4 \
  \
  -map [ov1] -map [oa1] -c:v libx264 -preset slow -crf 34 -r 25 -profile:v high -level 4.0 -pix_fmt yuv420p -tune animation -movflags faststart \
  -c:a aac -strict -2 -ar 22050 -ab 64k out-vga-high.mp4 \
  \
  -map [ov2] -map [oa2] -c:v libx264 -crf 23 -maxrate 1200k -bufsize 2400k -profile:v high -level 4.0 -pix_fmt yuv420p -x264opts keyint=25:min-keyint=25:no-scenecut -movflags +faststart \
  -c:a aac -b:a 64k -ac 1 -f mp4 out-preview.mp4
```

It seems like it would be much less effort to just use the existing non-complex filter chains. It would also make the code a bit less error-prone and complex since more operations would be allowed in such a command. For example, you could even use complex filters if their names do not conflict. The resulting command from the profiles above would look somewhat like this (basically a concatination of the encoding profiles without the input options):

```
ffmpeg -nostats -i test.mp4 \
  \
  -filter:v yadif,scale=-2:288 \
  -c:v libx264 -preset slower -crf 28 -r 25 -profile:v baseline -tune film -pix_fmt yuv420p -movflags faststart \
  -c:a aac -strict -2 -ar 22050 -ab 64k out2-low.mp4 \
  \
  -filter:v scale=800:-2 \
  -c:v libx264 -preset slow -crf 34 -r 25 -profile:v high -level 4.0 -pix_fmt yuv420p -tune animation -movflags faststart \
  -c:a aac -strict -2 -ar 22050 -ab 64k out2-vga-high.mp4 \
  \
  -filter:v 'scale=-2:min(ih\,720),fps=fps=25' \
  -c:v libx264 -crf 23 -maxrate 1200k -bufsize 2400k -profile:v high -level 4.0 -pix_fmt yuv420p -x264opts keyint=25:min-keyint=25:no-scenecut -movflags +faststart \
  -c:a aac -b:a 64k -ac 1 -f mp4 out2-preview.mp4
```

And still, both of these methods suffer from the risk of breaking due to incompatibility in profiles, … Not only complex filters may be problematic but also general mapping or file input options. So in the end, I was wondering if it wouldn't be best to use the same method `encode` uses and let the user configure a proper FFmpeg command. That would be easier to understand for both devs and users. Especially in cases of profile errors. We also shouldn't lose any flexibility with that. Any thoughts on that?

Btb, apart from the documentation I did not yet have a look at the other new features. I hope that I have finished the review before the conference. That will give us enough time to get it in for Opencast 5.

**Comment by phoebem** [comment]
@staubesv 
@lkiesow  
First of all, thanks Lars, for looking at this giant PR.
 

> On Feb 3, 2018, at 1:46 PM, Lars Kiesow <notifications@github.com> wrote:
> 
> @staubesv <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_staubesv&d=DwMFaQ&c=WO-RGvefibhHBZq3fL85hQ&r=TJQ-1SstdvXiL3rEjhdQ2hxEsqTStc7HrWDIrl0lxlI&m=9E65G0ck5dVZqKTK2Cgc_fCvjWcENtLe1Gkh1YJM0uM&s=pNYWtTZDo9JqBFlekak9pvWPlKKn_PWMSKUEJ_84TN8&e=>, true, that would be a nice feature but that's way outside of the scope of this pull request. It also seems like I misinterpreted what multi-encode does anyway and the way it's implemented is not unlike previous operations which will already spawn multiple jobs simultaneously if there are multiple input files
> 
> In fact, going through the code a bit more, it seems like multi-encode does exactly the same thing encode does: For each input file, launch an encoding job which may produce multiple outputs. The only difference is the configuration: While encode will use the same encoding profile and mostly the same output tags and flavors, these can be specified separately with multi-encode.
> 
> @phoebem <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_phoebem&d=DwMFaQ&c=WO-RGvefibhHBZq3fL85hQ&r=TJQ-1SstdvXiL3rEjhdQ2hxEsqTStc7HrWDIrl0lxlI&m=9E65G0ck5dVZqKTK2Cgc_fCvjWcENtLe1Gkh1YJM0uM&s=Gzu30qPe5SYiYH_UThpltbbhe8vOZEuKB_tZ2nGD16Y&e=>, there also seems to be a technical difference about which I'm not quite sure yet. Let's say that multi-encode is configured to use the following encoding profiles:
> 
> ...ffmpeg.command = -i #{in.video.path} -c:v libx264 -filter:v yadif,scale=-2:288 -preset slower -crf 28 -r 25 -profile:v baseline \
>   -tune film -pix_fmt yuv420p -movflags faststart -c:a aac -strict -2 -ar 22050 -ab 64k #{out.dir}/#{out.name}#{out.suffix}
> 
> ...ffmpeg.command = -i #{in.video.path} -c:v libx264 -vf scale=800:-2 -preset slow -crf 34 -r 25 -profile:v high \
>   -level 4.0  -pix_fmt yuv420p -tune animation -movflags faststart -c:a aac -strict -2 -ar 22050 -ab 64k #{out.dir}/#{out.name}#{out.suffix}
> 
> ...ffmpeg.command = -i #{in.video.path} -c:v libx264 -crf 23 -maxrate 10000k -bufsize 10000k -profile:v high -level 4.0 -pix_fmt yuv420p \
>   -x264opts keyint=25:min-keyint=25:no-scenecut -movflags +faststart \
>   -filter:v scale='-2:min(ih\\,2160)',fps=fps=25 -c:a aac -b:a 96k -ac 1  -f mp4 #{out.dir}/#{out.name}#{out.suffix}
> Skimming through the code, it seems like quite some effort goes into constructing a single FFmpeg command from these three encoding profiles. Especially in parsing filters and constructing a complex filter chain which will result in a command like this:
> 
> ffmpeg -nostats -i test.mp4 \
>   \
>   -filter_complex '[0:a]asplit=3[oa0][oa1][oa2];[0:v]split=3[ov00][ov01][ov02];[ov00]yadif,scale=-2:288[ov0];[ov01]scale=800:-2[ov1];[ov02]scale=-2:min(ih\,720),fps=fps=25[ov2]' \
>   \
>   -map [ov0] -map [oa0] -c:v libx264 -preset slower -crf 28 -r 25 -profile:v baseline -tune film -pix_fmt yuv420p -movflags faststart \
>   -c:a aac -strict -2 -ar 22050 -ab 64k out-low.mp4 \
>   \
>   -map [ov1] -map [oa1] -c:v libx264 -preset slow -crf 34 -r 25 -profile:v high -level 4.0 -pix_fmt yuv420p -tune animation -movflags faststart \
>   -c:a aac -strict -2 -ar 22050 -ab 64k out-vga-high.mp4 \
>   \
>   -map [ov2] -map [oa2] -c:v libx264 -crf 23 -maxrate 1200k -bufsize 2400k -profile:v high -level 4.0 -pix_fmt yuv420p -x264opts keyint=25:min-keyint=25:no-scenecut -movflags +faststart \
>   -c:a aac -b:a 64k -ac 1 -f mp4 out-preview.mp4
> It seems like it would be much less effort to just use the existing non-complex filter chains. It would also make the code a bit less error-prone and complex since more operations would be allowed in such a command. For example, you could even use complex filters if their names do not conflict. The resulting command from the profiles above would look somewhat like this (basically a concatination of the encoding profiles without the input options):
> 
> ffmpeg -nostats -i test.mp4 \
>   \
>   -filter:v yadif,scale=-2:288 \
>   -c:v libx264 -preset slower -crf 28 -r 25 -profile:v baseline -tune film -pix_fmt yuv420p -movflags faststart \
>   -c:a aac -strict -2 -ar 22050 -ab 64k out2-low.mp4 \
>   \
>   -filter:v scale=800:-2 \
>   -c:v libx264 -preset slow -crf 34 -r 25 -profile:v high -level 4.0 -pix_fmt yuv420p -tune animation -movflags faststart \
>   -c:a aac -strict -2 -ar 22050 -ab 64k out2-vga-high.mp4 \
>   \
>   -filter:v 'scale=-2:min(ih\,720),fps=fps=25' \
>   -c:v libx264 -crf 23 -maxrate 1200k -bufsize 2400k -profile:v high -level 4.0 -pix_fmt yuv420p -x264opts keyint=25:min-keyint=25:no-scenecut -movflags +faststart \
>   -c:a aac -b:a 64k -ac 1 -f mp4 out2-preview.mp4
> And still, both of these methods suffer from the risk of breaking due to incompatibility in profiles, … Not only complex filters may be problematic but also general mapping or file input options. So in the end, I was wondering if it wouldn't be best to use the same method encode uses and let the user configure a proper FFmpeg command. That would be easier to understand for both devs and users. Especially in cases of profile errors. We also shouldn't lose any flexibility with that. Any thoughts on that?
> 
process-smil was designed and written first and multiencode is just a quick wf operation to use the same encoding mechanism without the trim clauses.
The features are designed for optimizing trim and post-trim operations.
I use a complex filter in multiencode because it is the same backend code as process-smil, which requires it.  
For our use case, the profiles have to work for process-smil, so removing complex filters would not help.
The special case for multiencode is when there is only one target if you want it to mimic encode.

It is true that extra care has to be taken in writing the encoding profiles. The only issues I encountered are profiles using complex filters and non-unique suffix.
I am hoping that documentation is enough. Most people don’t use complex filters, but the suffices may be a problem. 
One alternative is to create unique names if the profiles do not have unique suffices, but this may break things if the user actually wanted all the delivery files to have the same name (Same problem for parallelencode)
I have mixed different codecs for testing and haven't found incompatible profiles for encoding yet. If you can send me some examples, I will make a unit test and try and solve it.

The reason I use single output encoding profiles is for flexibility: so that multiple workflows with different ingest routes can share the same encoding profiles and the resulting videos will be the same. 
Workflow writers can pick any combination of delivery formats by name and does not need to know ffmpeg.

It also allows individual tagging of the output formats by profile name, so a particular output format can be targeted for further processing via source-tags.  
We use this mechanism post-trim for segmentation and thumbnail creation.
It is not as easy to tag individual files when they are hidden in the ffmpeg command.

When these were first created (MH 1.5/1.6), they were meant only as an alternative to videoeditor+encode and encode (before parallelencode)
When I started porting, I spent some time looking at parallelencode which allows the user to write the entire ffmpeg command for all delivery formats, it is very flexible and powerful.
Unfortunately I can’t use it to drive process-smil, and multi-encode is just process-smil lite, so I just left it as is.
> Btb, apart from the documentation I did not yet have a look at the other new features. I hope that I have finished the review before the conference. That will give us enough time to get it in for Opencast 5.
> 
Please let me know if there are other questions or if you need me to fix anything.

**Comment by staubesv** [comment]
@karendolan Please note that github reports conflicting files for this pull request.

**Comment by karendolan** [comment]
@staubesv thanks for the heads up. @phoebem  is in the process of updating the pull on the latest changes and will add a comment when this pull is ready for review again.

**Comment by phoebem** [comment]
Just rebased the branch on develop.
There was a conflict with modules/videoeditor-workflowoperation/src/main/java/org/opencastproject/workflow/handler/videoeditor/VideoEditorWorkflowOperationHandler.java
with a new config option, but that is resolved.

**Comment by karendolan** [comment]
@phoebem are you going to push the rebased version?

**Comment by staubesv** [comment]
@karendolan & @phoebem: Please note that this PR still (or again) has conflicts.

**Comment by lkiesow** [comment]
I think it's time to get this forward ;-)
For that, it might be a lot easier to split the main components into separate pull requests to get the less controversial ones in first.

I took the liberty to start with the demux operation. I have extracted the relevant parts from this pull request and rebased them on the current head of the develop branch.

The updated patch is here:

> https://github.com/lkiesow/opencast/tree/harvard-dce-f/MH-12607-fast-composer-operations-rebase

I have also added a few patches on top of this to fix a few issues I noticed when going through the code. Mainly these are:

- I fixed the documentation. The page was not integrated in mkdocs and not linked from the list of operations. I also removed all vendor references and finally fixed the broken encoding profile example.
- In ComposerServiceImpl, I've merged the new and old inspection code. It was mainly a duplication of old code with just a few small differences. The old code just needed some slight adjustments to be usable by demux as well.
- In the DemuxWorkflowOperationHandler I removed the JobInformation since it wasn't used for more than a wrapper for Tracks with no additional information. There were also more, smaller fixes.
- In EncoderEngine, I've tried to simplify the code.

What I haven't done so far but what's bothering me in the code is the `process(…)` method in the encoder, which is a slightly modified version of the `parallelProcess(…)` method which in turn is a slightly modified version of the old (and still existing) `process(…)` method.

My suggestion would be to modify the existing process to support multiple output files. For getting the output files, we also could do less guessing nd do something like this:

```
% ffmpeg -y -i ocr-test-very-small-no-audio-40sec-640x400.mkv -nostats -map 0:v "$(pwd)/x.mp4" -map 0:v "$(pwd)/y.mp4"  2>&1 | sed -n "s/^Output .* to '\(.*\)':$/\1/p"
/home/lars/videos/x.mp4
/home/lars/videos/y.mp4
```

@phoebem, if the current modifications would be ok for you, can you create a new pull request based on it? Note that the branch still contains commit ba9e9c68f which is just for testing the code and should not be part of the final merge. But we should also squash my commits…

**Comment by karendolan** [comment]
Hi @lkiesow , @phoebem  is working with Jody to get time to focus on your comment and move this pull forward again. We are very grateful for your work on it.

**Comment by lkiesow** [comment]
@phoebem, I continued to work on [the previously mentioned branch](https://github.com/lkiesow/opencast/tree/harvard-dce-f/MH-12607-fast-composer-operations-rebase) which now not only fixes the conflicts and includes the mentioned fixes but also includes pull request #161 which collapses the process methods in the encoder engine which makes the code a lot cleaner (Additional to that pull request, this code collapses parts of the demux code as well). 

Apart from minor tweaks, I think we could already merge in the demux operation like this.

If I'll find the time, I'll try to fix the conflicts and prepare a patch based on your concat improvements tomorrow.

If possible, can you take a look at the updated patch and let me know what you think about this update?

**Comment by lkiesow** [comment]
As we discussed earlier, this pull request is/will be split into separate ones for the separate features. Hence, I'll close this pull request.

**Pull request closed without merging**
