### PR TITLE
Update Opencast Studio to 2022-06-15 & Update Editor to Version 2022-06-15

### PR DESCRIPTION
**Pull request by mwuttke**
Update Opencast Studio to 2022-06-15 & Update Editor to Version 2022-06-15

For the full release notes of Opencast Studio, please take a look at:
https://github.com/elan-ev/opencast-studio/releases/tag/2022-06-15

Added:
- Keyboard tab navigation opencast#921

Changed:
- Improved tooltips opencast#931
- Removed useless Tooltips opencast#933
- Updated browser support table in README.md opencast#935 and opencast#936
- Make CSS use more variable to make it more customizable opencast#902
- Updated dependencies

For the full release notes of the Editor, please take a look at:
https://github.com/opencast/opencast-editor/releases/tag/2022-06-15

### Your pull request should…

* [x] have a concise title
* [ ] [close an accompanying issue](https://help.github.com/en/articles/closing-issues-using-keywords) if one exists
* [x] [be against the correct branch](https://docs.opencast.org/develop/developer/development-process#acceptance-criteria-for-patches-in-different-versions)
* [ ] include migration scripts and documentation, if appropriate
* [ ] pass automated tests
* [x] have a clean commit history
* [x] [have proper commit messages (title and body) for all commits](https://medium.com/@steveamaza/e028865e5791)

### CODE REVIEW

**Comment by lkiesow** [comment]
Editor version 2022-06-15 had a somewhat nasty bug that it failed to start a workflow iif only one editor workflow existed. The new release fixes that. Maybe it makes sense to update to that?

**Comment by gregorydlogan** [comment]
My understanding from the technical meeting this morning is that there's a newer version in 12.1.  Perhaps we should update to that instead?

**Comment by mliradelc** [comment]
Hi, thanks for the PR, can you update to the latest release?

**Comment by gregorydlogan** [comment]
Closing this pending a new pr with a new version.

**Pull request closed without merging**
