### PR TITLE
MH-12414, JPA spec states positional parameters are indexed from 1

### PR DESCRIPTION
**Pull request by JamesUoM**

### CODE REVIEW

**Comment by smarquard** [comment]
Seems like this:

      final Object value = params[i];

would give an out-of-bounds exception where i==params.length and what you should be doing instead is using 0 to params.length-1 but calling

    setParameter(i+1, ...)

? Or else

      final Object value = params[i-1];

**Comment by JamesUoM** [comment]
> Seems like this:
> 
> ```
>   final Object value = params[i];
> ```
> would give an out-of-bounds exception where i==params.length and what you should be doing instead is using 0 to params.length-1 but calling
> 
> ```
> setParameter(i+1, ...)
> ```

And that is exactly what we have in our code, I thought it would be neater to write the other way *sigh*

**Comment by KatrinIhler** [comment]
Maybe this should also be changed in persistencefn/Queries for consistency? (Although I have no idea how these two modules differ since they seem to contain the same functionality and are both used in Opencast...)

**Comment by JamesUoM** [comment]
> Maybe this should also be changed in persistencefn/Queries for consistency? (Although I have no idea how these two modules differ since they seem to contain the same functionality and are both used in Opencast...)

The other is (Entwine's) functional programming equivalent ... *sigh* ... I'll duplicate the changes.

**Review by KatrinIhler — APPROVED** [review]

**Pull request merged**
