### PR TITLE
Remove compose in favor of encode

### PR DESCRIPTION
**Pull request by lkiesow**
By now, the compose workflow operation is doing an exact subset of the
encode workflow operation which universally can be used as a drop-in
replacement.

In addition to the functionality of compose, encode supports parallel
encoding as well as the adaptive encoding profiles but these are
additional features and using the same configuration as compose, encode
works identical. It even uses mostly the same code internally.

So, there is no real reason to keep compose around any longer. That is
why this patch drops it.

### Your pull request should…

* [ ] have a concise title
* [ ] [close an accompanying issue](https://help.github.com/en/articles/closing-issues-using-keywords) if one exists
* [ ] be against the correct branch (features can only go into develop)
* [ ] include migration scripts and documentation, if appropriate
* [ ] pass automated testing
* [ ] have a clean commit history
* [ ] have proper commit messages (title and body) for all commits
* [ ] have appropriate tags applied

### CODE REVIEW

**Review by pascalseeland — APPROVED** [review]
Removing unneeded old code and simplyfing config for users is good.

**Comment by lkiesow** [comment]
@pascalseeland, did you test this? In that case, I could merge this.

**Comment by pascalseeland** [comment]
@lkiesow Yes, I did a checkout of the PR and it did encode my testvideos without issues.

**Comment by gregorydlogan** [comment]
Signing off on this given @lkiesow and @pascalseeland's results.

**Pull request merged**
