### PR TITLE
Sakai User Directory Dependencies

### PR DESCRIPTION
**Pull request by lkiesow**
This patch removes a number of seemingly unrelated dependencies from the
Sakai user directory.

### Your pull request should…

* [x] have a concise title
* [x] [close an accompanying issue](https://help.github.com/en/articles/closing-issues-using-keywords) if one exists
* [x] be against the correct branch (features can only go into develop)
* [x] include migration scripts and documentation, if appropriate
* [x] pass automated testing
* [x] have a clean commit history
* [x] have proper commit messages (title and body) for all commits
* [x] have appropriate tags applied

### CODE REVIEW

**Comment by lkiesow** [comment]
@smarquard, you are the only one I know who actually uses this module. Can you check that this does not break anything?

**Review by smarquard — APPROVED** [review]
Tested by cherry-picking the commit into our 8.x local branch and it starts up and works correctly, so all seems good.

**Comment by smarquard** [comment]
Did you want to target this at r/8.x as the related PRs are 8.x or fine to merge into develop as it's included anyway in #1341?

**Comment by lkiesow** [comment]
Thanks for noticing. Changed this to 8.x

**Pull request merged**
