### PR TITLE
Users in the admin ui filter can be reduced via regex now.

### LINKED ISSUE #1965: Allow filter users selectable in admin interface
Right now, when you open the admin interface, `/admin-ng/resources/events/filters.json` will be loaded and it contains a list of all available users in Opencast. Often, being able to select all of them is unnecessary and it would be nice if one could configure the admin interface to limit the users to those matching a configurable pattern.

### PR DESCRIPTION
**Pull request by marwyg**
With a regex configured in the 'custom.properties' file, the users listed in the filter selectbox can be reduced now. The filter is in the top right corner in the admin ui.

closes #1965

### CODE REVIEW

**Comment by gregorydlogan** [comment]
@marwyg broken tests.

@lkiesow I know we've got a pending discussion re: minor releases including non-breaking features.  Arguably, this is a feature not an enhancement.  Would you put this in `r/8.x`, or force it to go all the way into `develop`?

**Comment by gregorydlogan** [comment]
@marwyg in discussion today at the dev meeting we're going to punt this to `develop`.  Please repoint the target branch.

**Comment by marwyg** [comment]
@gregorydlogan Checks have passed and it points to `develop` now. 👍

**Comment by marwyg** [comment]
@gregorydlogan I took back the self assignment here, too. The PR is ready for review.

**Comment by Rillke** [comment]
I back-ported this to our r/8.x and the filter in the Admin UI stopped listing LTI users using a negative look-ahead.

```ini
org.opencastproject.adminui.filter.user.regex = ^(?!lti:).*$
```

Thank you.

**Comment by gregorydlogan** [comment]
@marwyg Do you want this in 9.x or should we leave it in develop?  I don't care, but it's ready to go either way.

**Comment by marwyg** [comment]
@gregorydlogan It doesn't matter so much, so let us leave it as it is. Please feel free to merge.

**Pull request merged**
