### PR TITLE
Add Mkdocs To Travis Builds

### PR DESCRIPTION
**Pull request by lkiesow**
This patch adds mkdocs builds for all three parts of the documentation
to the automated builds on Travis.

### CODE REVIEW

**Review by ziegenberg — APPROVED** [review]

**Review by gregorydlogan — APPROVED** [review]

**Comment by lkiesow** [comment]
Fixed merge conflict

**Comment by lkiesow** [comment]
Fixed new merge conflict

**Comment by gregorydlogan** [comment]
Hah, more conflicts sorry @lkiesow  :D

**Comment by lkiesow** [comment]
Done. By now, I'm a highly trained professional when it comes to fixing this pull request's merge conflicts ;-P

**Pull request merged**
