### PR TITLE
Use JSON instead of XACML for ACL templates

### PR DESCRIPTION
**Pull request by lkiesow**
This patch switches from XACML to JSON for the format of our ACL templates provided via `etc/acl/`. The format is identical to what the REST API uses. This makes it much easier to read, write and understand the templates.

### Your pull request should…

* [x] have a concise title
* [x] [close an accompanying issue](https://docs.opencast.org/develop/developer/#participate/development-process/#automatically-closing-issues-when-a-pr-is-merged) if one exists
* [x] [be against the correct branch](https://docs.opencast.org/develop/developer/development-process#acceptance-criteria-for-patches-in-different-versions)
* [x] include migration scripts and documentation, if appropriate
* [x] pass automated tests
* [x] have a clean commit history
* [x] [have proper commit messages (title and body) for all commits](https://medium.com/@steveamaza/e028865e5791)

### CODE REVIEW

**Comment by geichelberger** [comment]
What do you think about switching to Yaml?

```json
{
  "acl": {
    "ace": [
      {
        "role": "ROLE_USER",
        "action": "read"
      }
    ]
  }
}
```
vs 
```yaml
---
acl: 
  ace: 
  - role: "ROLE_USER"
    action: "read"
```

**Comment by lkiesow** [comment]
We already have a JSON parser. We don't have a YAML parser. So, I think that would be a larger update and this already improves the situation a lot.

**Review by Arnei — CHANGES_REQUESTED** [review]
Looks to generally work, and I'm also in favour of getting rid of XACML.

There are still a lot of comments and logging statements using "XACML". Those should probably say "JSON" now to avoid confusion? 

Could also remove the `throws JAXBException` from `removeAcl(File artifact)` (which is was never actually throwing anyway) to get rid of the JAXBException import statement.

**Comment by lkiesow** [comment]
Fixed that.

**Review by Arnei — APPROVED** [review]

**Comment by mtneug** [comment]
@Arnei, can this be merged?

**Pull request merged**
