### PR TITLE
MH-13326: No file/directory found when taking snapshot

### PR DESCRIPTION
**Pull request by rute-santos**

### CODE REVIEW

**Review by lkiesow — COMMENTED** [review]
Generally, this looks good and fixes the problem. The following is nitpicking and I can merge it like this if you want me to:

- all `toString` calls are superfluous
- The logger's internal formatting is preferable since it's just executed if necessary while the `format()` will always generate a formatted sting even if the logs are never produced due to a lower log level.

```java
logger.debug("Archiving manifest of media package {} version {}", mpId, version);
final String manifestFileName = format("manifest_%s_%s.xml", pmp.getMediaPackage().getIdentifier(), version);
```

**Comment by rute-santos** [comment]
Done! Thank you!
Rute

**Comment by smarquard** [comment]
Can we target this at 6.x? Seems like a bugfix.

**Comment by lkiesow** [comment]
I don't mind either way. It doesn't seem to be an urgent fix but it should also be a safe patch. @rute-santos, your call ;-)

**Comment by lkiesow** [comment]
Merged.
Thanks for the patch.

**Pull request merged**
