### PR TITLE
image preview added

### PR DESCRIPTION
**Pull request by Dhananjay-12**
### Your pull request should…

* [x] have a concise title
* [x] [close an accompanying issue](https://help.github.com/en/articles/closing-issues-using-keywords) if one exists
* [x] [be against the correct branch](https://docs.opencast.org/develop/developer/development-process#acceptance-criteria-for-patches-in-different-versions)
* [x] include migration scripts and documentation, if appropriate
* [x] pass automated tests
* [x] have a clean commit history
* [x] [have proper commit messages (title and body) for all commits](https://medium.com/@steveamaza/e028865e5791)

### CODE REVIEW

**Comment by Dhananjay-12** [comment]
I made the changes. Having confusion regarding ICLA

**Comment by lkiesow** [comment]
> Having confusion regarding ICLA

Apereo got your ICLA, since manual filing is involved on their end, it may take a while until the checks recognize this. Feel free to just ignore the bot.

**Review by lkiesow — APPROVED** [review]
Looks good.
All pull requests should go through the technical meeting once. It's a formality in this case, but since this is also not an urgent fix, something I don't want to just wave.

Given that next week is Christmas, there won't be anyone there and the next regular meeting should be on 3:15pm UTC, Tuesday, January 3, 2023. If you are interested, feel free to join, but you definitely don't have to.

I'll merge this after the meeting unless someone complains, which is… really, really unlikely.

**Comment by lkiesow** [comment]
Thanks for taking this on and fixing this!

**Comment by Dhananjay-12** [comment]
Thanks, I learned an lot 😄.
 Can you suggest me issues that I can work on (JavaScript if possible) ?

**Comment by Dhananjay-12** [comment]
Screenshot_20221222_011206


Hi , @lkiesow what should I do in this??

**Comment by lkiesow** [comment]
> Can you suggest me issues that I can work on (JavaScript if possible) ?

If you want modern JavaScript, I would actually suggest to look at two subprojects of Opencast specifically. Opencast Studio (web-based self-recording studio) and Opencast Editor (web-based video editor) have their own projects and are just imported when building Opencast itself. There are a number of open issues in the specific issue tracker, for example:

- https://github.com/elan-ev/opencast-studio/issues/941
- https://github.com/opencast/opencast-editor/issues/932

**Comment by lkiesow** [comment]
> Hi , @lkiesow what should I do in this??

I'm not exactly sure what your question is? If you are asking if you need to update anything in this pull request because Opencast has been updated, the answer is no. You don't need to as long as there is no conflict. Using `git` takes care of such merges.

**Pull request merged**
