### PR TITLE
MH-13240 Remove workflow service solr index

### PR DESCRIPTION
**Pull request by KatrinIhler**
This is a second try to remove the workflow service solr index (see #599). Be aware that this is a work in progress, and especially that tests haven't been adapted yet. The biggest hurdles currently are:

1. how to assert permissions efficiently when querying workflow instances
2. recreating the ability to build queries dynamically
3. how to handle queries for event or series metadata

_This work was sponsored by UCT._

### CODE REVIEW

**Comment by gregorydlogan** [comment]
Does it make sense to decline this for now and refile when it's ready?

**Comment by smarquard** [comment]
This is an important change, so I'd rather keep it here for visibility (and conflict checks) and re-invigorate some interest in finishing it.

**Comment by gregorydlogan** [comment]
@KatrinIhler any ETA for further development here?

**Comment by KatrinIhler** [comment]
@gregorydlogan Unfortunately not. SWITCH wanted to pick this up, but right nw they have other priorities.

**Comment by KatrinIhlerTest** [comment]
I'm gonna close this PR for now. Hopefully we can get this moving for the future, but at this time it doesn't make any sense to keep it open in my opinion.

**Comment by KatrinIhler** [comment]
I'm gonna close this for now, as there are unfortunately no resources to get this finished anytime soon. I have some regrets about how I went about this change, splitting this into smaller parts would have been more wise. I'll do better next time... But for now, it doesn't make sense to keep it hanging around.

**Pull request closed without merging**
