### PR TITLE
Delete extra colon in paella description plugin's localization key

### PR DESCRIPTION
**Pull request by Gao-Jun**
### Test plan:
* Set the locale of the browser to Germany (de) or Chinese (zh) or any other Opencast supported language except English.
* Open a video with paella player.
* Open `Description` tab.

### Expected behavior:
All localized strings should be shown.

### Actual behavior:
All attribute names are shown in localized text except **Date** (which should be **Datum**, already translated in `modules/engage-paella-player/src/main/paella-opencast/plugins/es.upv.paella.opencast.descriptionPlugin/localization/de-DE.json`). 
de

### Explain
In the localization files of descriptionPlugin, the key `Date` is misspelled as `Date:`.

This PR modify all files under `modules/engage-paella-player/src/main/paella-opencast/plugins/es.upv.paella.opencast.descriptionPlugin/localization/` , change `Date:` to `Date`, and remove extra colon form corresponding values.

Since I cannot find these files on crowdin, so I make a PR to do this.

* [ ] have a concise title
* [ ] [close an accompanying issue](https://help.github.com/en/articles/closing-issues-using-keywords) if one exists
* [ ] [be against the correct branch](https://docs.opencast.org/develop/developer/development-process#acceptance-criteria-for-patches-in-different-versions)
* [ ] include migration scripts and documentation, if appropriate
* [ ] pass automated tests
* [ ] have a clean commit history
* [ ] [have proper commit messages (title and body) for all commits](https://medium.com/@steveamaza/e028865e5791)

### CODE REVIEW

**Comment by lkiesow** [comment]
The file `en-US.json` is the main translation files. It will automatically be uploaded to Crowding and defines which keys are available there. All other files are then pulled from Crowdin. So, you can spare yourself the effort of modifying them manually. They will be overwritten.

Does it make sense to make this a pull request against `r/10.x`? This sounds like an issue which is also present in `10.x.

**Comment by Gao-Jun** [comment]
1. I checked crowdin again, still cannot find the `en-US.json` file whilch should be located in `modules/engage-paella-player/src/main/paella-opencast/plugins/es.upv.paella.opencast.descriptionPlugin`. Does I miss something or have not enough privileges?
2. This PR can be used with `r/10.x`. Actually, I first modified the code in `r/10.x`, and then use `develop` to cherry pick it.

**Comment by lkiesow** [comment]
> I checked crowdin again, still cannot find the en-US.json file 

Crowdin can be somewhat confusing at times. It will omit files from branches which have not been modified compared to the last branch. This particular file has not been modified for a long time. The last time it is mentioned is in 5.x. It should automatically pop up in 10.x again after this is merged, since then the source file has changed.

> This PR can be used with r/10.x. Actually, I first modified the code in r/10.x, and then use develop to cherry pick it.

Can you then quickly rebase this and target `r/10.x` with this pull request? The option for changing the pull request's target can be found if you hit `Edit` not to this pull request's title.

**Comment by Gao-Jun** [comment]
Well, now this PR's target is `r/10.x`.

**Review by lkiesow — APPROVED** [review]

**Pull request merged**
