### PR TITLE
Seperate user and non-user roles in the access policy modal in various details views in the Admin UI

### PR DESCRIPTION
**Pull request by Arnei**
To make access policies a little more intuitive to Admin UI users, this commit changes the way roles are displayed in views where roles with additional actions can be set (e.g in the event details view). It splits the role selection section into two parts. The first part is for selecting "users" (i.e user roles), the second part is for more technical non-user roles.

Furthermore, additional roles are provided to allow users to see either of the two role selection sections, to e.g. hide the non-user roles to certain users.

Furthermore, additional list provider settings allow for customizing default read/write rights when adding a new role, and for making the read/write rights read-only.

Example image:
Bildschirmfoto vom 2022-11-23 10-51-15

Sponsored by the University of Bern.

This PR is going against r/12.x solely because it was developed against that branch. If it is determined to be too breaking for 12, I would have no qualms rebasing it on 13 or develop.

@naweidner could you check if the changes you made in #4308 are still working? I might have broken them while resolving merge conflicts. 

* [~] have a concise title
* [~] [be against the correct branch](https://docs.opencast.org/develop/developer/development-process#acceptance-criteria-for-patches-in-different-versions)
* [ ] include migration scripts and documentation, if appropriate
* [ ] pass automated tests
* [ ] have a clean commit history
* [ ] [have proper commit messages (title and body) for all commits](https://medium.com/@steveamaza/e028865e5791)

### CODE REVIEW

**Comment by KatrinIhler** [comment]
I just rebased this change onto the new OC version for Bern and noticed that there are still usages of accessChanged and accessSave in the HTML files that I believe are now obsolete in 12.x.

**Comment by KatrinIhler** [comment]
@Arnei Conflicts!

**Comment by gregorydlogan** [comment]
Looking at the output of grepping for `accessChanged` and `accessSave` in a merged `r/12.x`, the remaining uses seem to be in the event and series controllers and html.  I'm assuming those should go prior to merging this?

**Comment by KatrinIhler** [comment]
When testing this for OC 12, we noticed that there were two bugs:

1. The event modal doesn't wait for the roleUserPrefix config to be loaded before sorting the policies, so sometimes they are sorted wrong, which will lead to display errors, which in the end causes a complaint of unsaved changes when trying to close the modal (all but the last part already occurred in the 11.x version of this, but was less problematic).
2. The user policies also need to be checked for unsaved changes when the modal is closed.

I already fixed them for Bern, so just ping me and I can point you to the right commits, or we can talk about how to handle this PR in general.

**Comment by gregorydlogan** [comment]
@Arnei ping

**Comment by Arnei** [comment]
I already talked to Katrin outside of the official Github records, I will get to this!

**Comment by gregorydlogan** [comment]
Finally got around to looking at this:

- ~When editing an event, the ACL template dropdown is blank~
- ~When editing an event, closing the editing modal generates a 'this page has unsaved changes` popup regardless of whether anything has changed, or whether the ACL editor has been viewed.~

Most importantly, creating an Opencast 'test' user, and assigning that user READ permissions for the event doesn't seem to actually make the event visible for that user, even after republishing.

Edit: After an Opencast restart, the template dropdown works and the modal is behaving.  I'm guessing I had a bad startup?

Edit2: This may be related (note that my config files are effectively default):
```
2023-02-06 14:04:01,043 | INFO  | (SearchServiceImpl:416) - Added media package `2bb702c1-4865-463c-85b3-4e2ad1d45c00` to the search index, using ACL `[ROLE_ADMIN is allowed to read, ROLE_ADMIN is allowed to write, ROLE_AAI_USER_test is allowed to read, ROLE_AAI_USER_test is allowed to write]`
```

**Comment by Arnei** [comment]
> Finally got around to looking at this:
> 
>     * ~When editing an event, the ACL template dropdown is blank~
> 
>     * ~When editing an event, closing the editing modal generates a 'this page has unsaved changes` popup regardless of whether anything has changed, or whether the ACL editor has been viewed.~
> 
> 
> Most importantly, creating an Opencast 'test' user, and assigning that user READ permissions for the event doesn't seem to actually make the event visible for that user, even after republishing.
> 
> Edit: After an Opencast restart, the template dropdown works and the modal is behaving. I'm guessing I had a bad startup?
> 
> Edit2: This may be related (note that my config files are effectively default):
> 
> ```
> 2023-02-06 14:04:01,043 | INFO  | (SearchServiceImpl:416) - Added media package `2bb702c1-4865-463c-85b3-4e2ad1d45c00` to the search index, using ACL `[ROLE_ADMIN is allowed to read, ROLE_ADMIN is allowed to write, ROLE_AAI_USER_test is allowed to read, ROLE_AAI_USER_test is allowed to write]`
> ```

Looks like the config file had some values set to non-default values (that made sense for Bern). Fixed.

**Pull request merged**
