### PR TITLE
Replace internal logger where possible

### LINKED ISSUE #5261: Drop unused internal logger
We still have a separate internal logger implementation which has some problems (see #5240) and which can likely be removed completely. See https://github.com/opencast/opencast/pull/5240#pullrequestreview-1615380222

We should investigate if we can remove the logger in question:
https://github.com/opencast/opencast/blob/fcb7f122d0f7977455933be8ccbb3f293827a4ca/modules/common/src/main/java/org/opencastproject/util/Log.java#L45

…and replace it with our default logger:
https://github.com/opencast/opencast/blob/fcb7f122d0f7977455933be8ccbb3f293827a4ca/modules/crop-ffmpeg/src/main/java/org/opencastproject/crop/impl/CropServiceImpl.java#L180

### PR DESCRIPTION
**Pull request by amritagg**
Replaced the old use of Log for logging purpose with the new Logger object.

This fixes #5261

### CODE REVIEW

**Comment by lkiesow** [comment]
`Test Opencast / build` failing is due to the issue fixed in pull request #5271. If you want to have the checks run automatically, feel free to rebase your pull request and include that patch. I'm also going to merge that patch shortly to avoid further test issues. If you haven't done it by then, I can also just rebase this pull request.

It would, however, be great if you can sign the ICLA. If you've done that and let us know, we can also resolve that faster than letting the Apereo Foundation sort out their internal paperwork (which sometimes can take a while).

In any case: Thank you for your contribution!

---

Finally, a hint about pull requests and helping out projects in the future (no need to take action. I'm fixing that momentarily):

- Please use a title and description explaining what the pull requests does, even if there is a linked issue. That really helps developers sorting through and reviewing pull requests as they don't need to cross-reference issues every time they look at a patch.
- GitHub supports [automatically closing issues if you reference them correctly](https://help.github.com/en/articles/closing-issues-using-keywords). Basically, just writing something like `Fixes #…` will do The keyword before the issue number is what's important.

**Comment by amritagg** [comment]
This was my first ever PR for open - source contribution that's why I don't know all these stuff. So thank you for letting me know about all these stuff. Will keep in mind from next time :)

**Comment by lkiesow** [comment]
Rebased on `develop`. I've also had to add a minor patch to the dependency declaration since our dependency checker was complaining:

```
[INFO] --- maven-dependency-plugin:3.6.0:analyze-only (analyze) @ opencast-incident-workflowoperation ---                                                                                                                                     
[ERROR] Used undeclared dependencies found:                                                                                                                                                                                                   
[ERROR]    org.slf4j:slf4j-api:jar:1.7.36:compile 
```

**Comment by lkiesow** [comment]
Hi @amritagg, the pull request looks good and we can merge it as soon as an ICLA has been submitted.
As mentioned above, you can do that via https://www.apereo.org/licensing/agreements/icla
If you have any questions about the process or the ICLA, please let us know.

**Comment by amritagg** [comment]
I have filled the form.

**Comment by lkiesow** [comment]
Thanks.
I can confirm that Apereo got the ICLA.
They might take some time to process it.
If you happen to file another pull request and someone asks, Just point them to this comment.

**Pull request merged**
