### PR TITLE
MH-12701 Paella: Localization files + crowdin config file

### PR DESCRIPTION
**Pull request by miesgre**
There are a few localization files for which the english source localization is missing and which are not added to the Crowdin configuration file (.crowdin.yml)

### CODE REVIEW

**Comment by lkiesow** [comment]
Just wondering if it would be possible to use 4 letter codes instead. Otherwise `en_US` and `en_UK` would probably overwrite each other (not sure which language would win)

**Comment by miesgre** [comment]
Lars, At the moment Paella uses two letter codes. We can have in opencast 4 letters codes and merge them to two letter codes to use in paella. But I'm not sure about which translation will be selected.

Perhaps this confuses people who expect one translation and see another if the translation for two regional languages are different.

**Comment by gregorydlogan** [comment]
@miesgre, are you guys using an translation tool upstream?  I'm wondering if it makes sense to piggy back the translation into Opencast's Crowdin account, in which case we would really want to transition everyone over to four letter codes.  You'd have to add that support upstream, but you would have the benefit of wider translations.

**Comment by staubesv** [comment]
@miesgre Note that Opencast already comes with target languages that have the same two-letter code. That implies Paella would not be capable of distinguishing those languages and the translations provided by translators would be useless. Agree with @gregorydlogan that Paella really should move to 4 letter codes, preferably the same ones Opencast already uses.

**Comment by miesgre** [comment]
@gregorydlogan, Paella is not using a translation tool. Maybe @turro could open a crowdin account for paella?  The files added to the opencast crowdin account in this PR are localization files for the paella plugins used in the opencast bindings, not all the localizations used by Paella. 

@turro plans to change to  4 letter code for Paella 6 release. But for now, paella supports only 2 letters codes. So, in fact we hace to decide what to do in the meantime. 

1. Do nothing 
Paella localization files are not added to the crowdin account 

2. Use two letter codes 
Add localization to the crowdin account using 2 letter codes. When paella 6 released, change to 4 letter codes.

3. Use 4 letter codes
Add  localization to the crowdin account using 4 letter codes.  When building paella, 4 letter s localization files will be collected and merged in 2 letter codes. This has the problem of how the translations on the same language will be merged. But, when Paella supports 4 letter codes, 4 letters localizations will be there.

 What option do you prefer? Or maybe another one?

**Comment by staubesv** [comment]
@miesgre and @gregorydlogan Whatever option we take, we will lose translations where multiple four-letter codes map to a single two-letter code (e.g. chinese traditional vs chinese simplified). I would go for option 4 so that at least the Crowdin stuff is setup correctly - not sure what Crowdin will do if you ask it for two-letter codes if there are multiple target languages with that code...

**Comment by gregorydlogan** [comment]
@miesgre I would go with the four letter code as well.  Of our current translations, there are only a few pairs which might cause issues, and chances are the users in that case aren't too bothered by mistranslated words in Paella.

Edit: The RM will likely have to do the merging as part of updating the committed translations I suppose.  But at least that gets the translations into Crowdin, and thus ready for when Paella 6 is available.  Speaking of which, I'm not following Paella development - is there a timeline for Paella 6 release?

**Pull request merged**
