### PR TITLE
Make Thumbnail Optional

### PR DESCRIPTION
**Pull request by lkiesow**
This patch makes the thumbnail generation in the video editor optional
since it causes major performance problems and/or failures on some
systems so that a number of Opencast adopters already ended up patching
or removing this in one way or another.

This does not change the default behavior of Opencast. With the default
configuration, this should make Opencast behave in the same way as
before.

### Your pull request should…

* [x] have a concise title
* [x] [close an accompanying issue](https://help.github.com/en/articles/closing-issues-using-keywords) if one exists
* [x] be against the correct branch (features can only go into develop)
* [x] include migration scripts and documentation, if appropriate
* [x] pass automated testing
* [x] have a clean commit history
* [x] have proper commit messages (title and body) for all commits
* [x] have appropriate tags applied

### CODE REVIEW

**Comment by mliradelc** [comment]
Hi Lars, I will review it now :)

-------

This should close https://opencast.jira.com/browse/MH-13346

**Review by mliradelc — APPROVED** [review]
Tested completely! works without issue.

Code is ok for me 😄

**Comment by mliradelc** [comment]
@lkiesow if it's all ok from your part I can merge it.

**Comment by lkiesow** [comment]
I'm happy with this.
Thanks for the review.
Merged.

**Pull request merged**
