### PR TITLE
Extended statistics export

### PR DESCRIPTION
**Pull request by krinnewitz**
This patch brings statistics CSV exports to the external API.
    
Using the new endpoint, it is possible to export event/series statistics along with all available meta data to CSV.
    
Pagination and filtering by meta data fields is supported.

As this extends the external API, the external API version is increased to v1.4.0.
    
This work is sponsored by ETH.

### CODE REVIEW

**Review by wsmirnow — COMMENTED** [review]
Looks good so far. Will try it next week.

**Comment by wsmirnow** [comment]
@krinnewitz can you separate the statistic-export-service api as an independent osgi module, please?

**Comment by krinnewitz** [comment]
> @krinnewitz can you separate the statistic-export-service api as an independent osgi module, please?

@wsmirnow just pushed a patch which splits it up.

**Comment by wsmirnow** [comment]
Thanks. Looks good for me.

**Review by wsmirnow — APPROVED** [review]

**Pull request merged**
