### PR TITLE
Quick-links in documentation

### LINKED ISSUE #1144: Quick-links in documentation
It would be nice to have a way to quickly link a specific documentation header by clicking on a link next to it like this:

Screenshot from 2019-10-12 21-29-00

This functionality shouldn't be hard to add to the documentation template in [opencast/docs/guides/admin/docs/javascript/extra.js](https://github.com/opencast/opencast/blob/develop/docs/guides/admin/docs/javascript/extra.js)

### PR DESCRIPTION
**Pull request by lkiesow**
This patch introduces quick-links to section headers to make it easier
to link to a specific part of our documentation.

This fixes #1144

### Your pull request should…

* [x] have a concise title
* [x] [close an accompanying issue](https://help.github.com/en/articles/closing-issues-using-keywords) if one exists
* [x] be against the correct branch (features can only go into develop)
* [x] include migration scripts and documentation, if appropriate
* [x] pass automated testing
* [x] have a clean commit history
* [x] have proper commit messages (title and body) for all commits
* [x] have appropriate tags applied

### CODE REVIEW

**Review by mliradelc — COMMENTED** [review]
I built the documentation, but I found that the icon is not the little chain that appears in #1144, instead, it's the paragraph icon. Is this correct?

Screenshot 2020-02-20 at 11 17 08

The functionality works

**Comment by lkiesow** [comment]
That's correct. I never claimed that I would use the chain ;-p
Nevertheless, I could switch to a different icon though.

**Comment by mliradelc** [comment]
> That's correct. I never claimed that I would use the chain ;-p
> Nevertheless, I could switch to a different icon though.

Ahh, ok I understand  😜, Code wise it seems ok and the documentation renders without issue, about the icon, this is a personal opinion, I prefer the little chain icon instead of the paragraph icon 🧐

**Comment by lkiesow** [comment]
@mliradelc, now it's 🔗

**Pull request merged**
