### PR TITLE
Upgraded to admin interface release 2024-06-06

### PR DESCRIPTION
**Pull request by lkiesow**
This patch updates the admin interface in Opencast to release 2024-06-06. A lot of improvements made it into this version as part of the BugBash. Thanks for all who participated!

You will find the release notes at:
https://github.com/opencast/opencast-admin-interface/releases/tag/2024-06-06

### Your pull request should…

* [x] have a concise title
* [x] [close an accompanying issue](https://docs.opencast.org/develop/developer/#participate/development-process/#automatically-closing-issues-when-a-pr-is-merged) if one exists
* [x] [be against the correct branch](https://docs.opencast.org/develop/developer/development-process#acceptance-criteria-for-patches-in-different-versions)
* [x] include migration scripts and documentation, if appropriate
* [x] pass automated tests
* [x] have a clean commit history
* [x] [have proper commit messages (title and body) for all commits](https://medium.com/@steveamaza/e028865e5791)

### CODE REVIEW

**Comment by Arnei** [comment]
Can this go into r/15.x? As far as I am aware there is no reason it can't.

**Comment by lkiesow** [comment]
I don't know and didn't test it. I also don't have time to do that testing right now. If you can try and let me know, I can redirect the pull request to `r/15.x`.

**Comment by Arnei** [comment]
Added this to my local `r/15.x`, clicked through all the views and modals I could find and everything behaves as expected. So I am in favor of redirecting this to `r/15.x`.

**Comment by lkiesow** [comment]
This is now targeting `r/15.x`

**Review by Arnei — APPROVED** [review]

**Comment by geichelberger** [comment]
Should the translations be fixed before merging into 15.x?

**Comment by lkiesow** [comment]
They won't be fixed for this release. The only option would be to skip the release.

I'm not entirely sure what's broken, how this was broken and who plans to do what to fix it. I would merge it like this, but as committer, you can block this pull request if you have any concerns. But then I would appreciate it if you have a plan on how to move on from here?

**Comment by geichelberger** [comment]
I won't block it. It was just a reminder that non-English- and German-speaking countries may not be happy with the new minor release.

**Comment by lkiesow** [comment]
In that case. Maybe just redirect it to `r/16.x` after all then?

**Comment by lkiesow** [comment]
Rebased this back to `r/16.x` so people don't get confused about the sudden language changes.

**Comment by lkiesow** [comment]
Merging this so that people have time for a final test on the public test servers.
We can still think about putting a new version into `r/15.x` with tomorrow's release (#5923).

**Pull request merged**
