### PR TITLE
Issue1068 DEBUG ONLY ServiceRegistryJpaImplTest persistent test fail on Travis

### PR DESCRIPTION
**Pull request by karendolan**
***DO NOT Merge***

This pull is only to debug the Travis CI junit error for ServiceRegistryJpaImplTest. Issue #1068 

It uses WARN logs for DEBUG lines to force-speed debugging. 

The only code change is make the ServiceRegistryJpaImpl.deactivate() wait for the dispatcher thread to terminate before re-queuing jobs from de-registered hosts.

```
    logger.warn("===========  De-activate service registry =============");

    // Wait for job dispatcher to stop *BEFORE* re-queuing jobs from unregistered hosts below
    if (scheduledExecutor != null) {
      try {
        logger.warn("Waiting for Dispatcher to terminate");
        scheduledExecutor.awaitTermination(10, TimeUnit.SECONDS);
      } catch (InterruptedException e) {
        logger.error("Error shutting down the Dispatcher", e);
      }
    }
```

### CODE REVIEW

**Comment by lkiesow** [comment]
Just for the record: You don't need a pull request for a build on Travis. It also builds commits to branches. You can even activate Travis on your own repository so you don't need to test on the community repository if you want that.

**Comment by karendolan** [comment]
> Just for the record: You don't need a pull request for a build on Travis. It also builds commits to branches. You can even activate Travis on your own repository so you don't need to test on the community repository if you want that.

My apologies for appropriating this space like this. I wanted to make sure this pull builds on the same build server environment and config as the rest of Opencast. That is the environment where the build was failing 1 out of 3 times. I cannot duplicate the build failure on other systems. The constraints of the build server appear to aggravate the underlying race condition in the ServiceRegistry deactivate().

**Comment by karendolan** [comment]
Closing this pull. Created a new pull for 7.x https://github.com/opencast/opencast/pull/1087/files

**Comment by lkiesow** [comment]
Don't apologize, I'm really happy that you took this up!
It was meant purely for informational purposes ;-)

**Pull request closed without merging**
