### PR TITLE
Spelling Fixes

### PR DESCRIPTION
**Pull request by gregorydlogan**
This pull request fixes a few spelling issues.

- 817c658 should be non-controversial, since it's all internal changes
- 13844ac might not be able to go into 10.x?  I've fixed the spelling in the visible text, but this does not alter the translation keys. 
 It's unclear what the rules mean IMO.  Can we fix spelling without altering the keys in a release branch?
- c248b19 fixes spelling in both the visible text *and* translation keys.  I wouldn't be surprised if this isn't allowed in 10.x, but I think it makes sense in context.

### Your pull request should…

* [x] have a concise title
* [ ] ~[close an accompanying issue](https://help.github.com/en/articles/closing-issues-using-keywords) if one exists~
* [ ] [be against the correct branch](https://docs.opencast.org/develop/developer/#development-process/#acceptance-criteria-for-patches-in-different-versions)
* [ ] ~include migration scripts and documentation, if appropriate~
* [x] pass automated tests
* [x] have a clean commit history
* [x] [have proper commit messages (title and body) for all commits](https://medium.com/@steveamaza/e028865e5791)

### CODE REVIEW

**Comment by lkiesow** [comment]
> 817c658 should be non-controversial, since it's all internal changes

Not entirely sure but I think this might actually modify the filters of the external API. Not that I think this would actually hurt anyone and I'm fine with merging this. We also didn't so far make a lot of noise about translations and I would leave it to the release managers to decide if we want to invalidate some translations :grin:

**Comment by gregorydlogan** [comment]
I feel like this is worth doing in 10.x, since the translations are easy to fix later.  But I'm obviously not the reviewer :)

**Comment by pascalseeland** [comment]
I don't think it will change the external API, as to my understanding, the external API maps the CANCELLED state to STOPPED (https://github.com/opencast/opencast/blob/2f783712e96264b9d23fc926b2a6f7a4e0a2a980/modules/elasticsearch-index/src/main/java/org/opencastproject/elasticsearch/index/event/Event.java#L116). 
I would vote for fixing the translation and the keys. I would vote that wrong text is the same as wrong code.

**Review by pascalseeland — APPROVED** [review]

**Comment by lkiesow** [comment]
Two devs approve → I approve :D

**Pull request merged**
