### PR TITLE
MH-12897 Improve visibility of selected segments in the videoeditor

### PR DESCRIPTION
**Pull request by KatrinIhler**
Improve visibility of the selected segments in the video editor by darkening the blue or red some more and increasing saturation a bit.

_This work is sponsored by ETH._

### CODE REVIEW

**Comment by gregorydlogan** [comment]
Should this go into 5.x?

**Comment by KatrinIhler** [comment]
@gregorydlogan Fine with me, rebased! :)

**Comment by gregorydlogan** [comment]
@staubesv is this something you're going to look at?  I can do this today/tomorrow.

**Comment by staubesv** [comment]
@gregorydlogan Will work on this today.

**Review by staubesv — APPROVED** [review]

**Pull request merged**
