### PR TITLE
Add "Create new event with metadata from another event" button to Admin UI

### PR DESCRIPTION
**Pull request by Arnei**
Adds a new button to the action column of the events table in the Admin UI. The button opens the "Create new event" modal and fills in information from the already existing event that is associated with the button. Fills in metadata, extended metadata and scheduling information.

### Your pull request should…

* [ ] have a concise title
* [ ] [close an accompanying issue](https://help.github.com/en/articles/closing-issues-using-keywords) if one exists
* [ ] [be against the correct branch](https://docs.opencast.org/develop/developer/development-process#acceptance-criteria-for-patches-in-different-versions)
* [ ] include migration scripts and documentation, if appropriate
* [ ] pass automated tests
* [ ] have a clean commit history
* [ ] [have proper commit messages (title and body) for all commits](https://medium.com/@steveamaza/e028865e5791)

### CODE REVIEW

**Comment by gregorydlogan** [comment]
Using the `ingest-addtrack.sh` helper script, then copying the event works, but the location column remains unpopulated.  Is this expected?

**Comment by Arnei** [comment]
That is not expected, will have a look.

**Comment by Arnei** [comment]
Nevermind, this is expected. The "Create new Event" dialog only permits entering a subset of the metadata that is normally available for edit in the event details view, and the "Copy metadata to new event button" adheres to that subset. And location is not in that subset.

**Comment by gregorydlogan** [comment]
Confusing, but acceptable I suppose :)

**Pull request merged**
