### PR TITLE
Remove Spring's Patched JDOM

### PR DESCRIPTION
**Pull request by lkiesow**
This patch removes the JDOM implementation taken from Spring and
replaces it – where necessary – with the default implementation
available from Maven Central.

### Your pull request should…

* [x] have a concise title
* [x] [close an accompanying issue](https://help.github.com/en/articles/closing-issues-using-keywords) if one exists
* [x] be against the correct branch (features can only go into develop)
* [x] include migration scripts and documentation, if appropriate
* [x] pass automated testing
* [x] have a clean commit history
* [x] have proper commit messages (title and body) for all commits
* [x] have appropriate tags applied

### CODE REVIEW

**Comment by mtneug** [comment]
The NOTICES file has still references to jdom.

**Comment by lkiesow** [comment]
Updated JDOM in the NOTICES file but really, that file needs to be regenerated.

**Comment by mtneug** [comment]
Still doesn't compile for me with a clean .m2 but with an other dependency:

```
[ERROR] Failed to execute goal on project opencast-userdirectory-ldap: Could not resolve dependencies for project org.opencastproject:opencast-userdirectory-ldap:bundle:9-SNAPSHOT: Failed to collect dependencies at org.springframework.ldap:org.springframework.ldap:jar:1.3.1.RELEASE -> org.apache.commons:com.springsource.org.apache.commons.lang:jar:2.5.0: Failed to read artifact descriptor for org.apache.commons:com.springsource.org.apache.commons.lang:jar:2.5.0: Could not transfer artifact org.apache.commons:com.springsource.org.apache.commons.lang:pom:2.5.0 from/to spring.io (https://repo.spring.io/plugins-release/): Authentication failed for https://repo.spring.io/plugins-release/org/apache/commons/com.springsource.org.apache.commons.lang/2.5.0/com.springsource.org.apache.commons.lang-2.5.0.pom 401 Unauthorized -> [Help 1]
```

**Comment by mtneug** [comment]
These are all the pom downloaded from `repo.spring.io` up until the error:

```
https://repo.spring.io/plugins-release/com/entwinemedia/common/functional/1.4.2/functional-1.4.2.pom
https://repo.spring.io/plugins-release/org/aopalliance/com.springsource.org.aopalliance/1.0.0/com.springsource.org.aopalliance-1.0.0.pom
https://repo.spring.io/plugins-release/org/apache/commons/com.springsource.org.apache.commons.lang/2.5.0/com.springsource.org.apache.commons.lang-2.5.0.pom
https://repo.spring.io/plugins-release/org/apache/commons/com.springsource.org.apache.commons.logging/1.0.4/com.springsource.org.apache.commons.logging-1.0.4.pom
https://repo.spring.io/plugins-release/org/apache/commons/com.springsource.org.apache.commons.logging/1.1.1/com.springsource.org.apache.commons.logging-1.1.1.pom
https://repo.spring.io/plugins-release/org/jboss/security/jboss-sunxacml/2.0.5.final/jboss-sunxacml-2.0.5.final.pom
https://repo.spring.io/plugins-release/org/jboss/security/jboss-xacml-project/2.0.5.final/jboss-xacml-project-2.0.5.final.pom
https://repo.spring.io/plugins-release/org/jboss/security/jboss-xacml/2.0.5.final/jboss-xacml-2.0.5.final.pom
https://repo.spring.io/plugins-release/org/mnode/ical4j/ical4j/3.0.6-patched/ical4j-3.0.6-patched.pom
https://repo.spring.io/plugins-release/org/opencastproject/android-mms/1.2/android-mms-1.2.pom
https://repo.spring.io/plugins-release/org/sakaiproject/nakamura/javax.activation-mail/1.1.1.1.4.2-1.4.2/javax.activation-mail-1.1.1.1.4.2-1.4.2.pom
https://repo.spring.io/plugins-release/org/springframework/ldap/org.springframework.ldap/1.3.1.RELEASE/org.springframework.ldap-1.3.1.RELEASE.pom
https://repo.spring.io/plugins-release/org/springframework/org.springframework.aop/2.5.6.SEC01/org.springframework.aop-2.5.6.SEC01.pom
https://repo.spring.io/plugins-release/org/springframework/org.springframework.aop/3.0.5.RELEASE/org.springframework.aop-3.0.5.RELEASE.pom
https://repo.spring.io/plugins-release/org/springframework/org.springframework.asm/3.0.5.RELEASE/org.springframework.asm-3.0.5.RELEASE.pom
https://repo.spring.io/plugins-release/org/springframework/org.springframework.beans/2.5.6.SEC01/org.springframework.beans-2.5.6.SEC01.pom
https://repo.spring.io/plugins-release/org/springframework/org.springframework.beans/3.0.5.RELEASE/org.springframework.beans-3.0.5.RELEASE.pom
https://repo.spring.io/plugins-release/org/springframework/org.springframework.context/2.5.6.SEC01/org.springframework.context-2.5.6.SEC01.pom
https://repo.spring.io/plugins-release/org/springframework/org.springframework.context/3.0.5.RELEASE/org.springframework.context-3.0.5.RELEASE.pom
https://repo.spring.io/plugins-release/org/springframework/org.springframework.core/2.5.6.SEC01/org.springframework.core-2.5.6.SEC01.pom
https://repo.spring.io/plugins-release/org/springframework/org.springframework.core/3.0.5.RELEASE/org.springframework.core-3.0.5.RELEASE.pom
https://repo.spring.io/plugins-release/org/springframework/org.springframework.expression/3.0.5.RELEASE/org.springframework.expression-3.0.5.RELEASE.pom
https://repo.spring.io/plugins-release/org/springframework/org.springframework.transaction/3.0.5.RELEASE/org.springframework.transaction-3.0.5.RELEASE.pom
https://repo.spring.io/plugins-release/org/springframework/osgi/org.springframework.osgi.core/1.2.1/org.springframework.osgi.core-1.2.1.pom
https://repo.spring.io/plugins-release/org/springframework/osgi/org.springframework.osgi.io/1.2.1/org.springframework.osgi.io-1.2.1.pom
```

**Comment by lkiesow** [comment]
@mtneug: Sorry, but that's unrelated to this patch. I'm not claiming to remove everything that relias on the Spring repo. I claim to remove the patched JDOM ;-)

Also note that the fact that it downloads things from there does not mean that it's the only source. For example, android-mms is our artifact and does live in our maven repository from which it would be downloaded if maven wouldn't get it from Spring

**Review by SijmenHuizenga — APPROVED** [review]
LGTM!

**Comment by mtneug** [comment]
@lkiesow fair enough. I will create a new issue.

**Pull request merged**
