### PR TITLE
url query string incorrect

### PR DESCRIPTION
**Pull request by kristofkeppens**
The url query string should use ? instead of ; to work in an lti context.

### CODE REVIEW

**Comment by lkiesow** [comment]
Looks good. Two open questions:

- Does it make sense to already have this in the 6.x documentation?
- Does it make sense to change `tool=engage/theodul/ui/core.html?id=MEDIAPACKAGEID` to `tool=/play/MEDIAPACKAGEID`? In 7.x, this will automatically redirect you to the configured default player even if you later decide to change it.

**Comment by kristofkeppens** [comment]
This change is definitely relevant for 6.x as well, you need to add the tool parameter the same way then. 
For 7.x it would be an improvement to use the /play/MEDIAPACKAGEID instead of the player specific url. I wasn't aware of this change in 7.x, but good to know so I can change the LTI deep linking integration to use this url as well.

Should I make 2 different pull requests, 1 to develop and 1 to 6.x to add this?

**Comment by lkiesow** [comment]
Please do if you don't want me to do the work ;-)

**Comment by kristofkeppens** [comment]
@lkiesow I'll make a new PR for the 6.x branch without the /play/MEDIAPACKAGE url. This change can go into r/7.x as well.

**Review by lkiesow — APPROVED** [review]

**Comment by lkiesow** [comment]
Thanks for the patch. Merged in `develop` and cherry-picked to `r/7.x`

**Pull request merged**
