### PR TITLE
MH-12869 Remove superfluous playback tool

### PR DESCRIPTION
**Pull request by staubesv**
See discussion and proposal on https://groups.google.com/a/opencast.org/forum/#!topicsearchin/dev/remove$20playback/dev/U-Io91-xA_U

Now looks like:

screen shot 2018-05-07 at 17 05 22

### CODE REVIEW

**Comment by CGreweling** [comment]
@staubesv so the proposal has passed. I will have a look and merge it in.

**Comment by CGreweling** [comment]
@staubesv  Works. 
But now we see th Preview symbol as an eye when the event ist published. This should than be an cut icon for the editor. As it is now its a little confusing.
preview
Maybe this schould be done in another PR ?

**Comment by staubesv** [comment]
@CGreweling Good point. The cut icon is currently used to indicate that the event has an open comment "Requires Cutting". If we would just always show the cut icon, that additional information would get lost.

I definitely missed to adapt the tooltip, though.

What would you suggest considering the "eye" vs "cut" icons?

**Comment by staubesv** [comment]
Hmm... What would you think of always using the cut icon but in different shades (depending on whether there is an open comment)?

**Comment by staubesv** [comment]
Hi @CGreweling I've played around with the icon and ended up with the following:

screen shot 2018-05-17 at 15 17 11

Sorry, I'm quite "un-knowledgable" if it comes to CSS so that is about the best I could achieve ;-)

The red dot indicates the the event "needs cutting". The tooltip does explain that.

**Pull request merged**
