### PR TITLE
MH-12274 Ingest REST endpoint trace logs added

### PR DESCRIPTION
**Pull request by wsmirnow**
solve github issue #5 as well

### CODE REVIEW

**Comment by lkiesow** [comment]
Tip: A pull request already functions as an issue on Github. No need to create two tickets ;-P

**Comment by smarquard** [comment]
There are some changes here that are not just logging, for example adding UTF-8 explicitly and one or two other things. I'd suggest either moving those to a separate PR, or adding the description of what's changed to the JIRA and note the functional impact here.

**Comment by wsmirnow** [comment]
@smarquard, do we handle any other encoding as UTF-8 in Opencast? Yes this may be a bug in previous versions of Opencast where the default platform encoding was used. But the other changes are realy trivial. Do you want to seperate this commit yet?

**Comment by smarquard** [comment]
I think explicitly setting the encoding to UTF-8 whenever possible is the safest thing to do, so this is a good change. I would suggest just updating the commit title / description and noting the change in the JIRA as well.

**Comment by wsmirnow** [comment]
Ok , I will change the ticket metadata.

**Comment by wsmirnow** [comment]
@smarquard as you have took a look into this patch, can you take the review please?

**Comment by wsmirnow** [comment]
moved to [BitBucket](https://bitbucket.org/opencast-community/matterhorn/pull-requests/1594)

**Pull request closed without merging**
