### PR TITLE
WIP: Added missing documentation for the restore from remote WOH

### PR DESCRIPTION
**Pull request by ebbertd**
This PR adds the missing documentation for the restore-from-remote WOH

### CODE REVIEW

**Comment by ebbertd** [comment]
This PR adds the missing documentation for the restore-from-remote WOH. However, I'm not sure if I'm missing some details on how to use it. I only spotted that it was missing.

**Comment by gregorydlogan** [comment]
@ebbertd, now I know why I was confused on list: That workflow operation handler no longer exists.  I unified offloading and restoring to a single workflow operation handler (move-storage).  Are there references to the old one that I've missed?

**Comment by ebbertd** [comment]
@gregorydlogan Yes, you missed the example workflow. https://github.com/opencast/opencast/blob/develop/etc/workflows/restore.xml#L39

**Comment by gregorydlogan** [comment]
@ebbertd Bah, thanks for pointing that out!  I've directly fixed it in develop.  Are there any other references you can find?

**Comment by ebbertd** [comment]
No, couldn't find any more and therefore I will close this.

**Pull request closed without merging**
