### PR TITLE
MH-13123: Update paella player 6.0.2

### PR DESCRIPTION
**Pull request by miesgre**

### CODE REVIEW

**Comment by miesgre** [comment]
@staubesv I sent this PR against `develop`  before `r/6.x` cut. Can this be integrated info `r/6.x` or Do I need to send a new PR against `r/6.x`?

**Comment by staubesv** [comment]
@miesgre Sorry for not being fast enough considering the review... as upgrading Paella from 6.0.0 to 6.0.1 seems a maintenance upgrade, you can redirect this PR to r/6.x. For doing so, press the "Edit" button on this page and chose r/6.x as target branch (no need to create a new PR).

**Comment by miesgre** [comment]
@staubesv Don't merge this PR yet. I found a bug un paella 6.0.1
Put this on hold until the bug in paella is fixed.

**Comment by miesgre** [comment]
@staubesv You can continue the review. Thanks.

**Review by staubesv — APPROVED** [review]

**Pull request merged**
