### PR TITLE
conditionally encode 1440p in profile.adaptive-parallel.http

### LINKED ISSUE #4871: include 1440p in profile.adaptive-parallel.http?
**Describe the bug**

I'm not sure if this is a bug or intended behaviour, but **studio** seem to be superfluous  in the ffmpeg-command to encode 1440p in `/opencast/etc/encoding/opencast.properties` . This prevents encoding of 1440p. I'm happy to provide a pull request.

**To Reproduce**

Videos are not encoded in 1440p, even if the source material is 4k

**Expected behavior**

4k videos should be encoded in 480p, 720p, 1080p, 1440p and 2160p

**Diff of /opencast/etc/encoding/opencast.properties**

``` # The video distribution profile, optimized for parallel encoding of multiple
 # qualities for adaptive streaming
-profile.adaptive-parallel.http.name = parallel encode 480p and 720p and conditionally 1080p and 2160p qualities for adaptive streaming
+profile.adaptive-parallel.http.name = parallel encode 480p and 720p and conditionally 1080p, 1440p and 2160p qualities for adaptive streaming
 profile.adaptive-parallel.http.input = visual
 profile.adaptive-parallel.http.output = visual
 profile.adaptive-parallel.http.jobload = 4
@@ -44,7 +44,7 @@ profile.adaptive-parallel.http.ffmpeg.command.if-width-or-height-geq-1600-900 =
     -c:a aac -b:a 192k -ac 2 \
     -max_muxing_queue_size:a 1024 \
     -movflags faststart #{out.dir}/#{out.name}#{out.suffix.1080p-quality}
-profile.studio.adaptive-parallel.http.ffmpeg.command.if-width-or-height-geq-2440-1260 = \
+profile.adaptive-parallel.http.ffmpeg.command.if-width-or-height-geq-2440-1260 = \
   -filter:v scale=2560:2560:force_original_aspect_ratio=decrease:force_divisible_by=2,fps=25 \
     -pix_fmt yuv420p \
     -c:v libx264 -profile:v high -level 5.0 -crf 23 \
```

**Server environment:**
 - OS: Arch Linux
 - Distribution: allinone
- Installation method: container
 - Version 13.4

### PR DESCRIPTION
**Pull request by hercherf**
This fixes https://github.com/opencast/opencast/issues/4871

### CODE REVIEW

**Comment by hercherf** [comment]
i just filed the Individual Contributor License Agreement - can someone please retrigger the check?

**Review by Arnei — APPROVED** [review]
Makes sense and works, approved.

**Comment by Arnei** [comment]
Regarding the ICLA, that is manually reviewed by real people, so it may take a couple of days.

**Comment by mliradelc** [comment]
@lkiesow Do you know how to check the ICLA manually? I can't trigger the check by myself

**Comment by lkiesow** [comment]
Seems like someone triggered that a few times :D
But, yes, the ICLA is filed with Apereo
You can check at http://licensing.apereo.org

**Pull request merged**
