### PR TITLE
Update paella player to paella 6.5.5

### PR DESCRIPTION
**Pull request by miesgre**
### Your pull request should…

* [ ] have a concise title
* [ ] [close an accompanying issue](https://help.github.com/en/articles/closing-issues-using-keywords) if one exists
* [ ] [be against the correct branch](https://docs.opencast.org/develop/developer/development-process#acceptance-criteria-for-patches-in-different-versions)
* [ ] include migration scripts and documentation, if appropriate
* [ ] pass automated tests
* [ ] have a clean commit history
* [ ] [have proper commit messages (title and body) for all commits](https://medium.com/@steveamaza/e028865e5791)

### CODE REVIEW

**Review by mliradelc — APPROVED** [review]
Tested, works without problems.

**Comment by lkiesow** [comment]
Miguel filed an ICLA. We can probably merge this.
Event though Apereo hasn't confirmed the submission, they definitely received it.

**Comment by mliradelc** [comment]
Miguel, can you point your PR to 10.x branch? So Paella 7 will be for opencast 11 :)

**Comment by miesgre** [comment]
> Miguel, can you point your PR to 10.x branch? So Paella 7 will be for opencast 11 :)

I can do ti, but this PR is for update paella to 6.5.5.  If you want I can do the same for #3162 to add paella 7 bundle to opencast 11.

**Comment by miesgre** [comment]
> Miguel, can you point your PR to 10.x branch? So Paella 7 will be for opencast 11 :)

I think It's done. Can you check if I do it correctly?

**Comment by mliradelc** [comment]
The PR has conflicts? can you rebase against 10.x?

**Comment by miesgre** [comment]
> The PR has conflicts? can you rebase against 10.x?

I rebased it against r/10.x branch and I don't know why github-actions says it has conflicts, I think it hasn't conflicts

**Pull request merged**
