### PR TITLE
Use UTF-8 for config files

### PR DESCRIPTION
**Pull request by mtneug**
By default, config files are assumed to be encoded using ISO-8859-1 (latin1). This changes that to UTF-8.

### Your pull request should…

* [ ] have a concise title
* [ ] [close an accompanying issue](https://help.github.com/en/articles/closing-issues-using-keywords) if one exists
* [ ] be against the correct branch (features can only go into develop)
* [ ] include migration scripts and documentation, if appropriate
* [ ] pass automated tests
* [ ] have a clean commit history
* [ ] [have proper commit messages (title and body) for all commits](https://medium.com/@steveamaza/e028865e5791)

### CODE REVIEW

**Review by lkiesow — COMMENTED** [review]
- Do we actually need to include this in the fileinstall configurations?
- If we include it in the `custom.properties`, properties in there are still encoded `latin1` aren't they?
- Would it make sense to set this in the `config.properties`? I vaguely remember that one to be loaded before the other ones. Maybe that would cause them to be loaded as UTF-8 Already?

**Comment by mtneug** [comment]
1. This setting is a fileinstall setting. So why not? I'm not sure if files other than property files are then loaded with UTF-8, but it shouldn't hurt.
2. Probably.
3. Probably. `config.properties` includes `custom.properties` and has fileinstall settings for the general configuration files. As I understand it, `config.properties` is generated automatically by Maven. I would have to take a look at how I would change that.

**Comment by lkiesow** [comment]
Take a look at https://github.com/opencast/opencast/blob/develop/assemblies/resources/system.properties.append
Maybe we could even include it there.

> This setting is a fileinstall setting. So why not? I'm not sure if files other than property files are then loaded with UTF-8, but it shouldn't hurt.

More configuration isn't always better. Especially if we want everything to be UTF-8 anyway. If we can just set a global default instead of setting it  over and over again, I think that would be preferable.

**Comment by mliradelc** [comment]
@mtneug Should I continue with the review?  Because I can merge it before the FF.

**Comment by lkiesow** [comment]
@mliradelc, if you want to take it from here, feel free to unassign me and assign yourself. I don't mind doing one less review.

**Comment by mliradelc** [comment]
> Take a look at https://github.com/opencast/opencast/blob/develop/assemblies/resources/system.properties.append
> Maybe we could even include it there.
> 
> > This setting is a fileinstall setting. So why not? I'm not sure if files other than property files are then loaded with UTF-8, but it shouldn't hurt.
> 
> More configuration isn't always better. Especially if we want everything to be UTF-8 anyway. If we can just set a global default instead of setting it over and over again, I think that would be preferable.

@mtneug What do you think about to make it global?

**Comment by gregorydlogan** [comment]
@mtneug @mliradelc is this still a WIP, or are we still waiting on something?

**Comment by mtneug** [comment]
Current status:

* all config files directly in `etc` except for `custom.properties` should now use UTF-8 as configured in `system.properties`
* files in `etc/acl`, `etc/branding`, `etc/security`, `etc/workflows`, `etc/statistics` should already be loaded in the correct encoding (probably UTF-8). These are mainly XML files that specify an encoding. `etc/statistics` contains JSON files that I assume are loaded in UTF-8.
* files in `etc/email`, `etc/encoding`, `etc/feeds`, `etc/listproviders` are now loaded in UTF-8. This required a code change since we load the property files ourselves.
* Property files read in by the `execute-once` and `execute-many` operations now also use UTF-8.

There are some other locations we load in property files, but I'm unsure about those. I leave them out for now.

**Comment by lkiesow** [comment]
You mentioned in the technical meeting, that some code already converts the properties internally. How does this effect code like:

```
modules/dictionary-hunspell/src/main/java/org/opencastproject/dictionary/hunspell/DictionaryServiceImpl.java:98:      binary = new String(binary.getBytes("ISO-8859-1"), "UTF-8");
```

Does this still work?

**Comment by mtneug** [comment]
> Does this still work?

No, and thanks for reminding me to test this again. I thought I tested it, but apparently not. The conversion is no longer needed and interpreting it as non-UTF-8 will lead to wrong characters.

**Pull request merged**
