### PR TITLE
Bump Google OAuth library version

### PR DESCRIPTION
**Pull request by gregorydlogan**
Bumping the library version to remove a security issue within it.

﻿### Your pull request should…

* [x] have a concise title
* [ ] ~[close an accompanying issue](https://help.github.com/en/articles/closing-issues-using-keywords) if one exists~
* [ ] [be against the correct branch](https://docs.opencast.org/develop/developer/development-process#acceptance-criteria-for-patches-in-different-versions)
* [ ] ~include migration scripts and documentation, if appropriate~
* [x] pass automated tests
* [x] have a clean commit history
* [x] [have proper commit messages (title and body) for all commits](https://medium.com/@steveamaza/e028865e5791)

### CODE REVIEW

**Comment by mliradelc** [comment]
Greg I was checking this PR but have build issues

**Comment by gregorydlogan** [comment]
Yep, I just haven't gotten back to this. On top of your error, it won't actually boot right since it needs a package whitelisted in `custom.properties`

**Comment by mliradelc** [comment]
@gregorydlogan what we will do with this PR?

**Comment by gregorydlogan** [comment]
I'll rebase it into 11.x when I get time.

**Comment by lkiesow** [comment]
I converted this to a draft for now to make it clear that this is not ready yet

**Comment by gregorydlogan** [comment]
I'm going to decline this until I have time to work on it.

**Pull request closed without merging**
