### PR TITLE
Paella 7: Use master tracks in HLS serverless mode

### PR DESCRIPTION
**Pull request by miesgre**
When using HLS serverless with multiquality/multilanguage. ffmpeg creates multiple m3u8 files for different qualities/languages and one master m3u8 file. The master is marked with master=true property.
Paella was not using that property and was causing problems.

This PR solves it. Paella now selects the track with master=true and discards the rest.

### Your pull request should…

* [x] have a concise title
* [ ] [close an accompanying issue](https://help.github.com/en/articles/closing-issues-using-keywords) if one exists
* [ ] [be against the correct branch](https://docs.opencast.org/develop/developer/development-process#acceptance-criteria-for-patches-in-different-versions)
* [ ] include migration scripts and documentation, if appropriate
* [x] pass automated tests
* [x] have a clean commit history
* [x] [have proper commit messages (title and body) for all commits](https://medium.com/@steveamaza/e028865e5791)

### CODE REVIEW

**Comment by yokoul** [comment]
Successfully tested on my side. Paella 7 now show correctly multiple streams HLS sources and display selected tag in audio menu.

**Review by yokoul — APPROVED** [review]
Successfully tested on my side. Paella 7 now show correctly multiple streams HLS sources and display selected tag in audio menu.

**Comment by mliradelc** [comment]
Can this solve #3774?

**Comment by miesgre** [comment]
> Can this solve #3774?

No. Using wowza to distribute files in multiple languages requires modifying the distribution operation to write the corresponding SMIL file.

But since opencast 9, opencast supports HLS without wowza and you could use the encode/multiencode operation to generate the necessary HLS files with ffmpeg. In fact @yokoul, use these operations to generate videos with up to 7 languages.

When you use ffmpeg to generate the necessary HLS files, it usually generates multiple m3u8 files, one for each quality and language plus the master file. In the case you have a video with 3 qualities and 7 languages you would have 11 m3u8 files (3 with the different qualities, 7 of the different languages and the master file). Although you have to distribute them all, the operation marks as master = true, only the master to be able to distinguish it.

Paella must use the mark as master, this pull request does exactly that.

**Review by mliradelc — COMMENTED** [review]
From my part, is ok. but, Is it ok to delete the `package-lock.json`?

**Comment by miesgre** [comment]
> From my part, is ok. but, Is it ok to delete the `package-lock.json`?

In the package-lock.json there are some package updates

- [core-js](https://github.com/zloirock/core-js) updated to 3.23.2
- [paella-basic-plugins](https://github.com/polimediaupv/paella-basic-plugins) updated to 1.0.16 
- [paella-core](https://github.com/polimediaupv/paella-core) updated to 1.1.5

**Comment by mliradelc** [comment]
Ok, I misread the commit, With more than 7,000 lines deleted and without the change as shown in git, I false believe that was deleted.

**Comment by yokoul** [comment]
Unfortunately, as the change are correctly supported on multiple browser, is not working with safari and iOS. 

imageHLS live dualstream multiple audio

imageHLS vod dualstream multiple audio

**Pull request merged**
