### PR TITLE
MH-13304 Multi-value consistent with multi-select

### PR DESCRIPTION
**Pull request by KatrinIhler**
Make the behavior of the multi-value metadata fields consistent with that of the multi-select fields.

### CODE REVIEW

**Comment by KatrinIhler** [comment]
@staubesv Can you maybe take a look at this in time for the release today? I realized when reviewing your PR that the behavior of these fields is not consistent at all anymore due to my changes to multi-select.

**Comment by staubesv** [comment]
@staubesv No, I'm on a seminar today, sorry.

**Comment by KatrinIhler** [comment]
@gregorydlogan Maybe you can take a look at this?

**Comment by staubesv** [comment]
@KatrinIhler & @gregorydlogan The workshop finished earlier than expected ;-) I'm on it...

**Review by staubesv — APPROVED** [review]

**Pull request merged**
