### PR TITLE
MH-12639 update angular-chosen to 1.8.0

### PR DESCRIPTION
**Pull request by krinnewitz**
This updates angular-chosen to version 1.8.0. With this version, two-way
data binding is working. Unfortunately, it is not possible to include
angular-chosen through bower since this pulls in a very recent version
of jquery which breaks lots of other stuff.

You can see the now working two-way data binding in action when you open
the  video-editor and play around with the upper and lower drop-downs
where the workflow can be selected. Before this patch. the drop-downs
used to become out of sync. Now, the model is updated correctly and they
always share the same value.

This work is sponsored by SWITCH.

### CODE REVIEW

**Comment by krinnewitz** [comment]
Hi @gregorydlogan , the modifications you made to angular-chosen are removed with this patch. It would be great if you could check if this doesn't break anything. Fingers crossed :smile:

**Comment by gregorydlogan** [comment]
@krinnewtiz thanks for this. It was always a nasty hack, I'm glad it's gone. I'll take this review, although I don't see how in the mobile ui :-)

**Comment by krinnewitz** [comment]
@gregorydlogan thanks. You could give google chrome's developer mode a try. It has a "mobile mode" (ctrl+shift+M when developer tools are open). You can select different devices there and see how the admin UI would look on them.

Edit: Never mind. Someone just made me aware that you propably meant you were using github on your phone and couldn't finde the "review" button. This actually makes sense :-)

**Comment by gregorydlogan** [comment]
Ok, this actually breaks things I think.  STR, with dev tabs open:

1. Start uploading an event, get to the Access Policy tab
2. Select an ACL role (ie, bring the chosen popup up)
3. Scroll back and forth between the top and bottom of the dropdown

Without this patch you will see repeated requests to admin-ng/resources/ROLES.json?filter=role_target:ACL&limit=100&offset=6, with it you will not see any requests.

**Comment by staubesv** [comment]
@krinnewitz The changes to angular-chosen are fortunately relatively compact (see https://bitbucket.org/opencast-community/opencast/pull-requests/1349/mh-12016-fix-and-improve-user-group-role/diff#chg-modules/matterhorn-admin-ui-ng/src/main/webapp/scripts/lib/angular-chosen.js). 

Could you please just copy-paste the changes into angular-chosen 1.8 (this PR)?

**Comment by staubesv** [comment]
@gregorydlogan The customizations are integrated now in angular-chosen 1.8. Better?

**Comment by gregorydlogan** [comment]
Much!  Thanks guys!

**Pull request merged**
